### ISSUE TITLE
Browserify cannot find runnable module when using require('mocha')

### ISSUE THREAD

**Issue by taylor-smith** [mochajs/mocha#1316] opened 2014-08-20 17:19 UTC
When compiling test scripts into a single monolith using Browserify, I hit the error:

```
module "./runnable" not found from "../node_modules/mocha/mocha.js".
```

Line 846 of mocha.js requires runnable as such:

``` javascript
var Runnable = require('./runnable');
```

Does this need to be amended as such?

``` javascript
var Runnable = require('./lib/runnable');
```

If this is true, it seems there are several file paths that need to be renamed. Is there a workaround?

**Comment by wejrowski** [comment] 2015-06-16 23:14
Same problem. Trying to run mocha as a stand alone in a nashorn environment.

**Comment by ehgoodenough** [comment] 2015-10-25 00:25
Still getting this issue, both on browserify and webpack.

**Comment by dfcreative** [comment] 2015-12-21 02:14
@taylor-smith Hello! I wonder why this issue is closed, the problem is still actual. Are there no plans on making mocha browserifyable?

**Comment by strugee** [comment] 2016-02-22 04:40
@dfcreative if you look through the conversation, @taylor-smith wasn't the one who closed the issue. @boneskull did.

**Comment by boneskull** [comment] 2016-02-23 18:16
@dfcreative @taylor-smith @strugee 

Mocha bundles itself with browserify.  You need to include `node_modules/mocha/mocha.js` in your bundle.  I believe this can be accomplished by various means depending on your use case.

**Comment by boneskull** [comment] 2016-02-23 18:17
(`require('mocha')` gives you `node_modules/index.js` which is not what you want)

**Comment by dfcreative** [comment] 2016-02-23 22:46
@boneskull yes, I know, it is difficult to understand why mocha uses browserify to build it’s own browser `mocha.js`, but does not provide `browser` entry competible with other packages.
I tried to fork mocha and make it browserifyable, but the change was quite big and inpredictable that it would took months to merge it with no guarantees, so I just gave up and wrote [tst](https://github.com/dfcreative/tst), a minimalistic and fast mocha-compatible replacement for node and browser.

**Comment by boneskull** [comment] 2016-02-23 23:10
@dfcreative If it's possible to provide a `browser` entry which specifies `mocha.js` and also use it for replacing modules, then we could do that--though I don't think it is?  Seems strange.  Alternatively, we could simply leverage a package like `aliasify` for the module replacement and use `browser` to specify `mocha.js`.

Seems fairly straightforward, unless I'm missing something.

I also don't quite understand the use case for browserifying Mocha itself.  Can someone explain this?

**Comment by boneskull** [comment] 2016-02-23 23:11
I see this (from wejrowski)

> Same problem. Trying to run mocha as a stand alone in a nashorn environment

But it's not clear what this means.

**Comment by dfcreative** [comment] 2016-02-24 02:57
@boneskull browserifying mocha would be useful with browserify servers for dev, like beefy or budo.

**Comment by boneskull** [comment] 2016-02-24 16:03
@dfcreative Aren't these tools usually used for running your *app*, not your tests (is that their *intent*)?

**Comment by dfcreative** [comment] 2016-02-24 18:35
@boneskull no, they are only for development tasks afaik

**Comment by boneskull** [comment] 2016-02-24 19:47
Well, yes, they are not intended for production use.  I meant they are for *running your app in "development" mode*.

I can infer from [beefy's docs](https://www.npmjs.com/package/beefy) that it's meant to serve a directory, ostensibly with `.html` files in it.

I'd recommend using something like [karma-mocha](https://www.npmjs.com/package/karma-mocha) and [karma-browserify](https://www.npmjs.com/package/karma-browserify) to run tests.  You can use the following bit of configuration to get the HTML reporter to display in the browser (using `karma-chrome-launcher` or equivalent):

```js
// karma config object
{
  frameworks: ['browserify', 'mocha']
  files: ['src/**/*.js', 'test/**/*.js'],
  preprocessors: {
    '**/*.js': ['browserify']
  },
  browserify: {
    debug: true
    // plus whatever else; package.json settings will be read as well
  },
  reporters: ['progress'], // or whatever console reporter you wish (or none?)
  client: {
    mocha: {
      reporter: 'html'
    }
  },
  autoWatch: true, // reruns on file change
  singleRun: false, // "karma start" will run tests + stay open
  browsers: ['Chrome']
}
```

That being said, I'll try to see if the `browser` field supports what we want to do here.  Reopening.

**Comment by dfcreative** [comment] 2016-02-24 22:08
> running your app in "development" mode.
@boneskull yes, exactly, thanks for understanding. That is what I meant - mocha is a serious runner, same as karma, webdriver and other heavy testing stuff. In practice of developing atomic packages basically it is enough to group pieces of code in a single file, and be able to turn them on/off. Everything else should be as easy as possible, just set up and go.
With karma/mocha setting up env takes more time than writing the package. Especially for browser. The ideal solution for that would be just `var test = require('mocha');`, but that is exactly what is done in tst/tap/ava/tape. Unfortunately within them afaik only tst works in browser.

**Comment by boneskull** [comment] 2016-02-24 22:34
yes, making test files "node-able" is going to be the most basic usage of mocha at some point here

**Comment by JoshuaKGoldberg** [comment] 2023-12-27 05:56
This issue has been open and accepted for well over 5 years and hasn't seen a PR. Also:

> When compiling test scripts into a single monolith using Browserify, I hit the error

Browserify is, at this point, relatively legacy software. It's not something we're going to put a lot of effort into supporting. Closing this issue as wontfix / aged away. Someone please yell at me if I'm wrong here.

...and if you do, please post a recent isolated reproduction for how to demonstrate this issue. None of us on the team use Browserify regularly that I know of. 😄

**Closed by JoshuaKGoldberg** 2023-12-27 05:56 UTC
Labels: type: bug, status: accepting prs
