### ISSUE TITLE
Please change color scheme

### ISSUE THREAD

**Issue by octref** [mochajs/mocha#1200] opened 2014-04-24 19:56 UTC
I've read through https://github.com/visionmedia/mocha/issues/802 and https://github.com/visionmedia/mocha/issues/590

I believe I've found where the issue lies:
Snippet from base.js
https://github.com/visionmedia/mocha/blob/master/lib/reporters/base.js

```
exports.colors = {
    'pass': 90
  , 'fail': 31
  , 'bright pass': 92
  , 'bright fail': 91
  , 'bright yellow': 93
  , 'pending': 36
  , 'suite': 0
  , 'error title': 0
  , 'error message': 31
  , 'error stack': 90
  , 'checkmark': 32
  , 'fast': 90
  , 'medium': 33
  , 'slow': 31
  , 'green': 32
  , 'light': 90
  , 'diff gutter': 90
  , 'diff added': 42
  , 'diff removed': 41
};

var color = exports.color = function(type, str) {
  if (!exports.useColors) return str;
  return '\u001b[' + exports.colors[type] + 'm' + str + '\u001b[0m';
};
```

So the color function takes in a type and uses the conversion table above to get the ANSI escape color.
A chart can be found here:
http://en.wikipedia.org/wiki/ANSI_escape_code#CSI_codes

As you can see:
![screenshot from 2014-04-25 03 09 43](https://cloud.githubusercontent.com/assets/4033249/2793785/5ffc45e6-cbe4-11e3-88fc-7f6ab027e9a1.png)

Seems to be a closed-source terminal from IBM AIX.
I believe nobody is using mocha on it. (Correct me if I'm wrong)

Furthermore, I found the ECMA specification:
http://www.ecma-international.org/publications/files/ECMA-ST/Ecma-048.pdf
Here is page 62:
![mocha2](https://cloud.githubusercontent.com/assets/4033249/2793831/ef79afc4-cbe4-11e3-8f04-6b31c1c0cc0f.png)

Color 90-99 are not in the specification. Most terminals wouldn't care implementing these colors correctly and god knows what color they'll fall back into.
And not everyone uses iTerm2, which has a contrast setting.
Please use color 30-37, if you want increased intensity then ```\u001b[30;1m``` would use the intense variant. 
I think users are only responsible for configuring their terminals so the 16 colors look great on their bg/fg colors. So please don't just say *"It's the theme's fault"* and close the issue. It's mocha's problem not using color from the standard palette.

**Comment by legomind** [comment] 2015-10-07 21:14
This is still as issue when using solarized color scheme:

<img width="511" alt="screenshot12" src="https://cloud.githubusercontent.com/assets/3710857/10351293/ca22b552-6d16-11e5-80c8-fde4af2d89d2.png">

**Comment by mikeerickson** [comment] 2015-11-20 22:49
Any chance this has been addressed somewhere that works with release version.  I have tried all the various tweaks outlined above, but nothing works.   My issue is that I cant see any of the messages in terminal (running MobaXterm on Windows).

**Comment by octref** [comment] 2015-12-02 03:33
@boneskull 
I just see this get reopened. How do you plan to fix it?

**Comment by boneskull** [comment] 2015-12-02 03:34
I'm just going to use [chalk](https://www.npmjs.com/package/chalk) so nobody can complain Mocha uses weird ANSI escape sequences.

**Comment by boneskull** [comment] 2015-12-02 03:36
if people have a problem with the colors thereafter, it's really, truly, not Mocha's fault

**Comment by boneskull** [comment] 2015-12-02 03:39
(we're locked to v0.4.0 of chalk to keep node v0.8.0 support--its default npm version doesn't grok carets)

**Comment by boneskull** [comment] 2015-12-02 03:39
oops.

**Comment by boneskull** [comment] 2016-01-28 20:29
reopening since this had to be reverted.

we can still use standard colors by using chalk's dependencies (maybe), but not chalk itself.  this basically amounts to rewriting chalk *without* functionality which can't be shimmed in IE8 (`Object.defineProperty()` is the gotcha; [explanation](https://www.npmjs.com/package/es5-shim#may-fail)

**Comment by danielstjules** [comment] 2016-01-28 20:52
Are you planing on reverting all of chalk via https://github.com/boneskull/mocha/commit/ba3378a336dad69b10970cd171d109f3160923ac ?

**Comment by boneskull** [comment] 2016-01-28 20:55
@danielstjules yes

**Comment by boneskull** [comment] 2016-01-28 20:57
@danielstjules well, it's [this changeset](https://github.com/boneskull/mocha/commit/e1bf72898162b558dd8a7e53c102e187f457b926) now

**Comment by danielstjules** [comment] 2016-01-28 20:58
Seems like we can work around that by forcing use of the defineProperty/defineProperties shim in IE8 though?

**Comment by danielstjules** [comment] 2016-01-28 21:03
I'm just getting off lunch break now so I don't have time to test, but I can take a stab at an alternative tonight.

**Comment by boneskull** [comment] 2016-01-28 21:05
afaik there is no such shim that's functional.  anyway I was having a hell of a time getting a shim to work; would appreciate the help

**Comment by danielstjules** [comment] 2016-01-28 21:26
I can help dig into this 6 hours from now, but not sure how much of a rush we're in.

**Comment by boneskull** [comment] 2016-01-28 21:45
It's not of huge importance.  I did it in the first place because I thought it was low-hanging fruit.  Boy, was I wrong...

**Comment by leighman** [comment] 2016-02-10 10:46
If this gets fixed please consider using 'dim' in place of 'gray' which fixes output on the solarized theme.

Let me know if there's something I can do to help.

**Comment by dschinkel** [comment] 2016-02-27 04:25
this is such a pain in the ass, I have the same issue in Webstorm, Unless I change the console colors to very light background, the passing text won't show because it's dark grey.  I'd love to have a dark background for my console in Webstorm but if I do that then I can barely see the passed text for tests since I can't change that damn color!

**Comment by jdmarshall** [comment] 2016-03-01 19:35
My coworker is having the same problem with my new test harness and I can't figure out how to get him a color scheme that doesn't suck on a black background.

**Comment by boneskull** [comment] 2016-03-01 23:05
anyway, this is more of a "next major" thing, but will definitely be addressed

**Comment by jdmarshall** [comment] 2016-04-01 20:27
I ended up changing the color mappings on my terminal to improve the contrast on the dark grey color.  But it's a weird color selection in any context so I'd appreciate it if we got it fixed.

**Comment by wenwuwu** [comment] 2016-06-16 12:04
I am still having this problem with solarized color scheme. I am annoyed.

**Comment by ScottFreeCode** [comment] 2016-06-30 20:40
@boneskull What if we refactored the reporters a bit so that console-output reporters inherit from something that uses Chalk but the HTML reporter (and any hypothetical [programmatic or null reporter](2340#issuecomment-229781918)) doesn't inherit this and then we can exclude the Chalk-using reporters from the browser bundle (assuming that isn't going to break intended PhantomJS usage...)?

**Comment by boneskull** [comment] 2016-07-01 07:24
I can't for the life of me reproduce a terminal with a "solarized dark" color scheme wherein mocha won't be readable

**Comment by boneskull** [comment] 2016-07-01 07:27
can someone tell me how to reproduce this on a mac with either iTerm or Terminal?

we *did* fix the diff colors some time ago via a PR.

**Comment by boneskull** [comment] 2016-07-01 07:29
See #2164 for a proposed fix.  This fix LGTM *except* for my inability to assert it fixes any problems.

**Comment by r-tanner-f** [comment] 2016-07-01 17:54
@boneskull You should be able to reproduce by downloading the official [Solarized theme for iTerm](https://raw.githubusercontent.com/altercation/solarized/master/iterm2-colors-solarized/Solarized%20Dark.itermcolors). Open the file with Finder, then open iTerm. Load the colors by opening Preferences, selecting the Colors tab, opening the "Load presets" menu, and choose Solarized Dark.

Then run any test and you should see something like this:
![image](https://cloud.githubusercontent.com/assets/4127200/16529800/c5098aba-3f79-11e6-865f-91db4d9f25c5.png)

**Comment by r-tanner-f** [comment] 2016-07-01 18:42
I added this on the PR too but, it's starting to look like this is mostly a problem with the Solarized theme. It's using bright black as its background, which seems a little odd.

FWIW, I'd say the PR definitely fixes the original issue here, but maybe not the problem people are having with Solarized + Mocha. I tend to get around this problem anyway by `npm link`ing my own copy of Mocha so I can choose my own colors. Would custom colors be worth exploring?

**Comment by boneskull** [comment] 2016-07-01 19:51
@r-tanner-f I did exactly that:

![image](https://cloud.githubusercontent.com/assets/924465/16532980/76b7c366-3f8a-11e6-9fe6-454c590508bd.png)

**Comment by boneskull** [comment] 2016-07-01 19:52
@r-tanner-f Maybe the "minimum contrast" is making it so I cannot reproduce.

![image](https://cloud.githubusercontent.com/assets/924465/16533010/a84faa74-3f8a-11e6-99ce-0c7ee669fb5c.png)

**Comment by boneskull** [comment] 2016-07-01 19:54
Yep.  When I slide it to the left, nothing is shown.

You can see here that the problem is with *the solarized theme itself*:

![image](https://cloud.githubusercontent.com/assets/924465/16533065/fc691866-3f8a-11e6-8f74-5262596d7d34.png)

**Comment by boneskull** [comment] 2016-07-01 20:22
While #2164 seems "more correct", and *potentially* a low-impact change, it won't help anybody running a "Solarized Dark" theme in iTerm.

Running the official "Solarized Dark" theme in Terminal.app seems to work fine without any modifications.

Let's recap:

- OP complained about jacked-up color scheme
- To the credit of the OP, at the time the "diff" colors were jacked-up
- Someone sent a PR to fix the diff colors, and we merged that
- Along the way, people were complaining that the "Solarized Dark" theme didn't work
- tj was loathe to change the colors based on a a terminal theme some were using
- Ostensibly to convince tj, users noted the reporters used non-standard ANSI colors
- Others argued that you're unlikely to be using a terminal that doesn't support the non-standard colors
- Later, I attempted to leverage the `chalk` module for colors so Mocha could absolve itself of choosing them (and finally end the debate), but that caused mass brokenness, and had to be reverted.
- @jtangelder sent #2164, which removes the non-standard colors and uses "standard" ones
- As some users suspected, the non-standard colors had *no impact* on some users of "Solarized Dark", who still have problems with visibility
- In fact, certain users w/ certain terminal configurations can notice no difference whatsoever when the changes in #2164 are applied.

I can now say with certainty, ***if the colors Mocha uses aren't visible, your color theme is broken and/or your terminal is misconfigured***.  If you are having problems wherein Mocha fails to display visible text, you will *also* have problems using *other* programs which leverage the same ANSI colors.

If we changed the colors so theme *A* will display, there's no guarantee users of popular color theme *B* won't suffer invisible text as a result, because color theme *B* may be broken as well in a different manner.  In either case, a terminal can be misconfigured.

I still may be interested in merging #2164, but I am going to close *this* ticket.  It's not really in Mocha's best interest to play whack-a-mole with invisible terminal colors.  While tj may have been ultimately correct--and I had suspected as much--neither one of us did a great job of communication about it.

**If you are having this problem**:  Reconfigure your terminal and/or scheme to ensure all valid ANSI colors are clearly displayed.  
**For iTerm users**:  You can still use "Solarized Dark", but increase the "minimum contrast" setting.  
**For anyone else**:  I don't know; if you have a workaround, please post it here.

**Closed by boneskull** 2016-07-01 20:22 UTC
Labels: chore

**Comment by dschinkel** [comment] 2016-07-01 20:35
All I know is for me, I spent a lot of time trying to get mocha test colors fixed so that I could actually view it well in Solarized theme and it was impossible.  I ended up having to make my console completely white in order to be able to run mocha tests and see them clearly.   Most people do not run their tests in console, they do, but they usually have console embedded in an IDE like webstorm or other.  I was able to try to tweak some things via the Webstorm IDE but still no luck, it's mocha...trust me.

**Comment by boneskull** [comment] 2016-07-01 21:14
> Most people do not run their tests in console

Do you have data to support this?

> I was able to try to tweak some things via the Webstorm IDE but still no luck

Mocha works fine for me in WebStorm terminal, using any color theme.

I understand you are frustrated, but I would prefer to leave this issue unlocked so people can post workarounds or proper terminal configurations.

**Comment by dschinkel** [comment] 2016-07-01 21:21
So you're telling me most devs who use Sublime, Atom, Webstorm, etc. don't try using console embedded inside them and are always toggling back and fourth between their IDE or Editor and Console?  I doubt that.  Sure I can come up with proof, let me do a short video soon that illustrates the inability to tweak mocha's default terrible color scheme.

**Comment by dschinkel** [comment] 2016-07-01 21:27
Besides my bitching :)  What I'll also do is come up with a video showing a work-around, not really the colors I'd prefer, and you have to change the terminal background to white but that's what I had to do to get around the problem.

**Comment by boneskull** [comment] 2016-07-01 21:30
> So you're telling me most devs who use Sublime, Atom, Webstorm, etc. don't try using console embedded inside them and are always toggling back and fourth between their IDE or Editor and Console

I use Atom and WebStorm embedded terminals in addition to iTerm (all regularly), and have never had this problem.

**Comment by boneskull** [comment] 2016-07-01 21:31
> inability to tweak mocha's default terrible color scheme.

You can't tweak its color scheme, but you *can* adjust your terminal. :smile:

**Comment by jdmarshall** [comment] 2016-07-01 23:09
> I use Atom and WebStorm embedded terminals in addition to iTerm (all regularly), and have never had this problem.

It's a problem in the 'Darkula' theme, which almost everyone I observe using IntelliJ products seems to use now.

**Comment by dschinkel** [comment] 2016-07-01 23:24
I see... I'll look at that thx @jdmarshall

**Comment by boneskull** [comment] 2016-07-02 03:13
@dschinkel 

![image](https://cloud.githubusercontent.com/assets/924465/16537948/dab40810-3fc7-11e6-9c56-2a6dba9a6054.png)

![image](https://cloud.githubusercontent.com/assets/924465/16537953/ed9986ee-3fc7-11e6-82b8-de46cac835b9.png)

Before:

![image](https://cloud.githubusercontent.com/assets/924465/16537963/4055c51e-3fc8-11e6-8582-eb7cb3201053.png)

After:

![image](https://cloud.githubusercontent.com/assets/924465/16537960/1f595448-3fc8-11e6-991e-e00db2375b03.png)

**Comment by dschinkel** [comment] 2016-07-02 03:14
@boneskull pretty sure I have tried that but I'll check it out again to be sure.

**Comment by boneskull** [comment] 2016-07-02 03:15
@jdmarshall thanks for the direction on that.

**Comment by boneskull** [comment] 2016-07-02 03:15
also note above "ANSI: black" is actually white.

**Comment by dschinkel** [comment] 2016-07-02 03:26
Yep that's the work around I talked about.  That makes the background of your console white for the terminal inside Webstorm.

**Comment by dschinkel** [comment] 2016-07-02 03:42
I tried Dracula again, like you did tehre, and I still get the same problem I had originally, before my workaround which was to change the background of the terminal to white so I could at least read the dark grey text, the problem you see here that I still get with Dracula if I revert back to trying to use Dracula:

<img width="1680" alt="screen shot 2016-07-01 at 10 41 08 pm" src="https://cloud.githubusercontent.com/assets/338798/16538070/0beeaf06-3fdd-11e6-9ede-32bae6962f4e.png">

**Comment by boneskull** [comment] 2016-07-02 03:55
> Yep that's the work around I talked about. That makes the background of your console white for the terminal inside Webstorm.

There's is no need to make the background white, nor is that what my change in the screenshot did.

I'm trying to understand the problem you're seeing.  If that "exception" text is too dark, make it lighter by increasing the brightness on the "dark gray":

![image](https://cloud.githubusercontent.com/assets/924465/16538100/ecf6b7f6-3fcd-11e6-9783-fe5a3d37851a.png)

![image](https://cloud.githubusercontent.com/assets/924465/16538111/161dfaa4-3fce-11e6-9441-6c986ea1326c.png)

If you're still having trouble, you may wish to consult the WebStorm documentation and/or contact someone at JetBrains.

**Comment by dschinkel** [comment] 2016-07-02 03:57
Oh believe me I have consulted with them.  Oh well...thanks for providing the info.  If I find out the solution I'll post it on my side.  Not sure why yours is working and mine is not but hopefully I'll pinpoint it.

**Comment by boneskull** [comment] 2016-07-02 04:05
@dschinkel Put [this file](https://gist.github.com/boneskull/c349c3d8732ecd1962680c9a29287d70) in your `colors` folder, then restart WebStorm.

On a mac, this is `~/Library/Prefernces/WebStorm<version>/colors/`.  

But that's about the extent of what I can do to support JetBrains' products.  Again, this is not a Mocha-specific issue.

**Comment by dschinkel** [comment] 2016-07-02 04:06
@boneskull yea I've tried that :).  Thanks though.

**Comment by dschinkel** [comment] 2016-07-11 18:10
Just FYI, Webstorm just came out with a new version that apparently has fixed the problem at least it did for me http://bit.ly/29vZhiQ

**Comment by jeffvandyke** [comment] 2017-12-15 18:40
Just wanted to throw out there that I'm still bumping into this issue on gnome-terminal and xfce4-terminal, and I know this has a lot of talk, but as a new user of mocha, it's quite annoying :( It would be great if there was just a way to change, maybe via CLI, what color code gets used for secondary text output.

**Comment by r-tanner-f** [comment] 2017-12-15 19:01
@jeffvandyke Are you using Solarized Dark? Much as I love the theme, it's simply broken. It uses Bright Black as the background color. Simple as that.

Take a look at the values section: http://ethanschoonover.com/solarized#the-values 

And the usage guide: http://ethanschoonover.com/solarized/img/solarized-values-dark.png

If the background color was Black that might be forgivable, but I would never expect *Bright Black* to be the same as the background color. I've had this issue with other console applications and Solarized Dark as well. This isn't limited to Mocha at all.

**Comment by jeffvandyke** [comment] 2017-12-15 22:06
Gotcha, that does make sense. My workaround was to set Bright Black to one of the lighter gray colors in my terminal, but I see how solarized dark doesn't fit perfectly for 16-color terminals. Thanks!

**Comment by tpict** [comment] 2018-01-22 21:17
Many of the popular [base16](https://github.com/chriskempson/base16) themes are also affected by this.
