### ISSUE TITLE
global leaks in Chrome and Firefox

### ISSUE THREAD

**Issue by hunterloftis** [mochajs/mocha#695] opened 2012-12-28 18:00 UTC
Tests that pass in Safari and iOS fail in Chrome and Firefox with 'global leak detected.'

- Chrome 23.0.1271.101.
- FF 17.0.1.
- Mocha 1.7.4, browser build.
- Safari 6.0.2

Chrome error:
```
Error: global leak detected: __screenCapturePageContext__
    at Runner.checkGlobals (http://skookum.github.com/s4client/vendor/mocha.js:3907:21)
    at Runner.<anonymous> (http://skookum.github.com/s4client/vendor/mocha.js:3794:44)
    at Runner.EventEmitter.emit (http://skookum.github.com/s4client/vendor/mocha.js:235:20)
    at http://skookum.github.com/s4client/vendor/mocha.js:4138:14
    at done (http://skookum.github.com/s4client/vendor/mocha.js:3700:5)
    at http://skookum.github.com/s4client/vendor/mocha.js:3712:9
    at onAccount (http://skookum.github.com/s4client/test/test.accounts.js:29:16)
    at onAccount (http://skookum.github.com/s4client/src/status4.js:59:39)
    at ajaxSuccess (http://skookum.github.com/s4client/vendor/zepto.js:1010:22)
    at XMLHttpRequest.xhr.onreadystatechange (http://skookum.github.com/s4client/vendor/zepto.js:1165:16)
```

Firefox error:

```
global leaks detected: console, getInterface
Runner.checkGlobals@http://skookum.github.com/s4client/vendor/mocha.js:3905
Runner/<@http://skookum.github.com/s4client/vendor/mocha.js:3794
EventEmitter.emit@http://skookum.github.com/s4client/vendor/mocha.js:235
Runner.runTests/next/</<@http://skookum.github.com/s4client/vendor/mocha.js:4138
done@http://skookum.github.com/s4client/vendor/mocha.js:3700
Runnable.run/<@http://skookum.github.com/s4client/vendor/mocha.js:3712
onAccount@http://skookum.github.com/s4client/test/test.accounts.js:29
onAccount@http://skookum.github.com/s4client/src/status4.js:59
ajaxSuccess@http://skookum.github.com/s4client/vendor/zepto.js:1010
$.ajax/xhr.onreadystatechange@http://skookum.github.com/s4client/vendor/zepto.js:1165
```

**Comment by danielstjules** [comment] 2015-03-09 04:50
Closing since the issue was caused by browser plugins polluting the global namespace, and global detection has been disabled by default (as per tj's suggestion). Global detection is opt-in using `mocha.checkLeaks();`

**Closed by danielstjules** 2015-03-09 04:50 UTC
