### ISSUE TITLE
Runner `end` event can’t be caught if the `grep` option matches no tests

### ISSUE THREAD

**Issue by Mr0grog** [mochajs/mocha#3065] opened 2017-10-11 01:35 UTC
### Prerequisites

* [x] Checked that your issue isn't already filed by cross referencing [issues with the `common mistake` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Acommon-mistake%20)
* [x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
* [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
* [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with:
`node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend avoiding the use of globally installed Mocha.

### Description

When running Mocha programmatically or in a browser, `mocha.run()` returns the test runner instance and event handlers can be attached to it. However, when the `grep` option is used and it matches no tests, ]it emits the `end` event synchronously](https://github.com/mochajs/mocha/blob/master/lib/runner.js#L621-L623) before the runner is ever returned from `mocha.run()` and before any third-party code could attach a listener.

I know I can work around this by providing a callback to `mocha.run()`, but it still seems reasonable to expect that you’d always have an opportunity to attach an event listener before the `end` event fires.

### Steps to Reproduce

If I have a test suite at `/single-test.js` that looks like:

```js
describe('Test suite', function () {
  it('A single passing test', function() {
    // this passes
  });
});
```

And I run the following:

```js
const Mocha = require('mocha');
const mocha = new Mocha({ui: 'bdd', grep: /unmatchable/});
mocha.addFile('/single-test.js');
mocha
  .run()
  .on('end', () => console.log('End event handled!'));
```

**Expected behavior:** I expect “End event handled!” to be logged to the console.

**Actual behavior:** The test suite runs, but my handler does not.

**Reproduces how often:** 100%

### Versions

Mocha 4.0.1

**Comment by ScottFreeCode** [comment] 2017-10-11 02:50
I wonder if fixing #2753 would automatically fix this too.

**Comment by Mr0grog** [comment] 2017-10-11 04:54
Ah! Yes, that definitely would (assuming `end` is guaranteed to come after `start` :P )

**Comment by boneskull** [comment] 2017-10-17 04:17
duplicate of #2753

**Closed by boneskull** 2017-10-17 04:17 UTC
