### ISSUE TITLE
race condition on deprecation warnings in browser

### ISSUE THREAD

**Issue by boneskull** [mochajs/mocha#3832] opened 2019-03-12 21:37 UTC
when we use `process.nextTick` in a browser, of course it's not really `process.nextTick`.  it's from [process](https://npm.im/process) which is doing something really odd that I don't understand with queues.  but I digress.

our `process.emitWarning` polyfill uses `process.nextTick`, which is *only* used in the browser, since all supported Node.js versions have `process.emitWarning`.

When printing deprecation messages, it's possible for Mocha to stop running when executed in a headless browser (via something like puppeteer) *before* the deprecation message gets printed, due to use of the `process.nextTick` polyfill.

I've found just using `setTimeout` here instead seems to avoid this problem.

We currently do not encounter it in our builds because we don't run any integration tests in a browser.

A fix for this will be part of a forthcoming PR; just wanted to note it.

**Comment by boneskull** [comment] 2019-03-12 22:09
Looks like `setTimeout` is still flaky.  I guess we should just output the warning synchronously. :shrug:

**Comment by angie4u** [comment] 2019-10-21 00:09
Hi @boneskull , I tried to reproduce this race condition and it seems working synchronously(Deprecation message is always printed first). 

[Retro step]
1. Reproduce this situation using Karma
2. Perfome mocha test and print out deprecation message(1000 times).
3. Deprecation message always printed out before Mocha test.

[Screenshot]
![image](https://user-images.githubusercontent.com/16282358/67168781-73a71900-f3e2-11e9-9dbb-6f4085aff37e.png)

![image](https://user-images.githubusercontent.com/16282358/67168793-86215280-f3e2-11e9-8837-1419a6c11cc3.png)

**Comment by boneskull** [comment] 2019-10-21 19:18
@angie4u thanks for looking at this.  unfortunately I didn't give myself enough information here to remember how I was running into the problem.  I'm going to _guess_ I ran into it when using [mochify](https://npm.im/mochify).

I still have some old code hanging around which tries to get many integration tests working in the browser, but it's probably rotten now; will need to revisit before I can provide a reproduction plan.

**Comment by JoshuaKGoldberg** [comment] 2024-01-15 04:48
Closing as non-actionable since it's been a few years and I don't know how to reproduce this locally. If anybody has a reproduction, please do post back or file a new issue. Cheers!

**Closed by JoshuaKGoldberg** 2024-01-15 04:48 UTC
Labels: area: browser, unconfirmed-bug, status: accepting prs
