### ISSUE TITLE
Import error in ESM *.spec.js file results in commonjs loading to be used

### ISSUE THREAD

**Issue by TheSlowGrowth** [mochajs/mocha#4697] opened 2021-07-22 15:28 UTC
### Prerequisites

- [x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend that you _not_ install Mocha globally.

### Description

- Assume a test file with a broken import statement, e.g. due to the requested package not being installed.
- The containing package is ESM, so package.json: `"type": "module"`
- this results in very confusing errors: `Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: myTestFile.spec.js`

### Steps to Reproduce
- Assume a test file with a broken import statement, e.g. due to the requested package not being installed.
- The containing package is ESM, so package.json: `"type": "module"`
- Mocha tries to import the file via `import`, due to `mocha/lib/esm-utils.js:42`
```javascript
exports.requireOrImport = hasStableEsmImplementation
  ? async file => {
      if (path.extname(file) === '.mjs') {
        return formattedImport(file);
      }
      try {
        return dealWithExports(await formattedImport(file));
      } catch (err) {
        if (
          err.code === 'ERR_MODULE_NOT_FOUND' ||
          err.code === 'ERR_UNKNOWN_FILE_EXTENSION' ||
          err.code === 'ERR_UNSUPPORTED_DIR_IMPORT'
        ) {
          return require(file);
        } else {
          throw err;
        }
      }
    }
  : implementationOfRequireOrImportForUnstableEsm;
```
- If the loaded file has a problem in its imports, the catch statement catches the error and tries to load the file as a commonjs module. 
- this results in very confusing errors: `Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: myTestFile.spec.js`

**Expected behavior:** The import error from the test file is displayed so I can diagnose it (especially important for CI where I can't easily reproduce the error locally)

**Actual behavior:** The import error from the test file is hidden, instead the test file gets imported with require() resulting in another error message that has nothing to do with the actual problem

**Reproduces how often:** 100%

### Versions

- The output of `mocha --version`: command not found
- The output of `node node_modules/.bin/mocha --version`: 9.0.2
- The output of `node --version`: 16.5.0
- Your operating system
  - name and version: OSX 10.15.7 & ubuntu20.04
  - architecture (32 or 64-bit): 64bit
- Your shell (e.g., bash, zsh, PowerShell, cmd): zsh
- Any third-party Mocha-related modules (and their versions): none
- Any code transpiler (e.g., TypeScript, CoffeeScript, Babel) being used (and its version): typescript, but replicates with *.js files as well

**Comment by juergba** [comment] 2021-07-22 15:37
duplicate of #4675.
This issue is already fixed and will be published with our next release.

**Closed by juergba** 2021-07-22 15:37 UTC
Labels: duplicate
