### ISSUE TITLE
Mocha not honouring `--retries` flag

### ISSUE THREAD

**Issue by heychirag** [mochajs/mocha#4703] opened 2021-07-26 23:04 UTC
### Prerequisites

- [x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend that you _not_ install Mocha globally.

### Description

Mocha fails the test instead of retrying if the test times out.

### Steps to Reproduce

1. Use `--timeout` flag to set a specific timeout
2. Use `--retries` flag to set retries more than zero
3. Deliberately delay the test so `--timeout` flag is triggered
4. Mocha fails the test without honouring `--retries` flag

**Expected behaviour:** Test should be retried as many times as the number passed through the `--retries` flag.

**Actual behaviour:** Mocha fails the test without retrying

**Reproduces how often:** 100%

### Versions

- The output of `mocha --version` and `node node_modules/.bin/mocha --version`: 6.2.2
- The output of `node --version`: v14.16.1
- Your operating system
  - name and version: macOS 11.4
  - architecture (32 or 64-bit): 64-bit
- Your shell (e.g., bash, zsh, PowerShell, cmd): zsh
- Your browser and version (if running browser tests): N/A
- Any third-party Mocha-related modules (and their versions): N/A
- Any code transpiler (e.g., TypeScript, CoffeeScript, Babel) being used (and its version): N/A

### Additional Information

I am using Mocha with Appium and the app I am testing heavily depends on network conditions which sometimes leads to a test timeout. So reporting this as a bug and not a feature request since `--retries` flag is not being honoured.

I also asked this question on SO: https://stackoverflow.com/questions/68485310/mocha-retry-after-timeout

**Comment by juergba** [comment] 2021-07-27 07:35
@heychirag I can't reproduce your issue with Mocha v9.0.3.

```js
describe('retries', function() {
  let t = 1;
  this.retries(3);

  it.only('test1', async function() {    
    console.log(t);
    this.timeout(t++ * 1000);
    await new Promise(resolve => { setTimeout(() => resolve(1), 3500) } ); 
  });

  it('test2', function(done) {
    console.log(t);
    this.timeout(t++ * 1000);
    setTimeout(done, 3500);
  });  
});
```
Please add a simple example of your issue, thank you.

**Comment by heychirag** [comment] 2021-07-27 08:52
What about the `latest-6` release tag? Are you able to reproduce on that?

**Comment by heychirag** [comment] 2021-07-27 09:19
I am also able to reproduce on `9.0.2`. This is the error I get:

```
Error: Timeout of 10000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
      at listOnTimeout (internal/timers.js:554:17)
      at processTimers (internal/timers.js:497:7)
```

I am using `.mocharc.yaml`.

**Comment by heychirag** [comment] 2021-07-27 09:31
Something new I have discovered is that `--retries` doesn't work if the timeout happens in `before` or `beforeEach` hook.

**Comment by juergba** [comment] 2021-07-28 06:17
> I am also able to reproduce on 9.0.2 [...]

As already mentioned I need a simple example to reproduce this issue.

> What about the latest-6 release tag? Are you able to reproduce on that?

I haven't tried. We don't offer LTSupport and do not backport any fixes to earlier releases.

> Something new I have discovered is [...]

This is by design, `retries` re-runs when a `test` fails, it doesn't re-run when a `hook` fails. See [docs](https://mochajs.org/#retry-tests).

**Comment by heychirag** [comment] 2021-07-28 11:35
But that's wrong then. The hooks are part of the tests themselves. Let's say I have multiple tests and I want to perform a specific action before each of the tests. Would I rather duplicate that action in all of the tests or simply place them in the `beforeEach/afterEach` block? If I understand correctly, these hooks are meant for minimizing code duplication.

**Comment by juergba** [comment] 2021-07-28 12:28
I'm closing this issue with labels:
- invalid: no example has been provided to reproduce this issue
- duplicate: re-run on failed hooks, see eg. #4075 and more.

We are not planning to add "re-run on failed hooks" functionality at the moment.

**Closed by juergba** 2021-07-28 12:28 UTC
Labels: needs-feedback, unconfirmed-bug
