### ISSUE TITLE
Need update glob version

### ISSUE THREAD

**Issue by yuzhigang33** [mochajs/mocha#2379] opened 2016-07-18 07:04 UTC
Now mocha dependent on glob@3.2.11 and glob dependent on minimatch， the version of minimatch is too low。

Please update glob to the newest version ，it has fix the minimatch's RegExp DoS issue.

**Comment by marvinhagemeister** [comment] 2016-07-18 09:10
Duplicate of #2318, #2349, #2129

**Comment by boneskull** [comment] 2016-07-19 13:24
😭

**Closed by boneskull** 2016-07-19 13:24 UTC
Labels: duplicate
