### ISSUE TITLE
bug: mocha causing EADDRINUSE when spawning a child process in a directory

### ISSUE THREAD

**Issue by andrewrk** [mochajs/mocha#769] opened 2013-03-12 06:21 UTC
See https://gist.github.com/superjoe30/5140725 for a simple broken test case.

**Comment by jlchereau** [comment] 2015-05-07 10:00
+1 Same issue

**Comment by dasilvacontin** [comment] 2015-05-07 16:38
@jlchereau could you provide a simple breaking test?

**Comment by andrewrk** [comment] 2015-05-07 17:53
my gist url changed: https://gist.github.com/andrewrk/5140725

**Comment by jlchereau** [comment] 2015-05-07 17:56
Not sorted yet, but I now think the issue is with Webstorm, not mocha.

**Comment by dasilvacontin** [comment] 2015-05-07 18:34
@andrerk, by default, mocha executes all files under `test/**` in order to build up the suits and the tests.

In your case it means that the server is being started two times:
* when mocha executes `server.js` to build up suits/tests,
* and with the `spawn` in `test.js`.

Since the two servers try to listen at the same port, you get the EADDRINUSE.

**Comment by dasilvacontin** [comment] 2015-05-07 18:35
In general, if you get EADDRINUSE, it's probably because you are starting multiple servers, or not correctly closing previous ones before starting new ones.

**Comment by jbnicolai** [comment] 2015-07-05 15:05
Exactly. The fault lies not with mocha here.

**Closed by jbnicolai** 2015-07-05 15:05 UTC

**Comment by zwhitchcox** [comment] 2017-03-05 02:37
Except the fault does lie with mocha, because even if you catch the error, mocha still fails the testf
