### ISSUE TITLE
update jade dependency to pug

### ISSUE THREAD

**Issue by arturh85** [mochajs/mocha#2316] opened 2016-06-19 05:02 UTC
On installation of your fine module in its latest version 2.5.3 I get the following warning:

> npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade

Please change jade dependency to pug as suggested.

**Comment by marvinhagemeister** [comment] 2016-06-19 06:43
Duplicate of #2200

**Comment by boneskull** [comment] 2016-06-27 06:07
@arturh85 please search before adding an issue, thanks

**Closed by boneskull** 2016-06-27 06:07 UTC
Labels: duplicate
