### ISSUE TITLE
[Feature Request] mode to watch, then rerun failed tests only, then rerun all tests again once failed tests are fixed

### ISSUE THREAD

**Issue by jedwards1211** [mochajs/mocha#4762] opened 2021-10-01 18:08 UTC
**Is your feature request related to a problem or a nice-to-have?? Please describe.**
This would be a nice-to-have

**Describe the solution you'd like**
I run slow selenium tests with Mocha.  After I make a big change, I have to:

1. Run all my tests (which takes 10 minutes) to see what broke
2. Put `.only` on all the tests that failed and run with `--watch` to fix those tests, so I can fix them faster
3. After fixing all the tests that failed, I have to rerun all the tests again to see if my corrections broke anything else.

This is a huge hassle that I'm getting tired of.  It would be great for any of us who have this problem if Mocha had a mode where it does the following:

1. Run all tests
2. If all passed, exit 0
3. Put all the failed tests in a **failed list**
4. While the **failed list** is not empty:
  a. Rerun the **failed list** tests in watch mode (optionally also bail mode)
  b. Remove any tests that passed from the **failed list**
5. Now that the **failed list** is empty, go back to step 1

This would be a far more efficient workflow for fixing tests that get broken after major changes.

**Describe alternatives you've considered**
I guess I could respawn `mocha-broken` with a file watcher like nodemon, would be kludgey though, plus `mocha-broken` may lag behind support for new major versions of mocha.  The advantages of having this feature in core would be that it it's always supported by the latest version of mocha, and easier for users to discover and use.

**Additional context**
All users who have long-running tests (I'm sure there are many) would benefit significantly from this.  If you're a maintainer and you don't have to deal with long-running tests in any of your projects, I hope you'll try to get feedback on this idea from other people who do have that problem.

**Comment by JoshuaKGoldberg** [comment] 2023-12-27 06:09
This is, roughly, a duplicate of #1690.

**Closed by JoshuaKGoldberg** 2023-12-27 06:09 UTC
Labels: type: feature
