### ISSUE TITLE
ERROR: spawn notify-send

### ISSUE THREAD

**Issue by dinophile** [mochajs/mocha#3166] opened 2017-12-18 15:36 UTC
### Prerequisites
* [x] Checked that your issue isn't already filed by cross referencing [issues with the `common mistake` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Acommon-mistake%20)
* [x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
* [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
* [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with:
`node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend avoiding the use of globally installed Mocha.

### Description
Get this output every time I try to test:
```
An error occured. { Error: spawn notify-send ENOENT
    at exports._errnoException (util.js:1018:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn notify-send',
  path: 'notify-send',
  spawnargs: 
   [ '-i',
     '/home/cheyenne/.nvm/versions/node/v6.11.0/lib/node_modules/mocha/images/ok.png',
     '--hint=int:transient:1',
     'Passed',
     '',
     '92 tests passed in 622ms' ] }
```

### Steps to Reproduce
Just running `mocha --exit`

**Expected behavior:**
Tests all pass, and using the `--exit` flag should not produce an error.

**Reproduces how often:**
100% 

### Versions

 * The output of `mocha --version` and `node node_modules/.bin/mocha --version`:
1. 4.0.1
2. 4.0.1
 * The output of `node --version`:
6.11.0
 * The version and architecture of your operating system:
Kubuntu 16.04 64
 * Your shell (bash, zsh, PowerShell, cmd, etc.):
zsh
 * Your browser and version (if running browser tests):
 * Any other third party Mocha related modules (with versions):
Chai v3.5.0
 * The code transpiler being used:
none

**Comment by boneskull** [comment] 2017-12-21 19:56
duplicate of #3067 etc

**Closed by boneskull** 2017-12-21 19:56 UTC
