### ISSUE TITLE
No diff in html report

### ISSUE THREAD

**Issue by just-boris** [mochajs/mocha#1348] opened 2014-09-08 20:43 UTC
I've created a simple test example using latest `mocha@1.21.4` and `chai@1.9.1`

```
describe("a suite", function() {
    it("a spec", function() {
        expect(['a', 'b', 'c']).to.deep.equal(['a', 'x', 'c']);
    });
});
```

When I am running the test in console, it works good and I see a diff in output
But in browser I can't see a diff.
If need, there is a code of `runner.html`

```
<html>
<head>
  <meta charset="utf-8">
  <title>Mocha Tests</title>
  <link rel="stylesheet" href="node_modules/mocha/mocha.css" />
</head>
<body>
  <div id="mocha"></div>
  <script src="node_modules/chai/chai.js"></script>
  <script src="node_modules/mocha/mocha.js"></script>
  <script>mocha.setup('bdd')</script>
  <script>
    var expect = chai.expect;
    describe("a suite", function() {
      it("a spec", function() {
        expect(['a', 'b', 'c']).to.deep.equal(['a', 'x', 'c']);
      });
    });
    mocha.run();
  </script>
</body>
</html>
```

**Comment by NiGhTTraX** [comment] 2015-01-07 17:30
I can confirm this.

![image](https://cloud.githubusercontent.com/assets/485061/5648442/4025eafa-9697-11e4-99fd-70c6c3416130.png)

**Comment by callmevlad** [comment] 2015-01-08 22:26
Try changing your chai truncation threshold to disable truncation, like so: 

`chai.config.truncateThreshold = 0;`

**Comment by just-boris** [comment] 2015-01-09 13:17
@callmevlad It helped me, but not solves issue at all.
In console report I see a nice difference between expected and actual result
![image](https://cloud.githubusercontent.com/assets/812240/5680198/d46e809e-981a-11e4-9f78-cb8ce368aafd.png)
But in html version I see just two values without any hints

**Comment by geowarin** [comment] 2015-02-17 16:32
I have the same problem.

**Comment by dasilvacontin** [comment] 2015-02-17 21:22
Wait? Uncaught errors? That's not the same problem as the one mentioned above, right?

**Comment by CRogers** [comment] 2015-03-13 00:01
I too have this issue. It'd be great to get the diffs in the browser version.

**Comment by keithamus** [comment] 2015-08-12 12:44
`chai.config.truncateThreshold = 0;` simply tells chai to render more of the inspected values - it is not a diff, however. Diffing output is handled through the test runner (mocha) not the assertion lib.

The actual problem here is that the HTML reporter literally doesn't show diffs.

The code of how the HTML reporter constructs the failure HTML is between [L158-188](https://github.com/mochajs/mocha/blob/a81e5558f086808b682b6d196b80893d2c8926f8/lib/reporters/html.js#L158-L188). It does not check if the error has a diff, and so does not render one. It needs something along the lines of the Base Reporters diff logic (which it does upon summary); around [L193-215](https://github.com/mochajs/mocha/blob/a81e5558f086808b682b6d196b80893d2c8926f8/lib/reporters/base.js#L193-L215). 

Has the HTML reporter ever shown diffs for anyone?

**Comment by lydell** [comment] 2015-08-15 14:16
No, the HTML reporter has never shown diffs. I requested this in #1071, which was recently closed in favour of letting the assertion library do it. So this is actually a duplicate.

**Comment by keithamus** [comment] 2015-08-16 20:09
@lydell I'm not sure it'd make much sense for an assertion library to do diffs, because of the variety of output formats that'd be needed. Mocha's reporters can send coloured escape codes for terminal, and HTML tags for HTML reporting - because a mocha reporter is context aware, assertion libraries are not.

**Comment by oveddan** [comment] 2015-10-08 21:49
+1

I reported this issue in [karma-mocha](https://github.com/karma-runner/karma-mocha/issues/76)

In this bit of code:
https://github.com/mochajs/mocha/blob/58e94445beb722372589cbd2a0372bf741e7f0b7/lib/reporters/html.js#L168

The `error` object can have an `expected` `actual` properties with this data.  The html runner right now is not leveraging that in it's report.

The base runner [currently is leveraging it](
https://github.com/mochajs/mocha/blob/0956c023e4530a527f376be4ae0724ea96713ab7/lib/reporters/base.js#L200)

I can work on adding this to the html reporter.

**Comment by vvo** [comment] 2015-10-14 21:43
> I can work on adding this to the html reporter.

Yes do!

**Comment by oveddan** [comment] 2015-10-20 13:43
Ok, I'll work on it!

**Comment by ponelat** [comment] 2015-10-20 16:35
+1

**Comment by tnrich** [comment] 2015-10-26 06:05
+1 Any workaround for this currently?

**Comment by ponelat** [comment] 2015-10-26 07:49
I'm using [modern-diff](https://github.com/zerkalica/modern-diff) to generate little diffs that look like...
```js
dif({a: 1, b: 2, c: 3}, {b: 22, c: 3, d: 4})
/*
[
  ['-', ['a'], 1],
  ['r', ['b'], 2, 22],
  ['+', ['d'], 4]
]
*/
```

and my own little chai.expect helper for the error message.
Perhaps it'll help you in the mean-time :smile:

**Comment by keithamus** [comment] 2015-10-26 10:05
In the meantime - if you're using chai - you can set `chai.config.truncateThreshold = 0` which disables chai's inspector truncating objects for the error messages. Be warned: this is not a diff, it just shows you every property on an object and so can be pretty messy.

**Comment by impinball** [comment] 2015-10-30 23:00
I'm running into the same problem.

**Comment by boneskull** [comment] 2015-10-31 04:52
Diffing has been an issue for a long time.  I would like to leverage a third-party lib (or libs) for this.

Requirements:

1.  colors; console and CSS (could necessitate some ansi-to-css converter)
2.  human-readable output
3.  type-based: intuitive diffs for numbers, strings, objects, functions, `Date`s, `Buffer`s.
4.  proper handling of strict equality comparisons (though that may be something we would still need to implement); if two objects are otherwise equivalent but are different objects, this should be apparent.

nice to have:
1.  option for machine-readable output (which it looks like **modern-diff** is doing)
2.  option for GNU `diff`-style output.

I'm welcome to suggestions for modules that would fulfill the requirements.  If nothing exists, maybe we should write one with Mocha in mind?

**Comment by impinball** [comment] 2015-11-01 06:45
@boneskull [Multiple things on npm that might catch your eye](https://www.npmjs.com/search?q=object+diff). They simply create a machine-readable diff, which walking the two objects to format it wouldn't be that hard to do (although not quite trivial).

**Comment by lydell** [comment] 2015-11-01 07:08
[unexpected. js](https://github.com/unexpectedjs/unexpected) has really nice strimg and object diffs. Don't know how that's implemented, though. Hopefully in a modular way :)

**Comment by oveddan** [comment] 2015-11-14 03:19
@boneskull there are currently no tests on the html reporter.  Thinking of adding some.  Would you be ok with jsdom being added to the dev dependencies for use in testing the generated html?

**Comment by amir-arad** [comment] 2016-03-07 11:05
:+1:

**Comment by HamsterCoder** [comment] 2016-03-14 15:01
I came from this [issue](https://github.com/karma-runner/karma-mocha/issues/76) and it's title describes precisely my problem. Using karma/mocha/chai with deepEqual I get the following output in console:

`✖ supports predefined proxy
        PhantomJS 2.1.1 (Linux 0.0.0)
      expected { Object (url, headers, ...) } to deeply equal { Object (url, headers, ...) }`

**Comment by valentin-radulescu-hs** [comment] 2016-11-08 13:42
👍

**Comment by boneskull** [comment] 2017-10-18 03:50
actually I'm going to kill this because it's not really actionable aside from the continuing lack of tests of the html reporter.  if we want better / different diffs, someone should propose something concrete.

**Closed by boneskull** 2017-10-18 03:50 UTC
Labels: browser, feature, help-wanted, reporter

**Comment by rugk** [comment] 2018-08-10 21:35
Here is "something concrete":

Do make this:
![](https://cloud.githubusercontent.com/assets/485061/5648442/4025eafa-9697-11e4-99fd-70c6c3416130.png)

looks this:

![](https://cloud.githubusercontent.com/assets/812240/5680198/d46e809e-981a-11e4-9f78-cb8ce368aafd.png) 

In the browser too. Not only in the console.

How can one be more concrete? It's a missing feature, it's very obvious what "concrete thing" is requested here.

---

Also I'd say this is **the biggest** feature Mocha is missing. Not being able to render diffs is a major drawback!

And don't know what you mean by "continuing lack of tests of the html reporter". All reports of this issue likely will test the HTML reporter. And if you don't want to maintain it, remove it, but do not pretend to support it.

**Comment by boneskull** [comment] 2018-08-10 22:02
This is what I mean:

1. The HTML reporter has no code coverage
2. There have been a couple abortive attempts to do it with our existing testing environment, but we really need functional, Selenium-style tests
3. Functional tests will require a new toolchain to script a browser
4. We won't change the HTML reporter until we have coverage
5. We won't be removing the HTML reporter 😄 

"Concrete" refers to the diff implementation itself, which likely won't transfer cleanly from the console to the browser.  I was hoping for "let's use *module X*, because it fulfills all of the requirements," or a proposal to create a module which does.

@rugk It's clear you're frustrated by this missing feature.  But please take care not to make condescending comments or place demands on volunteer contributors to this project.

**Comment by rugk** [comment] 2018-08-11 09:16
> We won't be removing the HTML reporter smile

Great to hear, but then you may need to add these stuff still missing in that reporter.

>  I was hoping for "let's use module X, because it fulfills all of the requirements," or a proposal to create a module which does.

We don't even have a list of requirements, but aside from [this lib](https://github.com/zerkalica/modern-diff), which already has been mentioned, but does not provide HTML support as it seems, there are a lot libraries:
* https://github.com/prettydiff/prettydiff/
* [this](https://diff2html.xyz/demo?diff=https://github.com/rtfpessoa/diff2html/pull/106), whcih demo looks great
* [this seems to be low level](https://github.com/kpdecker/jsdiff)

I'd say diff2html looks promising and up-to-date (it's also [easily to embed in a browser](https://github.com/rtfpessoa/diff2html#browser-library)), but generally one may also have a look at what GitLab/GitHub/etc. use. They all have this implemented.

---

@boneskull It's clear you see some missing other stuff about the reporter and more important6 things to do. However, please acknowledge this issue here is valid and unsolved, and as such re-open it. I see no reason why it should be closed. You may mark it as "blocked" indicating no one should/can work on this, but acknowledge the general idea that this is missing.
Then, https://github.com/mochajs/mocha/issues/3071 is the issue this is blocking, is it?
But actually a PR is already open in https://github.com/mochajs/mocha/pull/3102.

**Comment by brian-lagerman** [comment] 2019-05-10 14:34
> I'd say diff2html looks promising

A little bit of a sidebar as it's not the default html reporter, but we just pushed out a [beta](https://netpoint-gmbh.github.io/mochaterial/dark.html) of our new mocha [reporter](https://www.netpoint.de/en/competence/mochaterial/) and we integrated diff2html into it. We tore diff2html apart a bit, so that area still needs some clean up, but I'd be interested in what people think. The 'Diff comparison' suite has a couple samples in it.

**Comment by brucou** [comment] 2021-06-13 00:14
Any news on this? This is closed, but it is still a very valuable feature.

**Comment by nicbou** [comment] 2022-01-21 13:31
@boneskull, why close this issue? The requirements are fairly clear, fairly popular (see multiple related tickets linked here), and certainly not met. 7 years later people are still coming here to request it.

**Comment by brucou** [comment] 2022-01-21 13:33
true story

**Comment by cesarvarela** [comment] 2022-06-26 04:23
![image](https://user-images.githubusercontent.com/1172479/175793706-0ce3ec22-d3c8-4c1e-b23f-a9cd59afdaf2.png)

(If someone comes here from Cypress,  try using `nested.include` instead. It tells you the property that's different, and after that you can change it back to `deep.equal`)
