### ISSUE TITLE
ERR_REQUIRE_ESM When using ESM with `--watch`

### ISSUE THREAD

**Issue by ChocolateLoverRaj** [mochajs/mocha#4854] opened 2022-03-19 00:13 UTC
### Prerequisites

- [x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend that you _not_ install Mocha globally.

### Description
`mocha` works when using ESM. `mocha -w` doesn't.

### Steps to Reproduce
https://replit.com/@Programmerraj/mocha-bug#package.json
- `type` is `module` in `package.json`
- run `mocha -w`

**Expected behavior:** Watch mode works, like with commonjs

**Actual behavior:** 

Log:
```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /home/runner/mocha-bug/test/index.js
require() of ES modules is not supported.
require() of /home/runner/mocha-bug/test/index.js from /home/runner/mocha-bug/node_modules/mocha/lib/mocha.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /home/runner/mocha-bug/package.json.

    at new NodeError (internal/errors.js:322:7)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1102:13)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at /home/runner/mocha-bug/node_modules/mocha/lib/mocha.js:417:36
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/home/runner/mocha-bug/node_modules/mocha/lib/mocha.js:414:14)
    at Mocha.run (/home/runner/mocha-bug/node_modules/mocha/lib/mocha.js:1015:10)
    at Object.run (/home/runner/mocha-bug/node_modules/mocha/lib/cli/watch-run.js:263:22)
    at FSWatcher.<anonymous> (/home/runner/mocha-bug/node_modules/mocha/lib/cli/watch-run.js:184:14)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
yarn test
```

**Reproduces how often:** 1 (Every time)

### Versions

- The output of `mocha --version` and `node_modules/.bin/mocha --version`: `9.2.2`
- The output of `node --version`: `v16.13.2`
- Your operating system
  - name and version: Repl.it, but I think it's not specific to Linux
  - architecture (32 or 64-bit): Repl.it, but I think it's not specific to Linux
- Your shell (e.g., bash, zsh, PowerShell, cmd): bash?
- <s>Your browser and version (if running browser tests):</s>
- Any third-party Mocha-related modules (and their versions):
- Any code transpiler (e.g., TypeScript, CoffeeScript, Babel) being used (and its version):

**Comment by juergba** [comment] 2022-03-19 04:46
duplicate of #4831

**Closed by juergba** 2022-03-19 04:46 UTC
Labels: unconfirmed-bug
