### ISSUE TITLE
Sharing of context between nested describe blocks

### ISSUE THREAD

**Issue by nene** [mochajs/mocha#3162] opened 2017-12-15 14:06 UTC
### Prerequisites
* [x] Checked that your issue isn't already filed by cross referencing [issues with the `common mistake` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Acommon-mistake%20)
* [x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
* [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
* [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with:
`node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend avoiding the use of globally installed Mocha.

### Description

When function `getFoo` is bound to `this` at top-level `beforeEach()` and I set `this.foo` property inside a nested `beforeEach()` block, that `getFoo` function cannot access this property.

As demonstrated by the code below:

```js
const {expect} = require("chai");

beforeEach(function() {
    this.getFoo = () => this.foo;
});

describe("when this.foo set", function() {
    beforeEach(function() {
        this.foo = true;
    });

    it("getFoo() returns value of foo", function() {
        expect(this.getFoo()).to.equal(true); // FAILS!
    });
});
```

When I remove the `describe()`, the tests will pass.

Is this the intended behavior of Mocha?

I'm trying to migrate my tests over from Jasmine, where the equivalent code works without any problems.

### Versions

* Mocha 4.0.1
* Node 6.1.1
* Mac OS 10.13.2
* Shell: Bash
* Installing and running through: Yarn
* Additional tools: Chai

**Comment by boneskull** [comment] 2017-12-15 22:04
duplicate of #2914

**Comment by boneskull** [comment] 2017-12-15 22:05
or #2014

**Closed by boneskull** 2017-12-15 22:04 UTC

**Comment by nene** [comment] 2017-12-15 22:33
I take it to mean: it's part of a larger group of problems with context in Mocha.
