### ISSUE TITLE
Test fails and passes at the same time....

### ISSUE THREAD

**Issue by alfonso-presa** [mochajs/mocha#3309] opened 2018-04-04 14:35 UTC
### Description

Given an async test, if an unhandled exception is produced and the done callback is invoked, the test passes and fails at the same time (it counts both as failed and as passed)

### Steps to Reproduce

Given the following test code:

```js
describe('strange thing', function() {
    it('fails and passes at the same time.... WTF!', function(done) {
        setTimeout(() => { throw new Error(); });
        setTimeout(done);
    });
});
```

**Expected behavior:**

It should notify the test as failed but not as passed.

**Actual behavior:**

The reporter says the following:

```
strange thing
    1) fails and passes at the same time.... WTF!
    ✓ fails and passes at the same time.... WTF!


  1 passing (7ms)
  1 failing

  1) strange thing
       fails and passes at the same time.... WTF!:
     Uncaught 
  Error
      at Timeout.setTimeout [as _onTimeout] (lib/test.spec.js:3:34)
```

**Reproduces how often:**

100%

### Versions

Mocha: 5.0.1
Node: 8.9.4
Linux Mint x64. Kernel: 4.4.0-116-generic
zsh

**Comment by boneskull** [comment] 2018-04-07 17:11
duplicate of #3223

**Closed by boneskull** 2018-04-07 17:11 UTC
