### ISSUE TITLE
🐛 Bug: structuredClone is not defined in Node <17

### ISSUE THREAD

**Issue by danielbayley80** [mochajs/mocha#4897] opened 2022-06-29 12:27 UTC
I wasn't sure if this was a bug and as something of a noob I thought I would raise it here. Please move as you see fit.
I previously logged on stackoverflow but haven't had any response yet.
I have googled this and I can not see anything for mocha but saw a similar bug for jest.

I recently started using structuredClone which has been a feature of node since version 17 I think.
I'm using version 18 with VS code and typescript.
Previously my tests worked fine.

My code itself runs fine, but my tests fail when they hit structuredClone method. 
Mocha outputs "ReferenceError: structuredClone is not defined".

![image](https://user-images.githubusercontent.com/1572154/176435217-4e15e5a1-d6e3-4500-b04d-8cfd53169839.png)

![image](https://user-images.githubusercontent.com/1572154/176435515-154feaba-eea1-4b4a-ba03-a908b1da5e11.png)

```
      "dependencies": {
            "bcrypt": "^5.0.1",
            "body-parser": "^1.19.2",
            "connect-flash": "^0.1.1",
            "cookie-parser": "^1.4.6",
            "dotenv": "^16.0.0",
            "eventemitter2": "^6.4.5",
            "express": "^4.17.3",
            "express-validator": "^6.14.0",
            "jsdom": "^20.0.0",
            "jsonwebtoken": "^8.5.1",
            "marked": "^4.0.12",
            "memory-cache": "^0.2.0",
            "mssql": "^8.0.2",
            "sanitize-html": "^2.7.0",
            "validator": "^13.7.0",
            "xsg.spider": "file:./../spider"
      },
      "devDependencies": {
            "@sendgrid/mail": "^7.6.2",
            "@types/bcrypt": "^5.0.0",
            "@types/chai": "^4.3.1",
            "@types/connect-flash": "^0.0.37",
            "@types/cookie-parser": "^1.4.2",
            "@types/dompurify": "^2.3.3",
            "@types/express": "^4.17.13",
            "@types/jsdom": "^16.2.14",
            "@types/jsonwebtoken": "^8.5.8",
            "@types/marked": "^4.0.3",
            "@types/memory-cache": "^0.2.2",
            "@types/mocha": "^9.1.1",
            "@types/mssql": "^7.1.5",
            "@types/node": "^18.0.0",
            "@types/npm": "^7.19.0",
            "@types/passport-local": "^1.0.34",
            "@types/sanitize-html": "^2.6.2",
            "@types/validator": "^13.7.2",
            "chai": "^4.3.6",
            "mocha": "^10.0.0",
            "nyc": "^15.1.0",
            "ts-node": "^10.8.1",
            "typescript": "^4.6.4"
      }
```

**Comment by JoshuaKGoldberg** [comment] 2023-12-27 06:24
> I recently started using structuredClone which has been a feature of node since version 17 I think.

This information is discoverable 🙂. https://caniuse.com/?search=structuredClone indicates it's been available since Node 17 

> I'm using version 18 with VS code and typescript.
> ...
> Mocha outputs "ReferenceError: structuredClone is not defined".

Either your code is somehow deleting the global `structuredClone` value (?!)... or you're not on Node 18 😉.

**Comment by JoshuaKGoldberg** [comment] 2023-12-27 06:36
Oh! Bug, Mocha is supposed to support Nodejs v14.0.0 or newer. So until support for Node <18 is dropped, this actually is a bug.

A userland workaround is to use an LTS supported version of Node.

**Comment by JoshuaKGoldberg** [comment] 2024-01-15 07:18
Hmm. There is no `structuredClone` in Mocha's source. I'm betting this is an issue either with your own source code or a dependency other than Mocha. If the issue is with a dependency other than Mocha, you'll want to file an issue over there. Closing this as not an issue in Mocha. Cheers!

**Closed by JoshuaKGoldberg** 2024-01-15 07:18 UTC
Labels: unconfirmed-bug

**Comment by voxpelli** [comment] 2024-01-15 08:51
To verify which version of Node.js that's actually run you can use eg [`console.log(process.version)`](https://nodejs.org/api/process.html#processversion)
