### ISSUE TITLE
In-page (HTML reporter) UX issues

### ISSUE THREAD

**Issue by ScottFreeCode** [mochajs/mocha#2202] opened 2016-04-11 23:50 UTC
[EDITTED to update some of these.] There are points on which the HTML reporter could use a little more TLC and polish:
- The "100%" in the upper-right is unlabelled; there should be some indication of what it's a percent of. Coverage? Tests run so far as a long testsuite runs (this would be self-evident while long test-suites are running, but not once they're done and especially not in short test-suites that are done almost immediately)? Tests run vs. pending tests/suites?
- There's an unobvious difference between clicking suite/context names to grep and clicking tests to show their code. How would a user who has tried one know that something different would happen if (s)he were to do the other?
- The triangle for grepping is highlighted when a test's name is hovered even though clicking then will not grep.
- The test names that can be clicked on to show their code are the only thing that doesn't give a visual indication of clickability other than the cursor. Since so many other things can be clicked on, it's easy to overlook the cursor indication. Since the triangle for grepping on the other side of the page is highlighted when the test name is hovered, attention is actually drawn away from the test name where one would click to see the source code.
- The triangles for grepping are far from the names with which they're associated and there's just blank space in between. This makes them both initially easy to miss and then hard to tell which lines up with what, except for the way they highlight when the name on the other end of the page is hovered, which is a difficult way to tell (have to keep the mouse on one end of the page while looking at the other for indications) -- and as already discussed causes other usability issues by making them less easy to miss in cases where they actually shouldn't be drawing attention.
- [EDIT: Technically, clicking on the suite links doesn't indicate that they'll grep either... except for the URL in the browser status bar, which the triangles have too.] The triangles don't really indicate what they're for before you click on them and get the grepping action. The only relationship I can think of between the grepping and a triangle even knowing what they do is that it's meant to be an arrow for navigating into a structure; but since the stuff inside was already visible before the grepping, I don't think that really applies -- the triangle/arrow somehow means "stop seeing other things" more than "go into this thing"... Granted it can be used with the same suite/context structure split across multiple files, in which case the matter of already having had the contents visible isn't applicable, but then similarly named structures from elsewhere are being pulled in so the notion of navigating into the structure that was clicked on doesn't fit well in that case either. [EDIT: I am no longer sure what I was talking about in the immediately preceding sentence!] (Plus -- although this is significantly more subjective than the rest of these points, there are lots of things that have more than one meaning in different backgrounds or contexts, but for what it's worth -- I've seen user-interfaces before where a triangle is used to indicate unfolding a hidden set of content, where the triangle rotates or flips as the content is pulled out or re-hidden, so my instinct is that triangles should be associated with showing the code. [EDIT: maybe if they pointed down instead of to the side. See [comment](#issuecomment-308290150).])
- ~When grepping on a test by clicking the triangles, the test code is revealed briefly before the navigation to the grepped page, making it harder to figure out which of those two things is supposed to be performed by what method.~ [EDIT: I can no longer reproduce this; it might have been specific to a certain browser, but... I am guessing it has been fixed!]
- The usefulness of grepping to a specific test in a specific suite structure is dubious altogether (unlike grepping to a suite/context, since a suite/context might be split across multiple test files); grepping to see all tests with the same name/description in a variety of suites might be handy instead, however. (Something similar may go for a sub-context within another context/suite, e.g. show the "#slice" suites on both String and Array.)

**Comment by mderijcke** [comment] 2016-04-22 12:28
I can tell you already that 100% is going to be amount of tests passed, because Mocha does not know anything about coverage. Only externals tools which invoke Mocha do.

**Comment by ScottFreeCode** [comment] 2016-05-10 02:04
Remind me to review these against the next release; I know at least some of them have been fixed in master.

**Comment by drazisil** [comment] 2017-03-30 16:26
@ScottFreeCode Consider this your reminder? :)

**Comment by ScottFreeCode** [comment] 2017-06-14 01:03
A lot of these could be fixed by a scheme along the lines of the following:
- Clicking the name greps no matter whether it's a suite or a test. Test grep links look just like suite grep links. Also consider adding a description at the top like "(Click on a name to filter.)". This would clarify most of the issues surrounding behavior of grep links and clickability.
- To show the test source code, have an arrow or triangle pointing *down* on the *left* side of the name/page rather than the right side. This would be more obvious in terms of the meaning of the triangle/arrow (as per my original comments about triangles being more commonly used for a reveal/unhide action) *and* make it easier to match up the buttons to the tests.

**Comment by JoshuaKGoldberg** [comment] 2023-12-27 21:44
This issue has a lot of good points in it but hasn't had much user involvement in 2017. Plus this:

> Remind me to review these against the next release; I know at least some of them have been fixed in master.

Closing now as duplicate of ... whatever got fixed. I'm sure there are other points we'll end up wanting to fix. If you're interested, please file a new issue per each improvement to make. Cheers!

**Closed by JoshuaKGoldberg** 2023-12-27 21:44 UTC
Labels: area: browser, area: reporters
