### ISSUE TITLE
HTML-Reporter filters does not unhide all hidden suites

### ISSUE THREAD

**Issue by HeilTec** [mochajs/mocha#3110] opened 2017-11-17 15:04 UTC
### Prerequisites

* [x] Checked that your issue isn't already filed by cross referencing [issues with the `common mistake` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Acommon-mistake%20)
* [x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
* [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
* [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with:
`node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend avoiding the use of globally installed Mocha.

### Description

HTML-Reporter filters does not unhide all hidden suites
### Steps to Reproduce
Run tests using the html reporter - click on the passes / failures filters

**Expected behavior:** [What you expect to happen]
When clicking on a filter twice all suites should be visible

**Actual behavior:** [What actually happens]
Only the odd numbered of the hidden reappears

**Reproduces how often:** [What percentage of the time does it reproduce?]
100% It happens every time

### Additional Information

While working on making a html-electron reporter I noticed this issue.
The function [unhide()](https://github.com/mochajs/mocha/blob/master/lib/reporters/html.js#L318) only un-hides the odd numbered hidden suites.

The problem is the mutation of the html collection as the parameters used for selecting the elements are removed from said elements.
This is the working solution I arrived at.

``` javascript

/**
 * Unhide .hidden suites.
 */
function unhide () {
  var els = document.getElementsByClassName('suite hidden');
  // as the search criterion is changed the elements are removed from the collection
  while (els[0]) { 
    els[0].className = els[0].className.replace('suite hidden', 'suite');
  }

// *** This only removes the odd numbered ***

  // for (var i = 0; i < els.length; ++i) {
  //   els[i].className = els[i].className.replace('suite hidden', 'suite');
  // }
}



```

**Comment by HeilTec** [comment] 2017-11-17 17:21
If the above code smell is offending and appropriate transpiler is used for compatibility I like the functional approach:

``` javascript
function unhide () {
  var els = document.getElementsByClassName('suite hidden');

  [].reduce.call(els, (acc, el) => acc.concat([el]), [])
  .forEach(el => el.className = el.className.replace('suite hidden', 'suite'));
}
```

**Comment by ScottFreeCode** [comment] 2017-11-19 19:55
Closing as a duplicate of #2893, but if I've misunderstood and this is a different issue please let me know.

**Closed by ScottFreeCode** 2017-11-19 19:55 UTC
