### ISSUE TITLE
structuredClone is not defined

### ISSUE THREAD

**Issue by kylefran-thryv** [mochajs/mocha#5010] opened 2023-09-07 21:35 UTC
### Basic info:
Node.js version: 18.0.0
mocha version: 10.0.0

### Minimal reproduction case
Running a mocha test that calls the structuredClone global

`structuredClone()`

structuredClone was introduced in node 17+

**Comment by JoshuaKGoldberg** [comment] 2023-12-27 06:35
Duplicate of #4897.

**Closed by JoshuaKGoldberg** 2023-12-27 06:35 UTC
Labels: unconfirmed-bug
