### ISSUE TITLE
Setting message (reason) for test skip

### ISSUE THREAD

**Issue by ponmudivn** [mochajs/mocha#2572] opened 2016-11-03 08:42 UTC
Is it possible to set a message (mentioning reason) why a particular test is skipped, so that it could be used in reporters.

```
describe('xxx', function() {
 checkToSkip(1)("test1", function() {\*test goes here*\});
 checkToSkip(4)("test2", function() {\*test goes here*\});
});

function checkToSkip(now) {
    return now > 3 ? it : xit; 
   //return now > 3 ? it : it.skip; 
}
```

Here 'test1' will be skipped as 'checkToSkip' returns 'xit' (or it.skip). Is it possible to pass a message to reporter mentioning the reason for the test skip? something like below (or any other possible way).

`checkToSkip(4)("test2", function() { \\ test goes here}, "My Skip message!!!!" );`

or 

`checkToSkip(4)("test2", function() { \\ test goes here}).pending("My Skip message!!!!");`

Note: Im using mocha in webdriverIO.

Thanks.

**Comment by ponmudivn** [comment] 2016-11-03 09:20
http://stackoverflow.com/questions/31688650/is-it-possible-to-send-a-reason-for-jasmine-2-specs-skipped-with-xit-or-pending

This thread explains the solution for same problem using Jasmine. Im looking for something similar in Mocha.

**Comment by vivganes** [comment] 2016-11-04 13:24
I too would love to have something like that.

I could not find any inputs about how to enter reason for skipping in documentation [here](http://unitjs.com/guide/mocha.html#ignore-suite-s-or-test-case-s-)

May be a candidate for a feature request?  It could just be a case that the documentation is missing while feature is there.

**Comment by ponmudivn** [comment] 2016-11-08 09:28
http://stackoverflow.com/questions/40397201/mocha-setting-message-reason-for-test-skip/40407177#40407177

fyi: a workaround to achieve this is available in the above thread.

**Comment by boneskull** [comment] 2016-11-17 02:31
this would be a good usability improvement, but see @ponmudivn's [workaround](https://github.com/mochajs/mocha/issues/2572#issuecomment-259087379)

**Comment by jeffvandyke** [comment] 2017-12-15 21:56
One approach that could cover all use cases and would only be a small api change would be to allow an optional `reason` parameter to `this.skip()`. The `it.skip(...)` case could be satisfied by just calling `this.skip("reason")` in the first line of the test.

**Comment by monkey-programmer** [comment] 2018-02-19 14:16
Agreed with @jeffvandyke I would love to have this feature

**Comment by Nokel81** [comment] 2018-04-11 13:37
How about doing:

```js
    it.skip("A test").reason("Code has changed");
```

But that doesn't allow for using the `this.skip` api, so maybe it can also accept a second or third string parameter as the reason as well. But that just seems weird in my opinion.

**Comment by boneskull** [comment] 2018-04-18 18:16
duplicate of #2026

**Closed by boneskull** 2018-04-18 18:16 UTC
Labels: feature, usability
