### ISSUE TITLE
🐛 Bug: Test file name getting passed to interface/bdd does not change

### ISSUE THREAD

**Issue by nirvanagit** [mochajs/mocha#1251] opened 2014-06-25 15:37 UTC
I am running mocha with protractor. It is being used as a library. In interfaces/bdd the file parameter which is getting passed is not getting reflected in the 
`context.it = context.specify = function(title, fn){` even after the test has completed.

e.g. Test files : A and B.
When I run mocha, it takes the file name of A and passes to the reporter. But when the test of A finishes the test file name still points to 'A'.

I understand that `context.it` is called for every it encountered. But when A finishes context.it still contains the file name of 'A'. 

To duplicate the issue, please use protractor and put shardTestFile to false. And console.log the file name in the interface/bdd file at two places. Once when listener is activated and second inside context.it function

**Comment by scott2449** [comment] 2015-04-05 02:06
@boneskull been suffering from this one myself for almost a year now and never had the time to look. I'll do you one better than reproducing, these commits here (that "introduce" the feature):

https://github.com/mochajs/mocha/commit/55f01bcb3713cc26294d07b610bd079c232f4404
https://github.com/mochajs/mocha/commit/3dd1cdbb695f0489e03171c0874f4ccfb7347893

never worked. When pre-require is triggered the context is *global*. This means that all the tests/suites of an interface run only the last version of the function (and importantly they all have it's scope). In other words context.describe keeps getting overwritten. Functionally not a problem because those methods just pull the next describe off the stack, with the exception of file name. All the tests/describe just get the file name of the last file from load Files. Make sense?

This assignment would need to exist somewhere else entirely I think.

**Comment by boneskull** [comment] 2015-04-05 09:07
@scott2449 tyvm

**Comment by JoshuaKGoldberg** [comment] 2023-12-27 05:53
This has been open & accepting PRs since 2015. Only two accounts have interacted other than maintainers and bots. Protractor hasn't been updated in 3 years. I'm going to go ahead and close this as a wontfix. Please let me know if this actually should be fixed!

...and if you do, please post a standalone isolated reproduction. None of us use Protractor regularly. 😄

**Closed by JoshuaKGoldberg** 2023-12-27 05:53 UTC
Labels: type: bug, status: accepting prs
