### ISSUE TITLE
🐛 Bug: Setting readOnly properties in `breakCircularDeps` breaks the reporter in `parallel` mode with `allow-uncaught`

### ISSUE THREAD

**Issue by satyen95** [mochajs/mocha#5188] opened 2024-08-06 10:19 UTC
### Bug Report Checklist

- [X] I have read and agree to Mocha's [Code of Conduct](https://github.com/mochajs/mocha/blob/main/.github/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/mochajs/mocha/blob/main/.github/CONTRIBUTING.md)
- [X] I have searched for [related issues](https://github.com/mochajs/mocha/issues?q=is%3Aissue) and [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20), but none matched my issue.
- [X] I have 'smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, my usage of Mocha, or Mocha itself.
- [ ] I want to provide a PR to resolve this

### Expected

Tests should run perfectly even if a `it` block (test) is failing
Error in it block (test) should not break `parallel-buffered-runner.js` even if `--allow-uncaught` is passed

### Actual

All the tests get executed in the expected behaviour, but before the EVENT_RUN_END the process fails while serializing the results with the below error:

```
/XXX/node_modules/mocha/lib/nodejs/parallel-buffered-runner.js:357
          throw err;
          
TypeError: Cannot set property maxHeaderSize of #<Object> which has only a getter
    at _breakCircularDeps (/XXX/node_modules/mocha/lib/utils.js:679:16)
    at _breakCircularDeps (/XXXnode_modules/mocha/lib/utils.js:679:18)
    at _breakCircularDeps (/XXX/node_modules/mocha/lib/utils.js:679:18)
    at _breakCircularDeps (/XXX/node_modules/mocha/lib/utils.js:679:18)
    at _breakCircularDeps (/XXX/node_modules/mocha/lib/utils.js:679:18)
    at _breakCircularDeps (/XXX/node_modules/mocha/lib/utils.js:679:18)
    at _breakCircularDeps (/XXX/node_modules/mocha/lib/utils.js:679:18)
    at _breakCircularDeps (/XXX/node_modules/mocha/lib/utils.js:679:18)
    at _breakCircularDeps (/XXX/node_modules/mocha/lib/utils.js:679:18)
    at _breakCircularDeps (/XXX/node_modules/mocha/lib/utils.js:679:18)
```
    
Failure point:
<img width="596" alt="Screenshot 2024-08-06 at 3 43 31 PM" src="https://github.com/user-attachments/assets/c537f4cf-e898-47a1-85cb-53fe30ec7b6c">
Reason: Trying to set a read-only property, which only has a getter 

### Minimal, Reproducible Example

Config:
- allow-uncaught: true
- parallel: true

Library dependency (easy to reproduce):
axios: 1.6.8

Create a suite, create a test in it, and make an incorrect/failing API call

Run the tests it will break

### Versions

Mocha version: 10.7.0
Node: v20.15.1
OS: MacOS Sonoma 14.2.1 (23C71)

**Comment by voxpelli** [comment] 2024-08-06 13:09
This is a regression caused by #5032

**Comment by JoshuaKGoldberg** [comment] 2024-08-06 16:19
Could someone please post a full reproduction we can work with locally?

We _might_ have just fixed this with #5173 (to be released in a patch version soon). But it's hard to be sure we're doing the same steps as you without an actual reproduction.

https://antfu.me/posts/why-reproductions-are-required

**Comment by JoshuaKGoldberg** [comment] 2024-08-06 16:19
Could someone (@satyen95?) please post a full reproduction we can work with locally?

We _might_ have just fixed this with #5173 (to be released in a patch version soon). But it's hard to be sure we're doing the same steps as you without an actual reproduction.

https://antfu.me/posts/why-reproductions-are-required

**Comment by satyen95** [comment] 2024-08-07 06:26
@JoshuaKGoldberg You can reproduce the issue via this zip, I have added the code for it

[mocha-5188.zip](https://github.com/user-attachments/files/16519100/mocha-5188.zip)

**Comment by satyen95** [comment] 2024-08-07 06:53
@JoshuaKGoldberg 
Also, I have a question what is the exact behaviour of `allow-uncaught` will it stop due `expect` failures too (inside `it` block)?
 
Because the behaviour of it is correct in my main project, Run only fails/breaks when the worker processes close due to failure at setup time & not due to any failures in `it` block. That's the only reason why I have used `allow-uncaught`.

But the behaviour is different in the given example, run is stopped even due to failure in `it` block

**Comment by JoshuaKGoldberg** [comment] 2024-10-08 17:45
> [@JoshuaKGoldberg](https://github.com/JoshuaKGoldberg) You can reproduce the issue via this zip, I have added the code for it
> 
> [mocha-5188.zip](https://github.com/user-attachments/files/16519100/mocha-5188.zip)

Great, thanks! I can reproduce the bug with that zip in its included Mocha version, 10.7.0. 

Aside, a tip: it's a little better practice to put the reproduction up on somewhere I can see it before unzipping potentially unsafe files to a file system 😄. I personally keep a https://github.com/JoshuaKGoldberg/repros repository; other folks make repositories per-issue or use something like [GitHub Gists](https://gist.github.com) or [Stackblitz](https://stackblitz.com).


> [@JoshuaKGoldberg](https://github.com/JoshuaKGoldberg) Also, I have a question what is the exact behaviour of `allow-uncaught` will it stop due `expect` failures too (inside `it` block)?
> 
> Because the behaviour of it is correct in my main project, Run only fails/breaks when the worker processes close due to failure at setup time & not due to any failures in `it` block. That's the only reason why I have used `allow-uncaught`.
> 
> But the behaviour is different in the given example, run is stopped even due to failure in `it` block

Sorry, I don't understand what you're asking. The grammar is broken and I don't follow what you're trying to ask. Can you rephrase please?

---

Anyway, the .zip has `mocha@10.7.0` and the crash as described. Trimming some blank lines:

```plaintext
$ npm run test

> mocha-5188@1.0.0 test
> mocha


before

  Test here should pass
    ✔ 1 to be equal to 1

before

  1) Uncaught error outside test suite

  1 passing (411ms)
  1 failing

  1) Uncaught error outside test suite:
     Uncaught TypeError: Cannot set property maxHeaderSize of #<Object> which has only a getter


[mochawesome] Report JSON saved to /Users/josh/repos/mocha-5188/mochawesome-report/mochawesome.json

[mochawesome] Report HTML saved to /Users/josh/repos/mocha-5188/mochawesome-report/mochawesome.html
```

Bumping to `mocha@10.7.3` has it hang indefinitely:

```plaintext
 $ npm i mocha@10.7.3 -D; npm run test

changed 1 package, and audited 117 packages in 783ms

...

> mocha-5188@1.0.0 test
> mocha


before

  Test here should pass
    ✔ 1 to be equal to 1

before
```

💡 That's the same behavior as #5209! And, in fact, applying the changes in #5212 to `node_modules/mocha` fixes the indefinite hanging on my computer... only to get back to the original bug:

```plaintext

  1) Uncaught error outside test suite:
     Uncaught TypeError: Cannot set property maxHeaderSize of #<Object> which has only a getter
      at Array.forEach (<anonymous>)
```

Running with `DEBUG=mocha:runner npm run test` shows:

```plaintext
  mocha:runner uncaught(): got truthy exception TypeError: Cannot set property maxHeaderSize of #<Object> which has only a getter
  mocha:runner     at _breakCircularDeps (/Users/josh/repos/mocha-5188/node_modules/mocha/lib/utils.js:679:16)
  mocha:runner     at _breakCircularDeps (/Users/josh/repos/mocha-5188/node_modules/mocha/lib/utils.js:679:18)
  mocha:runner     at _breakCircularDeps (/Users/josh/repos/mocha-5188/node_modules/mocha/lib/utils.js:679:18)
  mocha:runner     at _breakCircularDeps (/Users/josh/repos/mocha-5188/node_modules/mocha/lib/utils.js:679:18)
  mocha:runner     at _breakCircularDeps (/Users/josh/repos/mocha-5188/node_modules/mocha/lib/utils.js:679:18)
  mocha:runner     at _breakCircularDeps (/Users/josh/repos/mocha-5188/node_modules/mocha/lib/utils.js:679:18)
  mocha:runner     at exports.breakCircularDeps (/Users/josh/repos/mocha-5188/node_modules/mocha/lib/utils.js:688:10)
  mocha:runner     at SerializableEvent.serialize (/Users/josh/repos/mocha-5188/node_modules/mocha/lib/nodejs/serializer.js:262:5)
  mocha:runner     at /Users/josh/repos/mocha-5188/node_modules/mocha/lib/nodejs/serializer.js:72:13
  mocha:runner     at Array.forEach (<anonymous>)
  mocha:runner     at SerializableWorkerResult.serialize (/Users/josh/repos/mocha-5188/node_modules/mocha/lib/nodejs/serializer.js:71:17)
  mocha:runner     at serialize (/Users/josh/repos/mocha-5188/node_modules/mocha/lib/nodejs/serializer.js:374:15)
  mocha:runner     at /Users/josh/repos/mocha-5188/node_modules/mocha/lib/nodejs/worker.js:127:28
  mocha:runner     at ParallelBuffered.done (/Users/josh/repos/mocha-5188/node_modules/mocha/lib/nodejs/reporters/parallel-buffered.js:151:5)
  mocha:runner     at done (/Users/josh/repos/mocha-5188/node_modules/mocha/lib/mocha.js:1026:16) +417ms
```

**Comment by JoshuaKGoldberg** [comment] 2024-10-08 18:07
I updated #5212 to also handle this case. https://github.com/mochajs/mocha/pull/5212/commits/853dc9a8a1800d71abb45fc46fa09747b19bc472

**Closed** 2024-10-29 20:38 UTC
Labels: type: bug, status: accepting prs
