### ISSUE TITLE
Add more emphasis on failed tests in the browser reporter

### ISSUE THREAD

**Issue by emilecantin** [mochajs/mocha#450] opened 2012-06-05 14:10 UTC
I think it would be a good idea to emphasize a bit more when there are failed tests in the browser reporter. I am starting to have a sizeable test suite, and I always need to scroll to see if there are any failed tests. (I know I should look at the counter in the upper right corner, but it doesn't 'pop' enough to catch my eye)

I think a good idea would be to mimic the 'spec' reporter, and repeat all failures at the top of the page.

**Comment by danielstjules** [comment] 2015-03-15 03:05
Closing as it's a duplicate of https://github.com/mochajs/mocha/issues/792 Hopefully get this resolved soon :)

**Closed by danielstjules** 2015-03-15 03:05 UTC
