### ISSUE TITLE
Error: global leak detected in chrome

### ISSUE THREAD

**Issue by olivier-o** [mochajs/mocha#463] opened 2012-06-15 02:15 UTC
Hi,
running the example found at https://github.com/adomokos/mocha-in-browser.git that is a simple mocha setup in browser.
http://sandbox.dev/mocha-in-browser/spec/runner.html run fine in safari and firefox but generate an error in chrome...

`Error: global leak detected: script1339717561999
    at Runner.checkGlobals (http://sandbox.dev/mocha-in-browser/spec/lib/mocha.js:3139:21)
    at Runner.<anonymous> (http://sandbox.dev/mocha-in-browser/spec/lib/mocha.js:3054:44)
    at Runner.emit (http://sandbox.dev/mocha-in-browser/spec/lib/mocha.js:235:20)
    at http://sandbox.dev/mocha-in-browser/spec/lib/mocha.js:3360:14
    at Test.run (http://sandbox.dev/mocha-in-browser/spec/lib/mocha.js:3003:5)
    at Runner.runTest (http://sandbox.dev/mocha-in-browser/spec/lib/mocha.js:3305:10)
    at http://sandbox.dev/mocha-in-browser/spec/lib/mocha.js:3349:12
    at next (http://sandbox.dev/mocha-in-browser/spec/lib/mocha.js:3233:14)
    at http://sandbox.dev/mocha-in-browser/spec/lib/mocha.js:3242:7
    at next (http://sandbox.dev/mocha-in-browser/spec/lib/mocha.js:3192:23)
`

this error shows on the first test that is fired (if you comment out the first one, the second generates the error)

**Comment by danielstjules** [comment] 2015-03-08 21:30
I think @bentruyman might be right. I wasn't able to reproduce the issue after cloning and running https://github.com/adomokos/mocha-in-browser.git

![screen shot 2015-03-08 at 2 28 57 pm](https://cloud.githubusercontent.com/assets/817212/6547781/7a720d42-c59f-11e4-9b50-9fdc9539ded0.png)

Closing this for now, since it's been a couple years since the last reply. Feel free to re-open and provide additional details if this still happens.
Thanks!

**Closed by danielstjules** 2015-03-08 21:30 UTC
