### ISSUE TITLE
HTML reporter bug: error is shown twice

### ISSUE THREAD

**Issue by antpaw** [mochajs/mocha#2092] opened 2016-02-04 11:30 UTC
Everytime a error happens the HTML reporter shows it twice.

here is a testcase: 
http://stuff.antpaw.de/mocha.html or https://jsfiddle.net/u5zqnwrv/

**Comment by ArnaudBuchholz** [comment] 2016-02-11 05:03
Got the same issue here

**Comment by ohnnyj** [comment] 2016-02-12 23:56
Possible duplicate of #2083.

**Comment by ArnaudBuchholz** [comment] 2016-02-14 16:33
Confirmed, I also qualified a second 'test end' call.

**Comment by danielstjules** [comment] 2016-02-16 08:31
Closing as duplicate of #2083

**Closed by danielstjules** 2016-02-16 08:31 UTC
