### ISSUE TITLE
mocha --inspect-brk --inspect seems to not be supported now

### ISSUE THREAD

**Issue by jeremychone** [mochajs/mocha#3775] opened 2019-02-25 23:14 UTC
### Prerequisites

- [x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend that you _not_ install Mocha globally.

### Description

```sh
$ ./node_modules/.bin/mocha --inspect-brk --inspect --opts mocha.opts
```

**Expected behavior:** Should work as expected with debug mode on (used to work in mocha 5.x.x)
**Actual behavior:**  but now get error: 
```sh
$ mocha --inspect-brk --inspect --opts mocha.opts 
/usr/local/bin/node: bad option: --inspect-brk --inspect
```

**Workaround**
The following seems to work. Not sure if there is a fundamental difference with the above command. 

```sh
$ node --inspect-brk --inspect ./node_modules/.bin/mocha --opts mocha.opts
```

### Versions

- The output of `node node_modules/.bin/mocha --version`: **6.0.2**
- The output of `node --version`: **v10.15.0**
- Your operating system
  - name and version: **macOS-10.14.2**
  - architecture: **64-bit**

**Comment by plroebuck** [comment] 2019-02-26 00:28
Little more information, please...
* macOS what version
* (used to work) - what version was that?

**Comment by plroebuck** [comment] 2019-02-26 00:30
> `--inspect-brk` triggers the same codepath as `--inspect --debug-brk`.

Neither here nor there, but why repeat the same cmdline argument?

**Comment by jeremychone** [comment] 2019-02-26 00:37
@plroebuck updated the OSX version and the "used to work" mocha version (5.x.x) not sure which one I had, but was in the 5.x range. 

yes, tried with `--debug-brk` as well, and does not work. When I put the `--inspect-brk --inspect` before the `...mocha` commands as node arguments, it works.

**Comment by plroebuck** [comment] 2019-02-26 00:57
I know at least two issues dealing with that argument were closed recently, but someone else's work. Did have something to do with allowing `--inspect` to have an argument though.

Try this and see if it shows anything of note:
```sh
$ DEBUG=mocha:cli:* mocha --inspect-brk --inspect --opts mocha.opts
```

**Comment by boneskull** [comment] 2019-02-26 04:57
@jeremychone `--inspect` and `--inspect-brk` is redundant.  just use `--inspect-brk`

**Comment by boneskull** [comment] 2019-02-26 05:00
I'll call this a bug since it deviates from Node's behavior, which is to ignore `--inspect` when `--inspect-brk` is present.

**Comment by boneskull** [comment] 2019-02-26 05:03
To fix this, remove `inspect` from arguments if `inspect-brk` is present.  Likewise with `debug`/`debug-brk`.  You'd probably want to do that [here](https://github.com/mochajs/mocha/blob/master/bin/mocha#L72).

Add a test that ensures it works as intended [here](https://github.com/mochajs/mocha/blob/master/test/integration/options/debug.spec.js).

**Comment by craigtaub** [comment] 2019-03-02 15:49
I can look at this.

**Comment by juergba** [comment] 2019-03-04 17:51
@craigtaub 
The bug has a different cause. Mocha did not accept more than one Node flag, see #3787 .
Node should be able to handle `--inspect` plus `--inspect-brk` anyway.
I'm sorry that I haven't seen your PR earlier.

**Comment by craigtaub** [comment] 2019-03-04 18:02
@juergba i didnt see that, your right this bug is now fixed on master.

**Closed by craigtaub** 2019-03-04 18:02 UTC
Labels: confirmed-bug, help wanted

**Comment by jeremychone** [comment] 2019-03-04 22:51
Thank you all.
