### ISSUE TITLE
skip suite and test without failing

### ISSUE THREAD

**Issue by ehartford** [mochajs/mocha#332] opened 2012-03-19 22:04 UTC
I would like some function like skipTest() and skipSuite() that would allow me to skip a test or suite without failing it.

If you are in suiteSetup() then you could skip the suite
if you are in test() then you could skip the rest of the suite or the test
if you are in setup() then you could skip the rest of the suite or the test
if you are in tearDown() then you could skip rest of the suite
if you are in suiteTearDown() then you could not skip either

**Comment by dasilvacontin** [comment] 2015-02-03 20:03
Closed by #946.

**Closed** 2015-02-03 20:03 UTC
Labels: Feature

**Comment by ToshioMagic** [comment] 2015-05-29 17:03
I'm still confused about this. I'm doing an API get, getting a 404, and then calling this.skip(). But when i call this.skip() I get an uncaught reference error to "this."

it looks like:

beforeEach(function(done) {
    // blahblahblah
    this.skip();
    done();
});

**Comment by cmbuckley** [comment] 2015-05-29 18:32
@ToshioMagic This made it into the 2.2.0 release of mocha; what version are you using?

**Comment by ToshioMagic** [comment] 2015-05-29 18:34
@cmbuckley 2.2.5

**Comment by cmbuckley** [comment] 2015-05-29 18:49
@ToshioMagic sounds like you're dealing with a separate problem, As the `this.skip()` functionality is available in your version. You may find more help on [Gitter](https://gitter.im/mochajs/mocha).

**Comment by ryanshawty** [comment] 2015-10-20 17:04
My test structure is defined inside a require module e.g.

````js
define(function(require){
  before(function(){
    // do stuff
  });

  require('spec1');
  require('spec2');
  //etc
});
````
And in the specs there is something similar to

````js
describe('Suite', function(){
  var enabled = false;
  before(function(){
    if(!loaded) return this.skip();
      // ...
  });

  it('should do something', function(){
    // ...
  });
});
````

From what I can tell if the module is not loaded it should skip the rest of suite but not skip the spec2, in my case it is skipping ALL tests after that suite. Is this by design?

**Comment by code-guru** [comment] 2015-11-19 08:20
@ToshioMagic could you solved the problem? I have the same problem, when I use skip() inside a async callback I got following error from mocha. 
 
```JavaScript
 Error: the object {
  "message": [undefined]
  "uncaught": true
} was thrown, throw an Error :)
      at Runner.fail (\node_modules\mocha\lib\runner.js:225:11)
      at Runner.uncaught (\node_modules\mocha\lib\runner.js:682:8)
      at process.uncaught (\node_modules\mocha\lib\runner.js:727:10)
```

I'm using mocha v2.3.4 . can anyone confirm this problem? Should I open a new issue?

**Comment by danielstjules** [comment] 2015-11-19 08:25
@code-guru skip within async code isn't yet supported, sorry! See https://github.com/mochajs/mocha/pull/1618

**Comment by Himanshu11051** [comment] 2015-11-19 11:00
That worked thanks. :)

**Comment by code-guru** [comment] 2015-11-20 15:11
@danielstjules Thanks dan, I saw you had added the async skip to previous releases. But why it is not available in v2.3.4?

I think its use cases are very common. For example when you have an end2end system test, and need to check if the server is listening, and if it isn't, just skip the test. 

Also since all network requests and database connections are aync in node.js, an async skip is a necessity, and not just a fancy feature.

**Comment by mmigdol** [comment] 2016-09-18 19:35
Async skip was added in #2335

**Comment by mrt123** [comment] 2016-12-02 12:01
as of mocha 3.2.0
* `this.skip()`  works in `before` or in `it`, but not inside `describe`
* best option for conditionally skipping `describe` is `this.pending = myCondition;`
** however that does not seem to be part of your documented api.


And yes, for any doubters, the use case if very common: 
* using mocha to drive acceptance tests with selenium
* application is build in test mode first and tested in test environment with limited features
* then application is then progressed to next stage with more realistic / costly to build environment and full suite of features available (think large databases, added 3rd party providers , like payment processing etc).

**Comment by dasilvacontin** [comment] 2016-12-02 12:18
I agree functionality / methods should be consistent.

I wanted to point out that – as I got it – the outcome described in your use cases would be better addressed by the tagging feature (which is not there yet but): https://github.com/mochajs/mocha/pull/1445.

**Comment by mrt123** [comment] 2016-12-02 12:30
@dasilvacontin  Thanks, for making me aware of work being done on Tags.

However tags are inferior, to simply allowing a conditional. First of all, for most scenarios , they will force you to tag every single spec. Also you can imagine someone coming up with multiple tags just to describe few conditions.  Allowing for conditionals is much more flexible. 

Simply ensuring this.skip() works everywhere (describe, it , before etc) , and being able to provide optional skip reason, that would participate in output, would be the most flexible thing to do:
Simplest example: 
```
if(myCondition) {
   this.skip('My reason for skipping');
}
```
Outputs : 
`- [Skip Reason: My reason for skipping. TEST LABEL: alert shows when leaving.`

**Comment by dasilvacontin** [comment] 2016-12-02 13:18
> they will force you to tag every single spec

@mrt123 Wouldn't you have to add an `if () { this.skip(...)` to every spec otherwise?

```js
// file1
describe('some class', function () {
  this.tag('integration', 'slow')
  ...
})

// file2
describe('some other class', function () {
  this.tag('integration', 'slow')
  ...
})
```
vs
```js
// file1
const { isIntegration, isSlow } = require('./specUtils.js')

describe('some class', function () {
  if (isIntegration) this.skip('integration skip reason')
  if (isSlow) this.skip('slow skip reason')
  ...
})

// or
const { skipIfIntegration, skipIfSlow } = require('./specUtils.js')

describe('some class', function () {
  skipIfIntegration(this)
  skipIfSlow(this)
  ...
})
```

(since you probably want to reuse the condition across spec files, and maybe some of the skip messages)

If what you are concerned about is skip messages, that's a different improvement, and nothing would stop you from using both tags and skip when there's a particular case where you want to skip + show a message.

**Comment by dasilvacontin** [comment] 2016-12-02 13:26
To sum up, it feels like moving conditions from setup declarations to code inside tests. You would be able to have any conditions you want that generate options / set filter tags. Unless you don't plan on reusing them in multiple specs/tests, I don't see the benefit of having the condition inside the spec/test itself.

```js
// setup.js
const mocha = require('mocha')

const tags = []
if (/* integration condition */) tags.push('integration')
if (/* slow condition */) tags.push('slow')
mocha.tags(tags)
```

**Comment by mrt123** [comment] 2016-12-02 14:11
@dasilvacontin   Agreed, however still `this.skip()` currently (v3.2.0) does not work inside `describe`. And I don't see any other documented way.

**Comment by dasilvacontin** [comment] 2016-12-02 14:36
@mrt123 Yep, I'm aware of that sad fact. I was just replying to:

> However tags are inferior, to simply allowing a conditional. First of all, for most scenarios , they will force you to tag every single spec. Also you can imagine someone coming up with multiple tags just to describe few conditions. Allowing for conditionals is much more flexible.

For now you can only conditionally declare the sub `it`/`describe`s. If conditions are async, we have `--delay`.
