### ISSUE TITLE
skip and only for exports ui

### ISSUE THREAD

**Issue by seanmonstar** [mochajs/mocha#1073] opened 2013-12-17 03:59 UTC
I see in #524 is where `.skip()` and `.only()` where added, and some of the comments were looking for ways that this could be used with the exports ui. The commit including them says "only tdd and bdd for now", but that's a year ago.

Could strings of "comment" and "hashbang" be used for skip and only?

``` js
module.exports = {
  Array: {
    '//should be skipped': function() {},
    '#!should be only test': function(){}
  }
};
```

Or something? Anything? I much prefer exports ui, but I miss being able to use skip and only.

**Comment by rgraffbrd** [comment] 2018-09-06 20:03
I'm also looking for a way to mark a test, using the exports ui, as ONLY.

**Comment by resistdesign** [comment] 2020-05-19 01:04
Oh man, I thought this was already a thing! 😮

**Comment by JoshuaKGoldberg** [comment] 2023-12-27 21:11
Duplicate of #928... I think. Someone yell at me if this is for something else. But at the very least I think #928 is more fleshed out and would solve the same use case as this.

**Closed by JoshuaKGoldberg** 2023-12-27 21:11 UTC
Labels: type: feature, status: accepting prs
