### ISSUE TITLE
unable to listen to start event during programmatic run

### ISSUE THREAD

**Issue by grawk** [mochajs/mocha#2753] opened 2017-03-27 04:02 UTC
The 'start' event is emitted synchronously downstream of the `mocha.run` method. Thus, if you are attaching a listener to that event after calling `mocha.run` (to get the runner instance), you miss the event:

```js
var runner = mocha.run(function (failures) {
  process.on('exit', function () {
    process.exit(failures);  // exit with non-zero status if there were failures
  });
});
runner.on('start', function (Evt) {
  //never called
});
```

Maybe there is some other way to attach event listeners to the runner prior to calling run, but I haven't found it yet.

**Comment by kunagpal** [comment] 2017-05-30 21:39
This is an issue with Mocha v3.4.2 and should probably be marked as confirmed.

**Comment by ScottFreeCode** [comment] 2017-05-31 02:57
I just tried this out to confirm it; looks like we'll want to change https://github.com/mochajs/mocha/blob/a054380203d1d7f271ff0649656779915ac28e63/lib/runner.js#L807 to move the `emit` and `runSuite` calls into an asynchronous callback (perhaps `Runner.immediately`?)... We'll also want a test for it, should be pretty simple -- just `new Runner(<whatever the minimum requirement is -- check existing Runner tests>).run().on("start", <spy>).on("end", function() { <assert that spy was called>; done() })`, I think.

**Comment by boneskull** [comment] 2017-10-17 04:17
linking back to #3065

**Comment by fancy967** [comment] 2018-05-23 05:41
Hi guys, any plan to fix this?

**Closed** 2020-03-09 08:02 UTC
Labels: confirmed-bug
