### ISSUE TITLE
awaiting promises in describe blocks makes mocha ignore following it blocks

### ISSUE THREAD

**Issue by manuschillerdev** [mochajs/mocha#4819] opened 2022-01-24 09:34 UTC
### Prerequisites

- [x ] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [ x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [ x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend that you _not_ install Mocha globally.

### Description

awaiting a promise in a describe block makes mocha ignores all following it blocks.
One can fix the behaviour by awaiting the promise inside another it or before block.

### Steps to Reproduce
I created a minimal reproduction here:
https://stackblitz.com/edit/testing-mocha-b5uca7?file=src%2Findex.js

**Expected behavior:** [What you expect to happen]
awaiting the promise in the describe block should not make mocha ignore all following it blocks.

**Actual behavior:** [What actually happens]
awaiting the promise in the describe block leads to mocha never executing the following it blocks.

**Reproduces how often:** 
consistently (100%)

### Versions

- The output of `mocha --version` and `node node_modules/.bin/mocha --version`: 8.4.0
- The output of `node --version`: unknown (how can I detect that on stackblitz?)

**Comment by juergba** [comment] 2022-01-24 16:25
duplicate of eg. #2975

**Closed by juergba** 2022-01-24 16:25 UTC
Labels: duplicate
