### ISSUE TITLE
🚀 Feature: Ability to teardown globals on after hooks

### ISSUE THREAD

**Issue by jwalton** [mochajs/mocha#2206] opened 2016-04-12 14:55 UTC
When run with `--check-leaks`, this test:

```
describe('geolocate', () => {
    before(() => global.navigator = {});
    after(() => delete global.navigator);

    it('should get the current position from navigator', () => {
        // Do nothing.
    });

});
```

fails with "Error: global leak detected: navigator", even though the `after` cleans up the navigator object.

**Comment by dasilvacontin** [comment] 2016-04-13 07:48
@jwalton globals are checked right after the `it` finishes:
- https://github.com/mochajs/mocha/blob/9ae6a85b6ba50ea415affc88456d469d6915a157/lib/runner.js#L72-L74
- https://github.com/mochajs/mocha/blob/9ae6a85b6ba50ea415affc88456d469d6915a157/lib/runner.js#L528-L559.

If you don't check after the `it`, you can't know whether the global was introduced by the hook or the `it`.

**Comment by ScottFreeCode** [comment] 2016-04-14 04:56
Given that the "leak" in this case *is* coming from a hook (the before hook, rather than the after hook), that's a bit ironic; could leaks be checked after the before/beforeEach hooks and any detected there be added to the ignored globals for the check against the tests?

**Comment by dasilvacontin** [comment] 2016-04-14 06:47
@ScottFreeCode well pointed out, I had overlooked that detail. Maybe it would be nice to track the existing globals before the `it` and after the `it` so we can allow global variable teardown in hooks.

**Comment by ScottFreeCode** [comment] 2016-04-14 22:49
Another nice thing about that approach: it would probably also reduce the cases for which globals need to be ignored in general, since if I'm not mistaken right now it's needed to ignore globally declared dependencies and such even if they didn't leak from the actual tests.

**Comment by jwalton** [comment] 2016-04-14 23:46
It *is* nice to find globals that don't leak from the tests, though.  Saved me once or twice when I was missing a "var" at top level scope.  :)

**Comment by danielstjules** [comment] 2016-04-27 08:40
> could leaks be checked after the before/beforeEach hooks and any detected there be added to the ignored globals for the check against the tests?

I think that's a bit too much magic. I would much prefer having the check run after all `afterEach/after` hooks, which would allow @jwalton's original example to pass.

**Comment by JoshuaKGoldberg** [comment] 2024-01-21 06:46
Duplicate of #4954. That one was filed much later than this one, but has a very clean reproduction case - so let's go with it.

**Closed by JoshuaKGoldberg** 2024-01-21 06:46 UTC
Labels: type: feature
