### ISSUE TITLE
Execute flags are missing in Mocha 3.4.1 when installed with --no-bin-links

### ISSUE THREAD

**Issue by meister** [mochajs/mocha#2809] opened 2017-05-16 08:05 UTC
When Mocha is installed with `--no-bin-links`, the executable flags are missing in `bin/` folder. So all the test that are configured for no-bin-links environments will fail to execute.

Environment:
Node v6.10.2
NPM v3.10.10

```
bash-4.3# npm install --no-bin-links mocha@3.4
/test
`-- mocha@3.4.1

bash-4.3# ls -l node_modules/mocha/bin/
total 24
-rw-r--r--    1 root     root         12862 May 14 19:03 _mocha
-rw-r--r--    1 root     root          2234 May 14 19:03 mocha
-rw-r--r--    1 root     root           710 May 14 19:03 options.js
bash-4.3# npm install --no-bin-links mocha@3.3
/test
`-- mocha@3.3.0

bash-4.3# ls -l node_modules/mocha/bin/
total 24
-rwxr-xr-x    1 root     root         12575 Apr 24 08:46 _mocha
-rwxr-xr-x    1 root     root          2179 Apr 24 08:46 mocha
-rw-r--r--    1 root     root           710 Oct 24  2016 options.js
```

Note the missing `x` flag in 3.4.1 installation.

**Comment by ScottFreeCode** [comment] 2017-05-16 16:58
Did this change from a previous release? I thought NPM sets the flags on installation, but I'm not familiar with the `--no-bin-links` behavior.

**Comment by rreinurm** [comment] 2017-05-16 21:17
The previous release 3.3.0 is working as expected using npm v2, v3 and v4. Since mocha version 3.4 the mocha scripts lost execute flag then bin-links are disabled.

**Comment by ScottFreeCode** [comment] 2017-05-17 06:39
Hmm. So, a possible temporary workaround would be to chmod the files, if I'm not mistaken?

Not that I'd recommend it long-term, because it shouldn't be necessary in the first place.

My next big question is, how urgent is this to fix? The next release should fix it regardless, and will happen this week if anything else affecting behavior gets merged. But if it's critical to get it out sooner, we can try to put together a quick release with just the permissions flags fixed.

**Comment by rreinurm** [comment] 2017-05-17 06:48
We locked mocha version to 3.3 to overcome the issue and yes chmod can be used as a workaround. If you can release a fixed version in a week I believe its fast enough.

**Comment by ScottFreeCode** [comment] 2017-05-24 17:02
@meister @rreinurm Can you confirm that this is fixed in 3.4.2? Thanks!

**Comment by meister** [comment] 2017-05-25 08:23
Confirmed. Working in 3.4.2.

**Comment by rreinurm** [comment] 2017-05-25 08:24
Confirmed. Tested with npm v2, v3, v4.

**Comment by ScottFreeCode** [comment] 2017-05-26 03:00
Thanks!

Sorry again about the inconvenience.

**Closed by ScottFreeCode** 2017-05-26 03:00 UTC
Labels: confirmed
