### ISSUE TITLE
this.timeout(0)

### ISSUE THREAD

**Issue by ORESoftware** [mochajs/mocha#1742] opened 2015-06-11 00:45 UTC
Frankly, thinking about it for a couple seconds

for developers sharing code:

this.timeout('disable') is a lot more clear in terms of intent than this.timeout(0)

the latter makes it seem like the test should fail almost automatically

the former makes it clear that you actually want to disable timeouts for the test

would be easy to implement, but might be too late in terms of backward compatibility

**Comment by ORESoftware** [comment] 2015-06-11 00:46
also, as an important detail, the reason I posted this issue in the first place, was because this.timeout(0) inside of a mocha it() function was not in fact disabling timeouts for that test, even though the mocha docs indicate that it should disable the timeout.

**Comment by rstacruz** [comment] 2015-06-15 10:24
I disagree. a string like `'disable'` is so arbitrary. `timeout(false)` might be clearer.

**Comment by danielstjules** [comment] 2015-06-15 14:42
> the reason I posted this issue in the first place, was because this.timeout(0) inside of a mocha it() function was not in fact disabling timeouts for that test,

I think that's a bigger issue. :) Do you have an example? Couldn't reproduce with a quick test against master:

``` javascript
$ cat example.js
it('test', function(done) {
  this.timeout(0);
  setTimeout(done, 2000);
});
$ mocha example.js

  ․

  1 passing (2s)
```

And I agree with @rstacruz that `'disable'` is a bit arbitrary. However, both 0 and -1 are very common values for APIs to disable a restriction or limit. I'm of the opinion that this doesn't need to change.

**Comment by ORESoftware** [comment] 2015-06-16 00:00
thanks guys, I really don't care if it's this.timeout(false) or this.timeout(-1) or this.timeout('the best choice'), anything but this.timeout(0) ! :)

**Comment by ORESoftware** [comment] 2015-06-16 00:01
I will try to reproduce the this.timeout(0) failing to work as soon as possible

**Comment by dasilvacontin** [comment] 2015-06-16 07:00
@ORESoftware Make a PR that adds the failing unit test, that would be perfect. :)

**Comment by EvanHahn** [comment] 2015-07-01 16:18
I'm fine with `this.timeout(0)`, FWIW.

**Comment by ORESoftware** [comment] 2015-07-01 18:54
I am working on multiple projects and can't find the this.timeout(0) that I was thinking of, but give me a few more days to see if I can find it. I think this.timeout(-1) makes the most sense, but this.timeout(0) is not the end of the software world.

**Comment by ORESoftware** [comment] 2015-07-01 18:55
if I recall, the reason why I turned the timeout(s) off was so I could debug the mocha test with node-inspector

**Comment by danielstjules** [comment] 2015-07-01 19:08
I'm impartial. Setting values to 0 or a negative value to disable is very common. As with false.
https://github.com/search?utf8=%E2%9C%93&q=%22or+0+to+disable%22&type=Code&ref=searchresults (have to go through a few pages)
https://github.com/search?utf8=%E2%9C%93&q=%22or+false+to+disable%22&type=Code&ref=searchresults

I see a lot of "0 or false to disable it"

**Comment by ORESoftware** [comment] 2015-07-01 19:36
I agree that it is probably more common to see 0 or false in this case but

this.timeout(-1) makes the most sense, and I believe it gels more with the world outside of Node.js.

this.timeout(false) or this.timeout(0) has the wrong semantics - for example, this.timeout(true) doesn't mean anything, that's why this.timeout(false) should not mean what does mean in this library either.

**Comment by danielstjules** [comment] 2015-07-01 20:00
> I agree that it is probably more common to see 0 or false in this case but this.timeout(-1) makes the most sense

I disagree - I think it's best to stay consistent with both nodejs, as well as the rest of the community. 0 is very common for disabling timeouts and limits.

https://nodejs.org/api/net.html#net_socket_settimeout_timeout_callback
> If timeout is 0, then the existing idle timeout is disabled.

https://nodejs.org/api/http.html#http_server_timeout
> Set to 0 to disable any kind of automatic timeout behavior on incoming connections.

https://nodejs.org/api/http.html#http_server_maxheaderscount
>  If set to 0 - no limit will be applied.

https://github.com/felixge/node-mysql/#pool-options
> If set to 0, there is no limit to the number of queued connection requests. (Default: 0)

https://github.com/felixge/node-mysql/#poolcluster-option
> If set to 0, then node will be removed instead and never re-used. (Default: 0)

https://github.com/mqttjs/MQTT.js#mqttclientstreambuilder-options
> keepalive: 10 seconds, set to 0 to disable

https://github.com/tomas/needle#request-options
> open_timeout: (or timeout) Returns error if connection takes longer than X milisecs to establish. Defaults to 10000 (10 secs). 0 means no timeout.
>  read_timeout: Returns error if data transfer takes longer than X milisecs, after connection is established. Defaults to 0 (no timeout).

https://github.com/bitinn/node-fetch#options
> // req/res timeout in ms, 0 to disable

I'm going to close this issue for now, opting to preserve backwards compatibility for this part of the API. If you're able to replicate the timeout issue, could you open a new issue with a reproduce case? I'd love to fix that if you're able to reproduce it. Thanks again! :)

**Closed by danielstjules** 2015-07-01 20:00 UTC
