### ISSUE TITLE
Allow passing configuration via environment variables

### ISSUE THREAD

**Issue by icholy** [mochajs/mocha#5044] opened 2023-12-08 21:12 UTC
**Is your feature request related to a problem or a nice-to-have?? Please describe.**

I have a launch config in neovim which runs `npm test`. I'd like a mechanism to pass `--inspect-brk` to mocha. Setting `NODE_OPTIONS=--inspect-brk` isn't an option because it affects all tools that are executed by the `test` script.

**Describe the solution you'd like**

A `MOCHA_OPTIONS` environment variable variable similar to [NODE_OPTIONS](https://nodejs.org/api/cli.html#node_optionsoptions).

**Describe alternatives you've considered**

Yargs has support for env variables: https://yargs.js.org/docs/#api-reference-envprefix
However, using this feature would result in a separate env variable for each option:

Ex:

* `MOCHA_BAIL`
* `MOCHA_ALLOW_UNCAUGHT`
* `MOCHA_FAIL_ZERO`
* etc ...

**Comment by icholy** [comment] 2023-12-08 21:12
PR https://github.com/mochajs/mocha/pull/4835

**Comment by JoshuaKGoldberg** [comment] 2023-12-27 07:06
Duplicate of #4330.

**Closed by JoshuaKGoldberg** 2023-12-27 07:06 UTC
Labels: type: feature
