### ISSUE TITLE
Mocha enforces synchronous timeouts

### ISSUE THREAD

**Issue by peterjwest** [mochajs/mocha#2779] opened 2017-04-26 10:32 UTC
It seems to me that the timeout in mocha exists to catch unhandled asynchronous tests, which would otherwise cause the test to hang indefinitely.

However, Mocha also fails synchronous steps which exceed this limit. The problem with this is that Mocha can only enforce this limit after the step has successfully finished processing, so there is no reason the test could not be allowed to complete successfully.

I'd like to propose either removing synchronous timeouts, demoting them to a warning or allowing a separate timeout to be set for synchronous/asynchronous.

Timeout test cases: https://gist.github.com/peterjwest/ae556cfd329983575a47ca0b9d4b1cd3

**Comment by ScottFreeCode** [comment] 2017-04-27 02:19
As I mentioned on Gitter, this does seem a bit odd to me but I don't know if there was a rationale for it or if it's unintentional; I did try put together the simplest test case I can, however:
```js
it("times out", function() {
    var then = Date.now();
    while (Date.now() < then + 2100) {}
});
```

**Comment by ScottFreeCode** [comment] 2017-05-25 03:35
Possibly related to #1667

**Comment by TC-jPham** [comment] 2019-04-08 17:20
Any update on whether this will get fixed any time in the future/soon?

**Comment by boneskull** [comment] 2019-04-08 17:56
@TC-jPham if this is affecting you, please consider sending a PR to address the behavior.

**Comment by audoh-red7** [comment] 2019-04-09 09:01
> @TC-jPham if this is affecting you, please consider sending a PR to address the behavior.

`function done (err) {
    var ms = self.timeout();
    if (self.timedOut) {
      return;
    }
    if (finished) {
      return multiple(err || self._trace);
    }

    self.clearTimeout();
    self.duration = new Date() - start;
    finished = true;
    if (!err && self.duration > ms && self._enableTimeouts) {
      err = new Error('Timeout of ' + ms +
      'ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.');
    }
    fn(err);
  }`
The solution would be to remove that last conditional, but since it's specifically there in the done() block, it feels by design?

**Comment by boneskull** [comment] 2019-04-09 17:56
actually... I'm thinking maybe this should be a `wontfix`.

> However, Mocha also fails synchronous steps which exceed this limit. The problem with this is that Mocha can only enforce this limit after the step has successfully finished processing, so there is no reason the test could not be allowed to complete successfully.

There *is* a reason to fail such a test: if you expect it to finish in *n* ms.  You can always disable timeouts for tests where this is undesirable behavior.

**Comment by boneskull** [comment] 2019-04-09 17:56
@mochajs/core thoughts?

**Comment by juergba** [comment] 2019-04-10 08:32
The docu states:
> Note: synchronous (blocking) tests are also bound by the timeout, but they will not complete until the code stops blocking. Infinite loops will still be infinite loops!

So yes, a synch test terminates first - maybe even successfully - and then fails by a timeout error. It seems synchronous timeouts are intented by design and altering this behavior would be a breaking change. Unless we extend our options with a seperate timeout flag.

**Comment by Bamieh** [comment] 2019-04-10 09:36
I am afraid that addressing this issue would only further complicate mocha API.
Currently timeouts are straightforward.

If the code block (sync or async) exceeds the timeout limit, the test will fail. If users want it otherwise they'd change the timeout for the test case or config wise depending on their need.

This issue was opened since 2017 and i don't see a huge traction to change the current behavior.

**Comment by peterjwest** [comment] 2019-04-10 11:04
At this point I'm happy to use the existing API to solve my issues, feel free to close.

**Closed** 2019-04-10 12:25 UTC
Labels: wontfix
