### ISSUE TITLE
Can't Install Mocha: Hostname/IP does not match certificate's altnames

### ISSUE THREAD

**Issue by yuens1002** [mochajs/mocha#3473] opened 2018-09-01 11:44 UTC
expected:
install mocha with `npm i mocha`

got this from the terminal after running the install
```
npm ERR! code ERR_TLS_CERT_ALTNAME_INVALID
npm ERR! errno ERR_TLS_CERT_ALTNAME_INVALID
npm ERR! request to https://registry.npmjs.org/mocha failed, reason: Hostname/IP does not match certificate's altnames: Host: registry.npmjs.org. is not in the cert's altnames: DNS:a.sni.fastly.net, DNS:a.sni.global-ssl.fastly.net
```

windows 10, 64bit
NPM v6.4.1
Node v10.8.0

**Comment by outsideris** [comment] 2018-09-02 07:59
In my case, it is fine.
I guess the problem is related with https://status.npmjs.org/incidents/v22ffls5cd6h .

**Comment by plroebuck** [comment] 2018-09-02 16:32
@outsideris, close this, with reason you gave earlier.
Nothing to do with Mocha...

**Closed** 2018-09-03 10:35 UTC
Labels: question
