### ISSUE TITLE
Cannot run `ui: 'exports'` tests using API.

### ISSUE THREAD

**Issue by rpaterson** [mochajs/mocha#3004] opened 2017-09-12 10:50 UTC
### Prerequisites

* [x] Checked that your issue isn't already filed by cross referencing [issues with the `common mistake` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Acommon-mistake%20)
* [x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
* [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
* [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with:
`node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend avoiding the use of globally installed Mocha.

### Description

Cannot run `ui: 'exports'` tests using API.  The call to `mocha.run()` throws an exception "TypeError: Cannot read property 'skip' of undefined".

### Steps to Reproduce
Create a file `MyTestFile.js` with contents:
```Javascript
exports.MyTest = {
    myTestFunction() {
    }
};
```
Then run `node -e "const Mocha = require('mocha'); const mocha = new Mocha({ ui: 'exports' }); mocha.addFile('./MyTestFile.js'); mocha.run();"`

**Expected behavior:**
Test should pass.

**Actual behavior:**
Throws exception:
```
/home/rpaterson/programming/signpost/toshokan/node_modules/mocha/lib/mocha.js:207
    exports.xit = context.xit || context.test.skip;
                                             ^

TypeError: Cannot read property 'skip' of undefined
    at Suite.<anonymous> (/home/rpaterson/programming/signpost/toshokan/node_modules/mocha/lib/mocha.js:207:46)
    at emitThree (events.js:116:13)
    at Suite.emit (events.js:194:7)
    at /home/rpaterson/programming/signpost/toshokan/node_modules/mocha/lib/mocha.js:230:11
    at Array.forEach (native)
    at Mocha.loadFiles (/home/rpaterson/programming/signpost/toshokan/node_modules/mocha/lib/mocha.js:228:14)
    at Mocha.run (/home/rpaterson/programming/signpost/toshokan/node_modules/mocha/lib/mocha.js:514:10)
    at [eval]:1:117
    at ContextifyScript.Script.runInThisContext (vm.js:25:33)
    at Object.exports.runInThisContext (vm.js:77:17)
```
**Reproduces how often:**
100% of the time.

### Versions

Problem does not happen in v3.5.0, starts happening in v3.5.1.  The line that is throwing the exception was added in that release by 1cc0fc0e6153bbd746b0c2da565363570432cdf7.

**Comment by ScottFreeCode** [comment] 2017-09-13 00:26
Hmm. Given that those assignments seem to depend on the BDD or TDD interface being chosen, I think we could put that whole callback in an `if` to filter out the Exports interface. ...And the QUnit interface if it isn't close enough to the TDD interface to make these assignments work, which I'd have to do a little more digging to confirm or deny.

**Comment by plroebuck** [comment] 2018-10-12 17:22
@arvind, To my knowledge, _no one is working on this issue_!
Provide an MCVE and I'll take a look when I get a chance.

**Comment by plroebuck** [comment] 2018-10-12 19:15
Unverified but...

`exports` ui:
* minus sign prepended to title will skip test, same as calling `it.skip`
* exclamation point prepended to title will make test exclusive, same as calling `it.only`

**Comment by juergba** [comment] 2018-12-11 07:01
@boneskull please close, since solved in b5c0fb0

**Comment by juergba** [comment] 2018-12-17 07:36
@outsideris could you please close this issue? Thanks.

**Comment by outsideris** [comment] 2018-12-17 16:15
I confirmed it fixed as @juergba said.

**Closed by outsideris** 2018-12-17 16:15 UTC
Labels: confirmed-bug, help wanted
