### ISSUE TITLE
--harmony-proxies option not working

### ISSUE THREAD

**Issue by JaKXz** [mochajs/mocha#1980] opened 2015-11-26 01:35 UTC
This is my `mocha.opts` file in my `test/` folder:

```
--compilers js:babel/register
--require mocha.conf.js
--harmony-proxies
```

I'm using mocha v2.3.4, and node v5.1.0 and I get the error:

```
  error: unknown option `--harmony-proxies'
```

_EDIT: In fact, none of the `--harmony` options are working._

**Comment by danielstjules** [comment] 2015-11-26 03:15
Looks like a regression in 2.3.3. Works in 2.3.2.

**Comment by boneskull** [comment] 2015-11-26 03:15
@danielstjules I don't know about that, I can't reproduce it using his setup.

**Comment by danielstjules** [comment] 2015-11-26 03:17
@boneskull I think it's a regression :(

```
$ cat test/mocha.opts
--harmony-proxies
dstjules:~/Desktop
$ mocha --version
2.3.2
dstjules:~/Desktop
$ mocha


  0 passing (4ms)

dstjules:~/Desktop
$ npm install -g mocha@2.3.3
/usr/local/bin/mocha -> /usr/local/lib/node_modules/mocha/bin/mocha
/usr/local/bin/_mocha -> /usr/local/lib/node_modules/mocha/bin/_mocha
mocha@2.3.3 /usr/local/lib/node_modules/mocha
├── escape-string-regexp@1.0.2
├── supports-color@1.2.0
├── growl@1.8.1
├── commander@2.3.0
├── diff@1.4.0
├── debug@2.0.0 (ms@0.6.2)
├── jade@0.26.3 (commander@0.6.1, mkdirp@0.3.0)
├── glob@3.2.3 (inherits@2.0.1, graceful-fs@2.0.3, minimatch@0.2.14)
└── mkdirp@0.5.0 (minimist@0.0.8)
dstjules:~/Desktop
$ mocha --version
2.3.3
dstjules:~/Desktop
$ mocha

  error: unknown option `--harmony-proxies'
```

**Comment by danielstjules** [comment] 2015-11-26 03:19
Looks like it's my fault, sorry: https://github.com/mochajs/mocha/commit/c4647bf2fa167501e40d1c9a3858b09eae741700

**Comment by danielstjules** [comment] 2015-11-26 03:20
@JaKXz Note that this still works by passing options to the bin. So in the meantime, you can do:
`mocha --harmony-proxies`

I'll have a fix for this tomorrow.

**Comment by JaKXz** [comment] 2015-11-26 03:32
@danielstjules thanks!

**Comment by danielstjules** [comment] 2015-12-26 05:53
Nevermind, this isn't a regression after all. Any node-specific flags (harmony, etc) need to be passed via CLI, and not placed in mocha.opts. When passed via CLI, bin/mocha will spawn an instance of bin/_mocha with the harmony flags.

**Comment by danielstjules** [comment] 2015-12-26 06:01
This was a result of https://github.com/mochajs/mocha/pull/1910 But we can't remove getOptions from _mocha, due to https://github.com/mochajs/mocha/issues/1645 I think an immediate solution would be to check whether or not the options have already been loaded

**Comment by danielstjules** [comment] 2015-12-26 06:35
Fixed in master. Thanks again! :)

**Closed** 2015-12-26 06:34 UTC

**Comment by JaKXz** [comment] 2015-12-26 07:23
Thank you, @danielstjules!

**Comment by josmardias** [comment] 2016-03-26 03:04
Harmony flags doesn't work for me while using bin/_mocha (required by istanbul)

```
  "devDependencies": {
    "chai": "^3.5.0",
    "istanbul": "^0.4.2",
    "mocha": "^2.4.5"
  },
```

I'm trying ```--harmony_default_parameters``` node flag
Reproduction [here](https://github.com/josmardias/mocha-issue-1980-repro)

Obs.: it does work for bin/mocha binary

**Comment by boneskull** [comment] 2016-03-26 08:01
@josmardias `mocha` exists so that `_mocha` can be run with node flags.  You will need to execute istanbul with node flags.
