### ISSUE TITLE
Programatic API cannot access retry test objects

### ISSUE THREAD

**Issue by akiroz** [mochajs/mocha#3849] opened 2019-03-27 03:01 UTC
Currently the programatic API can only access the first attempt of each test if there are multiple retries because the `Runner.runTests` method clones the test array inside the suite and mutates the cloned array for retries.

https://github.com/mochajs/mocha/blob/586bf78499b23e5f514b534cf93cf31e53fd0a42/lib/runner.js#L544

https://github.com/mochajs/mocha/blob/586bf78499b23e5f514b534cf93cf31e53fd0a42/lib/runner.js#L659

It would be great if I could access the final attempt by default and even better if I could access all attempts somehow.

**Comment by plroebuck** [comment] 2019-03-29 10:19
Can you not get this information listening to `EVENT_TEST_RETRY` yourself?

**Comment by akiroz** [comment] 2019-03-29 17:14
Yes, I think it should be possible. Thanks for the suggestion.
I just realized that my project was on an old version of mocha that didn't have the `retry` event.

Although I still think it would make more sense to have the final attempt test object in the suite...

**Comment by juergba** [comment] 2020-02-05 19:03
duplicate of #2188

**Closed by juergba** 2020-02-05 19:03 UTC
Labels: feature
