### ISSUE TITLE
Add browser testing to CI

### ISSUE THREAD

**Issue by ndhoule** [mochajs/mocha#1732] opened 2015-06-07 19:55 UTC
This probably involves some test refactoring work, but moving to Browserify means it's easy to add a Node shim without really thinking about it, and some of Browserify's shims rely on an ES5 environment. Would be easy to break IE6 without noticing.

**Comment by boneskull** [comment] 2015-06-08 18:52
I'm more than ready to drop IE6 support

**Comment by boneskull** [comment] 2015-06-10 20:42
@mochajs/mocha We need automated tests for Mocha which run in the browser.

Anyone have any opinions on the best way to get this done?

When I need to run client-side tests, I reach for [Karma](https://www.npmjs.com/package/karma).  If I need to debug something, I tell it to use a real browser, but otherwise I run headlessly with PhantomJS.

If there are any services out there that would automate the tests against real browsers *for free*, I'd like to know about them.

**Comment by ndhoule** [comment] 2015-06-10 21:37
I generally go for Sauce Labs to run cross-browser tests. Free for OSS projects.

Karma's fine for most cases but its Sauce runner has [a long-standing concurrency issue](https://github.com/karma-runner/karma-sauce-launcher/issues/40) that has made it difficult for me to run tests against multiple browsers in the past. Might be able to get around this by only running one browser at a time through Karma. I prefer [Zuul](https://github.com/defunctzombie/zuul) these days; some annoying edges but it doesn't involve the same level of configuration Karma does and works OOTB with Browserify.

**Comment by dasilvacontin** [comment] 2016-04-22 06:54
Dupe of #2079.

**Closed by dasilvacontin** 2016-04-22 06:54 UTC
Labels: High priority, PR PLEASE, Test
