### ISSUE TITLE
mocha@2.5.0 depends on to-iso-string

### ISSUE THREAD

**Issue by ericprud** [mochajs/mocha#2276] opened 2016-05-23 08:25 UTC
When I upgrade from mocha@2.4.5 to mocha@2.5.0, I fail with
<pre>
eric@mouni2:/tmp/checkouts/shex.js$ npm test

> shex@0.5.9 test /tmp/checkouts/shex.js
> mocha -C -R dot

module.js:327
    throw err;
    ^

Error: Cannot find module 'to-iso-string'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/tmp/checkouts/shex.js/node_modules/mocha/lib/utils.js:15:19)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
npm ERR! Test failed.  See above for more details.
</pre>
I see

  "to-iso-string": "0.0.2"

in devDependencies but not dependencies.

**Comment by elrrrrrrr** [comment] 2016-05-23 08:28
+1

**Comment by rockdai** [comment] 2016-05-23 08:28
+1

**Comment by DinisCruz** [comment] 2016-05-23 08:44
Here is the error as caught by travis
![image](https://cloud.githubusercontent.com/assets/656739/15465141/fb770942-20ca-11e6-9216-6c57d3c6cc80.png)

**Comment by DinisCruz** [comment] 2016-05-23 08:46
short term solution is to ```npm install to-iso-string```

**Comment by Levino** [comment] 2016-05-23 08:47
The issue is that "to-iso-string" ist a dev dependency instead of dependency.

**Comment by aivus** [comment] 2016-05-23 08:47
It will be fixed
https://github.com/mochajs/mocha/commit/bd9450b9e5522cb8d89abc926a754752dc697b39

**Comment by Levino** [comment] 2016-05-23 08:49
@aivus How long for build? Can one check progress somewhere?

**Comment by DinisCruz** [comment] 2016-05-23 08:50
thx @aivus for pushing a quick fix

**Comment by DinisCruz** [comment] 2016-05-23 08:50
btw, is npm slow to you? https://www.npmjs.com/package/mocha at the moment is taking ages to load

**Comment by aivus** [comment] 2016-05-23 08:52
@Levino @DinisCruz published https://github.com/mochajs/mocha/releases/tag/v2.5.1

**Comment by boneskull** [comment] 2016-05-23 08:53
fixed in 2.5.1

**Comment by boneskull** [comment] 2016-05-23 08:53
sorry!

**Closed by boneskull** 2016-05-23 08:53 UTC

**Comment by DinisCruz** [comment] 2016-05-23 09:01
@boneskull no probs, all fixed now

![image](https://cloud.githubusercontent.com/assets/656739/15465610/53135398-20cd-11e6-88dc-62d72b0fbd3d.png)
