### ISSUE TITLE
🚀 Feature: Add pseudo-tests for timing of before()/after() hooks

### ISSUE THREAD

**Issue by plroebuck** [mochajs/mocha#3368] opened 2018-05-02 01:56 UTC
### Prerequisites

- [x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)

Related issues/proposals:
#419 
#700
cybertk/abao#203

### Description

Breakdown of test timing should add setup/teardown pseudo-tests to help give better individual test timings. Timing of `before()` functions would be added to the "setup" pseudo-test, and `after()` functions to the "teardown" pseudo-test of each `describe()`.

Timing of `beforeEach()/afterEach()` would remain with each `it()`.

Reporters would display these as two additional tests named "setup" and "teardown", assuming they exceeded some threshold.

### Rationale

When using Mocha tests to perform RESTful interface testing against a resource, timing of a database setup routine in a `before()` would be added to the first test -- making its performance look terrible. When running API tests, the timing of the routine can be almost as important as it passing.

**Comment by eight04** [comment] 2019-05-28 12:12
I think it will be better to provide a way to access the timing API or a "pseudo it" that will record the timing. Currently, I have a test file like this:
```js
describe("test cases", () => {
  for (const case of cases) {
    it(case.name, () => {
      const input = fs.readFileSync(case.inputFile);
      const output = doSomething(input);
      const expectedOutput = fs.readFileSync(case.outputFile);
      assert.equal(output, expectedOutput);
    });
  }
});
```
The problem is that setup, assert, and teardown phases are all counted in the timing. What I really care is the calculation time i.e. `doSomething(input)`. Currently, I can use a workaround like:
```js
describe("test cases", () => {
  for (const case of cases) {
    describe(case.name, () => {
      let input, expectedOutput;
      before(() => {
        input = fs.readFileSync(case.inputFile);
        expectedOutput = fs.readFileSync(case.outputFile);
      });
      it("run", () => {
        const output = doSomething(input);
        assert.equal(output, expectedOutput);
      });
    });
  }
});
```
With a timing API, we can simplify this to:
```js
describe("test cases", () => {
  for (const case of cases) {
    it(case.name, function () {
      const input = fs.readFileSync(case.inputFile);
      const expectedOutput = fs.readFileSync(case.outputFile);
      
      this.timeStart();
      const output = doSomething(input);
      this.timeEnd();
      
      assert.equal(output, expectedOutput);
    });
  }
});
```
Or, with a "pseudo it":
```js
describe("test cases", () => {
  for (const case of cases) {
    it(case.name, function () {
      const input = fs.readFileSync(case.inputFile);
      const expectedOutput = fs.readFileSync(case.outputFile);
      let output;
      
      timeMe(() => {
        output = doSomething(input);
      });
      
      assert.equal(output, expectedOutput);
    });
  }
});
```
The API should accept an optional label in case that the user want to record multiple time-span e.g. setup time:
```js
this.timeStart("setup");
// ...
this.timeEnd("setup");
this.timeStart();
// ...
this.timeEnd();

// or

timeMe("setup", () => {...});
timeMe(() => {...});
```

**Comment by plroebuck** [comment] 2019-05-28 14:23
The concept was to add the timing information for each test to the `stats` object automatically; there is no API.

**Comment by JoshuaKGoldberg** [comment] 2024-02-06 04:42
This issue has had exactly two people interact with it since it was filed in 2019. That's less than one every two years. Per #5027, we're trying to stay away from changes that don't have broad appeal. Closing as wontfix.

But, if anybody thinks I'm wrong here, please do file a new issue with one of our new issue templates. They'll prompt for the supporting info that would help us triage this higher. 

Cheers, all!

**Closed by JoshuaKGoldberg** 2024-02-06 04:42 UTC
Labels: type: feature, area: usability
