### ISSUE TITLE
Combine mocha tests programmatically

### ISSUE THREAD

**Issue by cyberjoac** [mochajs/mocha#2304] opened 2016-06-10 13:30 UTC
I'm trying to combine mocha tests in a programmatic way with (so that I can pass arguments between tests).

But the tests don't get detected by Mocha if they're not there at the beginning of the run.

This is the code I got to so far:

```
for (var i = 0; i < buildingBlocks.length; i++) {
        (function (index) {
            var buildingBlock = buildingBlocks[index];
            it(buildingBlock.getDescription(), function (done) {
                var executeCallback = function (err, args) {
                    done();
                    console.log("after done");
                    function(index+1)(args);
                };
                args.push(executeCallback);
                buildingBlocks[index].execute.apply(null, args);

            })
        })(i);
    }
```

Thanks a lot for your help.

**Comment by ScottFreeCode** [comment] 2016-06-10 20:55
You can define Mocha tests programmatically, but to do it asynchronously you need to use the `--delay` option and call `run()` in the asynchronous code after it defines the tests.

By design, you can't call tests from other tests (and shouldn't need to, but hold that thought -- I'll get to why that is in a moment) -- even if you did find a way to do something very similar, Mocha would view whatever chain of functions you call from each test it runs as being part of that test, not new tests.

You can, *if it's appropriate*, test code that requires one function to call another to call another etc., or feeding results from one function into the arguments for the next and so on, *all as a single test*, provided the last callback is what calls `done` (assuming the code under test involves asynchronous callbacks; if it doesn't, you don't even need `done`). With asynchronous functions a more natural way to do this could be to use a promise with chained `then` calls, either not taking a `done` parameter and instead returning the promise (in which case Mocha will check whether it ends up erroring or completing successfully) or else ending in `.then(done, done)` (this will either call `done()` if there has been no error or else pass `done` any error that occurred anywhere along the chain). However, be aware that in any case such chains of functionality under test would only be appropriate in integration or end-to-end testing; for unit-testing you'd want to test each of the functions individually with whatever types of input it's supposed to take and output it's supposed to produce.

To circle back a bit (and I apologize if this seems a bit philosophical, but I did say I'd get to the design matter), passing arguments between tests isn't a good idea -- for unit tests the whole point is to test the units in isolation (thus, not depending on stuff coming out of other pieces), whereas for integration or end-to-end tests each set of operations (comprising one higher level action or condition to test) with steps that do depend on the prior steps in the same set should just be one test per set. ...At least, I think that's the idea anyway.

**Comment by boneskull** [comment] 2016-06-27 06:27
what @ScottFreeCode said.  I'm going to close this

**Closed by boneskull** 2016-06-27 06:27 UTC

**Comment by cyberjoac** [comment] 2016-07-10 06:58
Thanks a lot for your clear explanations !
