### ISSUE TITLE
this.timeout in before ignored?

### ISSUE THREAD

**Issue by stevenvachon** [mochajs/mocha#1501] opened 2015-01-15 03:46 UTC
```js
describe("something", function() {
    beforeEach( function(){ this.timeout(0) });
    it("should keep going", function(done) {
        // "Error: timeout of 2000ms exceeded"
    });
});
```
And this just kills the whole test:
```js
describe("something", function() {
    this.timeout(0);
    it("should keep going", function(done) {
        // exits program.. no exit code given
    });
});
```

**Comment by stevenvachon** [comment] 2015-01-19 20:13
It's working fine today. I guess it's just my machine acting up (?)

**Comment by hallas** [comment] 2015-01-19 20:35
@stevenvachon Come back tomorrow. If the problem is still gone, please close the issue and comment. Bookmark and return an re-open if you see it again.

**Comment by dasilvacontin** [comment] 2015-02-01 02:52
I'll close this. Re-open if needed.

**Closed by dasilvacontin** 2015-02-01 02:52 UTC
Labels: Unconfirmed
