### ISSUE TITLE
npm WARN deprecated graceful-fs

### ISSUE THREAD

**Issue by efortes** [mochajs/mocha#2262] opened 2016-05-17 08:47 UTC
I get the following error: 

> npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.

Tree:

> ├─┬ mocha@2.4.5
│ └─┬ glob@3.2.3
│   └── graceful-fs@2.0.3

**Comment by gagern** [comment] 2016-05-17 10:41
Sounds similar to #2200 (the warning about jade) except that not supporting node 7 feels somewhat more serious than just a warning due to some package name change, at least in the long run. Current glob is using caret [dependencies](https://github.com/isaacs/node-glob/blob/68f2509d237babec64cf03adf72531127fd80339/package.json#L19-L25) as well, so it will probably be *really* hard to get a single version of mocha to support node 0.8 through 7.0.

**Comment by ScottFreeCode** [comment] 2016-05-17 14:01
Glob 3.2.11 actually is compatible and doesn't have the graceful-fs dependency, so it should work on 0.8 through 7, as far as I can tell at this point; this was already updated by #2201 and will go out in the next release. Until then, at least it's actually not an error but just a warning; even updating to Node 7 [might not break it if you're not getting any warnings other than the one on install](2234#issuecomment-217071801).

**Comment by jakereps** [comment] 2016-05-17 19:12
Node v6 & npm v3.8.6 really do not like this. After any command ran through NPM, whatsoever, it floods the screen with warnings because of the graceful-fs@2.0.3 dependency of glob on mocha. Definitely +1ing the usage of an updated glob.

![screen shot 2016-05-17 at 12 06 30 pm](https://cloud.githubusercontent.com/assets/2638727/15335591/d0981fb0-1c27-11e6-9da5-8cfe8779d6c7.png)

**Comment by ScottFreeCode** [comment] 2016-05-17 22:54
Wow, I've never seen it dump the fs re-evaluation warning like that before. There might be a good test case in there.

**Comment by efortes** [comment] 2016-05-18 10:32
Thanks for the replies. I will wait for the update. 
Manually going into the mocha node_modules folder is not a good idea as i don't want to touch external modules.

**Comment by boneskull** [comment] 2016-05-22 00:03
dupe of #2234 basically

**Closed by boneskull** 2016-05-22 00:03 UTC
