### ISSUE TITLE
How to use mjs module in mocha?

### ISSUE THREAD

**Issue by wnghdcjfe** [mochajs/mocha#4313] opened 2020-06-05 07:25 UTC
I try to use mocha like this for this reference
https://mochajs.org/#nodejs-native-esm-support
### main.mjs
```js
import {add} from './add.mjs';
import assert from 'assert';

it('should add to numbers from an es module', () => {
  assert.equal(add(3, 5), 8);
});
```
### add.mjs
```js
export function add(a, b){
    return a + b; 
} 
```

## command
```
mocha main.js --experimental-modules
mocha main.js --extension mjs
```
But both of them is not working

I also found the npm link
https://www.npmjs.com/package/mjs-mocha
But Can't Mocha just alone do that?
## version
 - mocha : v7.2.0
 - node : v10.15.1

**Comment by juergba** [comment] 2020-06-05 07:35
> Mocha supports ES modules only from Node.js v12.11.0 and above. To enable this in versions smaller than 13.2.0, you need to add --experimental-modules when running Mocha. From version 13.2.0 of Node.js, you can use ES modules without any flags.

**Comment by juergba** [comment] 2020-06-06 04:29
duplicate of #4297

**Closed by juergba** 2020-06-06 04:29 UTC
Labels: question

**Comment by wnghdcjfe** [comment] 2020-06-07 01:42
Thanks a lot @juergba. Have nice a day

**Comment by meszaros-lajos-gyorgy** [comment] 2020-06-13 14:06
For anyone googleing why `--watch` is not working with mjs files, the docs state, that this is a known limitation: https://github.com/mochajs/mocha/blob/master/docs/index.md#current-limitations

> Watch mode does not support ES Module test files

One possible workaround is to use `nodemon` and it's `--exec` flag:

```
"scripts": {
  "unit": "mocha --experimental-modules --no-warnings test/**/*.spec.mjs",
  "unit:watch": "nodemon --exec \"npm run unit\" --watch test/**/*.spec.mjs",
}
```
