### ISSUE TITLE
Update glob dependency 

### ISSUE THREAD

**Issue by denysvitali** [mochajs/mocha#2180] opened 2016-04-01 07:46 UTC
mocha still depends on glob@3.2.3 when the version 7.0.3 is out
Having mocha to depend on glob@3.2.3 means that graceful-fs is still at version 2.0.3, so the following warning is shown:
`npm WARN deprecated graceful-fs@2.0.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.`

**Comment by danielstjules** [comment] 2016-04-01 08:37
Thanks! Closing as duplicate of https://github.com/mochajs/mocha/issues/2121

**Closed by danielstjules** 2016-04-01 08:37 UTC
