### ISSUE TITLE
Regression: Failures rendering twice

### ISSUE THREAD

**Issue by ahamid** [mochajs/mocha#2083] opened 2016-01-29 03:00 UTC
I just happened to start up a simple hello world mocha test project (to test something else :) ), and I noticed that versions >= 2.4 now double-render the failure in my example.  Reverting to 2.3.3 makes the behavior go away.  I will try to get to the bottom of it, but I see several releases in the last few days so I thought maybe you'd want to know.

https://github.com/ahamid/mocha-phantomjs-blanket/tree/mocha-failure-double-render

![double-render-failure](https://cloud.githubusercontent.com/assets/77031/12666004/7d77283a-c60a-11e5-9377-10e00da863fe.png)

**Comment by ahamid** [comment] 2016-01-29 03:22
It might be this commit: ae4fbca3e19049cd18d676e865c844fbc890e14c

The HTML reporter is now emitting another `'test end'` event on any test failure, which I believe causes the result to be printed twice (since it's rendered on 'test end').  That's my hunch anyway.

**Comment by ahamid** [comment] 2016-01-29 03:28
Commenting this line has the same effect: https://github.com/mochajs/mocha/blob/v2.4.5/lib/runner.js#L551

Both avoid `'test end'` being emitted twice.

**Comment by danielstjules** [comment] 2016-01-29 04:13
Thanks for letting us know! Looks like not all exceptions are emitted twice - likely why it was missed.

**Comment by danielstjules** [comment] 2016-01-29 04:38
I'm more inclined to just revert the PR: https://github.com/mochajs/mocha/pull/1981

**Comment by boneskull** [comment] 2016-01-29 05:57
the fix may be as simple as checking if the test has already failed in the callback there.

**Comment by danielstjules** [comment] 2016-01-29 06:18
@boneskull As in?
``` diff
diff --git a/lib/reporters/html.js b/lib/reporters/html.js
index 7da2508..6366542 100644
--- a/lib/reporters/html.js
+++ b/lib/reporters/html.js
@@ -131,8 +131,8 @@ function HTML(runner) {
   runner.on('fail', function(test) {
     // For type = 'test' its possible that the test failed due to multiple
     // done() calls. So report the issue here.
-    if (test.type === 'hook'
-      || test.type === 'test') {
+    if (test.type === 'hook' ||
+        (test.type === 'test' && test.state !== 'failed')) {
       runner.emit('test end', test);
     }
   });
```

While it prevents double errors, it suppresses any error messages dealing with async errors after a test passed, or multiple calls to done.

**Comment by boneskull** [comment] 2016-01-29 06:21
[here](https://github.com/mochajs/mocha/blob/v2.4.5/lib/runner.js#L534)

just an idea

**Comment by ohnnyj** [comment] 2016-02-06 01:47
Hello all.

I am by no means an expert with the mocha code base but here is just a thought.

Can we mark the test as being ended something like:

```javascript
    if (test.type === 'hook'
      || test.type === 'test') {
      test.didEnd = true;
      runner.emit('test end', test);
    }
```

Then in `runTest` callback:

`!test.didEnd && self.emit('test end', test);`

**Comment by mckoss** [comment] 2016-02-12 23:18
I'm seeing this too - pretty annoying.  Please revert #1981.

**Comment by Standard8** [comment] 2016-02-15 08:13
I only got notified of this issue a couple of days ago. I would like to ask that we don't revert PR 1981 - that causes other types of failures to be completely hidden from view, and cost a lot of time in debugging an issue.

Having thought about the code a bit more, I think the solution here might be to change the HTML reporter, and rather than listening to `test end`, make it listen to `pass`. We'll probably also have to make it listen to `pending`.

I think that would most likely correctly handle the failure cases.

I'm not sure if I'll get time to try this today, but should do tomorrow unless anyone beats me to it.

**Comment by mckoss** [comment] 2016-02-16 05:23
I think it's pretty clear, that no test should emit more than one 'test end' event.  This change (#1981) is a regression in that it does just that in the most basic synchronous test case.  There needs to be some test state that ensures that this invariant is maintained.

**Comment by boneskull** [comment] 2016-02-16 05:51
@Standard8 @mckoss  @ahamid 

thanks for bringing this to our attention.  sorry about the slow response.

I *believe* a simple memoization of the `test end` listener ([code](https://github.com/mochajs/mocha/blob/master/lib/reporters/html.js#L140)) in the HTML reporter would address this, e.g.:

```js
var memoize = require('lodash/memoize');
runner.on('test end', memoize(function(test) {
  // etc
});
```

Note that we don't have `lodash` as a dependency, and can't add it right now, so the possibilities include:

- find some other (small) memoization module which is compatible w/ Node.js 0.8.x out of the box
- do it manually by tossing `Test` objects into an `Array` and checking if the test is already in there; if so, just `return` (slow)
- toss `Test` objects into an object instead (faster; but you need a key)

To support an object-based lookup (which we should), you'll need a unique (`string`) identifier.  The problem is `Test` objects don't currently *have* a unique identifier.  Unless we give it one (perhaps an `id` prop), I can't think of anything we could potentially use--no temporal data is kept in the `Test` object other than `duration`, which is not necessarily unique when combined with `title`.  

So I'd recommend just adding an `id` prop to each `Test` object in `lib/test.js`.  An auto-incrementing integer is fine.  Then we can use it in this manner (assuming we don't end up doing it manually):

```js
var memoize = require('lodash/memoize');
runner.on('test end', memoize(function(test) {
  // etc
}, function resolver(test) {
  return test.id;
});
```

To ensure v0.8.x compatibility (if adding a 3p module), do something like this:

```shell
$ cd /tmp
$ nvm install 0.8
$ npm install /path/to/my/working/copy/of/mocha
```

If that fails, then whatever package you added won't work (you may need to try an older version of it?).

Would happily accept a PR!

**Comment by boneskull** [comment] 2016-02-16 05:58
(also, if you can find another sane way to fix it, that's great too)

**Comment by danielstjules** [comment] 2016-02-16 07:35
https://github.com/mochajs/mocha/issues/2083#issuecomment-176599271 won't work because that line doesn't actually see the test twice. Memoization would def work, though I'm hoping we can come up with an alternative.

**Comment by danielstjules** [comment] 2016-02-16 08:19
> no test should emit more than one 'test end' event.

True, though we shouldn't rely on the `test end` event at all since a test can succeed, then later emit async errors resulting in subsequent failures. Updating the HTML reporter to listen to the `pass|fail|pending` events like the other reporters would probably help.

**Comment by mckoss** [comment] 2016-02-17 00:10
I thought it already did listen to pass/fail/pending - but injects the HTML
at 'test end' time.


+Mike Koss <https://plus.google.com/+MikeKoss/posts>
(425) 246-7701 (m)

On Tue, Feb 16, 2016 at 12:19 AM, Daniel St. Jules <notifications@github.com

**Comment by danielstjules** [comment] 2016-02-17 00:53
> I thought it already did listen to pass/fail/pending - but injects the HTML
> at 'test end' time.

If that were the case, https://github.com/mochajs/mocha/pull/1981/files wouldn't have been required. We need to handle specs that fail after having already ended. For example:

``` javascript
it('test', function(done) {
  setTimeout(done, 1000);
  setTimeout(done, 1100);
});

// Events:
// - pass
// - test end
// - fail
```

I've opened a PR that fixes this.

**Comment by chemzqm** [comment] 2016-04-10 07:46
Issus exists with latest mocha 2.4.5, pleeeeease fix this.

**Comment by Standard8** [comment] 2016-04-11 10:03
It looks like a fix is in progress in PR #2112 but has currently stalled.

**Comment by maciejjankowski** [comment] 2016-05-18 13:20
Somebody, please. What happened to PR #2112 ?

**Closed** 2016-05-25 07:57 UTC
Labels: Browser, Bug, PR PLEASE

**Comment by Standard8** [comment] 2016-05-25 09:41
@danielstjules thank you for fixing this! Sorry that I caused it in the first place.
