### ISSUE TITLE
add coverage to CI; use a coverage service

### ISSUE THREAD

**Issue by boneskull** [mochajs/mocha#2620] opened 2016-12-02 08:41 UTC
[nyc](https://npmjs.com/nyc) is appropriate for Node.js coverage with all the process forking we need to do; [karma-coverage](https://npmjs.com/karma-coverage) probably fine for browser.

Coveralls.io is straightforward.  Code Climate is probably going to have more info.  Codacy is another one.  There are a [ton of these things](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis).  Anybody have a favorite?

**Comment by pgoldrbx** [comment] 2017-01-16 19:05
+1 for `nyc` and `karma-coverage` (though combining the output [might still have some issues](https://github.com/karma-runner/karma-coverage/issues/1) due to file paths in karma)

From experience, Coveralls is nice in that you'll get per-branch/PR coverage information, versus Code Climate which currently only shows reports on the default branch. I have no experience with Codacy. It might not matter too much which you choose to start as anything is better than nothing, but being able to matter coverage changes on PRs is a pretty important OSS concern.

**Comment by coderbyheart** [comment] 2017-01-17 08:56
Seems like a duplicate of #2351

**Closed** 2017-01-17 22:39 UTC
Labels: qa
