### ISSUE TITLE
test.only is not working if code is loading after mocha.run()

### ISSUE THREAD

**Issue by TheLevenCreations** [mochajs/mocha#2077] opened 2016-01-27 14:30 UTC
Hi, I am a newbie to use Mocha and I think it is a really really cool tool to test my javascript code. Thanks for creating such great tool.

However, I met some problem to test my AMD module code. See the following. Please let me know if it is worked as designed.

Currently, I am using mocha delay method to test AMD modules. However, I just found the test.only is not  working. My way is:
1. Use node(or electron) to start a thread to load bin/_mocha javascript file.
2. bin/_mocha will find the test/mocha.opts file and load it, then run the tests specified in opts. (--delay is specified in opts)
3. Actually, there is only one TestsLoader.test.js in opts. That file is to load the AMD scripts and when the loading is done, fire run() method provided by mocha

It works well until I found test.only won't work, while test.only works well in browser mode.

After some investigation, I found probably it is a design issue. The runner instance is started when mocha.run() is fired, and the options.grep is stored in runner immediately. See the following code I grabbed from mocha.js. As a result, whiling loading AMD modules after mocha.run() is fired and before run() is issued, the test.only will change the mocha.options.grep, but it won't change the runner's grep. As a result, when the run() and then runner.runTests() is issued, the grep is not working.

``` javascript
/**
 * Run tests and invoke `fn()` when complete.
 *
 * @api public
 * @param {Function} fn
 * @return {Runner}
 */
Mocha.prototype.run = function(fn) {
  if (this.files.length) {
    this.loadFiles();
  }
  var suite = this.suite;
  var options = this.options;
  options.files = this.files;
  var runner = new exports.Runner(suite, options.delay);
  var reporter = new this._reporter(runner, options);
  runner.ignoreLeaks = options.ignoreLeaks !== false;
  runner.fullStackTrace = options.fullStackTrace;
  runner.asyncOnly = options.asyncOnly;
  runner.allowUncaught = options.allowUncaught;
  if (options.grep) {
    runner.grep(options.grep, options.invert);
  }
  if (options.globals) {
    runner.globals(options.globals);
  }
  if (options.growl) {
    this._growl(runner, reporter);
  }
  if (options.useColors !== undefined) {
    exports.reporters.Base.useColors = options.useColors;
  }
  exports.reporters.Base.inlineDiffs = options.useInlineDiffs;

  function done(failures) {
    if (reporter.done) {
      reporter.done(failures, fn);
    } else {
      fn && fn(failures);
    }
  }

  return runner.run(done);
};

```

I just think it would be better to let runner to read mocha.options.grep rather than reading a temp value stored.

My current workaround is to rewrite the _mocha file and:
1. register mocha, suite, test as global value
2. to load the AMD scripts, set delay mode =false
3. fire mocha.run()

Please let me know I am doing towards the right direction. Thanks :)

**Comment by boneskull** [comment] 2016-01-27 15:53
using globals is kind of heavy-handed to fix this, but if it works for you, then that's good. 

would accept a PR to fix this.

**Comment by ScottFreeCode** [comment] 2016-06-11 16:12
Rather than having `Runner` use `mocha.options.grep`, what about having `Mocha.prototype.run` save `this._runner`* instead of a local `runner` variable and `Mocha.prototype.grep` call `this._runner.grep` in addition to assigning `this.options.grep`? This keeps `Runner` agnostic to `Mocha`/`mocha` (`Mocha` already "knows about" `Runner`, so we're not adding any coupling there), only affects the case we're trying to fix (e.g. doesn't affect anything using `Runner` and/or its `grep` command directly, if there is any such code), and is about as trivial to implement as the most naive and potentially problematic implementation of the "`Runner` use `mocha.options.grep`" alternative.

*This isn't strictly private, but marked as intended to be private by the underscore variable name convention, which other Mocha internal variables already are too.

**Comment by boneskull** [comment] 2016-06-21 04:19
@ScottFreeCode Sounds reasonable

**Comment by ScottFreeCode** [comment] 2017-10-18 07:28
This is a duplicate of #1838, right?

**Comment by JoshuaKGoldberg** [comment] 2023-12-27 06:00
Looks like it! This issue also hasn't been interacted with in quite a while.

**Closed by JoshuaKGoldberg** 2023-12-27 06:00 UTC
Labels: type: bug, status: accepting prs
