### ISSUE TITLE
Console logging gets extremely mixed up after a retry

### ISSUE THREAD

**Issue by brubakbd** [mochajs/mocha#2395] opened 2016-07-26 13:04 UTC
I'm running a very long test suite that sends many requests to our API, so it's nice to be able to log what request I'm sending and what the response is for debugging purposes if a test fails. All goes well if I don't allow retries. Everything stays in order and everything gets printed. However, if I turn on any retrying using this.retries(1) the logging is fine until it hits a retry. Then it starts getting really weird. It continues logging most(some of the console.log statements appear to never be printed), but it puts some out of order and no longer splits into the separate suites. It begins printing everything into one suite until it randomly moves on to the next and is completely out of order. In addition, it doesn't actually print the error that caused the retry until ~3 tests after it happened.
My best guess as to what is causing this is that it has something to do with using promises and/or a setTimeout function in the area that gets retried.

**Comment by boneskull** [comment] 2016-07-27 03:27
@brubakbd Can you provide an example suite that will reproduce this?

**Comment by brubakbd** [comment] 2016-07-27 12:36
```
require('mocha');
var variables = require('./../variables.js');
var rules = require('./../rules.js');
var async = require('async');


describe("overall suite", function(){
    this.retries(2);
    it("test one",function(){
        console.log("test one-1");
        console.log("test one-2");
        return new Promise(function(resolve, reject){
            setTimeout(function(){
                resolve("Test one promise response")
            },1000);
        })
            .then(function(resp){
                console.log(resp);
                console.log("Finished test one");
            });
    });
    it("test two",function(){
        console.log("test two-1");
        console.log("test two-2");
        return new Promise(function(resolve, reject){
            setTimeout(function(){
                resolve("Test two promise response")
            },1000);
        })
            .then(function(resp){
                console.log(resp);
                console.log("Finished test two");
            });
    });
    var i = 0;

    it("test three",function(){
        console.log("test three-1");
        console.log("test three-2");
        return new Promise(function(resolve, reject){
            setTimeout(function(){
                if(i===2)
                    resolve("Test three promise response")
                else{
                    reject("i = "+i);
                }
            },1000);
        })
            .then(function(resp){
                console.log(resp);
                console.log("Finished test three");
            });
    });

    it("test four",function(){
        console.log("test four-1");
        console.log("test four-2");
        return new Promise(function(resolve, reject){
            setTimeout(function(){
                resolve("Test four promise response")
            },1000);
        })
            .then(function(resp){
                console.log(resp);
                console.log("Finished test four");
            });
    });

    it("test five",function(){
        console.log("test five-1");
        console.log("test five-2");
        return new Promise(function(resolve, reject){
            setTimeout(function(){
                resolve("Test five promise response")
            },1000);
        })
            .then(function(resp){
                console.log(resp);
                console.log("Finished test five");
            });
    });
});
```

When looking at the console log for test one I see: 
```
test one-1
test one-2
Test one promise response
Finished test one
```

Test two:
```
test two-1
test two-2
Test two promise response
Finished test two
```

First attempt of test three:
```
test three-1
test three-2test three-1
test three-2test three-1
test three-2test four-1
test four-2
Test four promise response
Finished test fourtest five-1
test five-2
Test five promise response
Finished test five
Process finished with exit code 1
```

Test four has nothing

Test five has nothing

Second iteration of test three has nothing

3rd iteration of test tree that fails:
```
Error: the string "i = 0" was thrown, throw an Error :)
```

Also, should the test three retries be running at the end? It appears that it fails once, then goes to four and five, then comes back to three for the retries. I couldn't find any documentation on what Mocha's retry is supposed to do.

**Comment by boneskull** [comment] 2017-10-17 17:23
someone should review this

**Comment by Bamieh** [comment] 2018-09-04 08:39
Closing this as I am unable to reproduce with the latest mocha, feel free to re-open if this issue persists.

**Closed by Bamieh** 2018-09-04 08:39 UTC
Labels: unconfirmed-bug
