### ISSUE TITLE
Html reporter displays duplicate results

### ISSUE THREAD

**Issue by npbenjohnson** [mochajs/mocha#2222] opened 2016-04-25 23:33 UTC
Html reporter re-emits 'test-end' for some reason on failure, so the event gets reported once by the runner, and once by the reporter, duplicating the results.

inside html reporter:
```js
  runner.on('fail', function(test) {
    // For type = 'test' its possible that the test failed due to multiple
    // done() calls. So report the issue here.
    if (test.type === 'hook'
      || test.type === 'test') {
      runner.emit('test end', test);
    }
  });
```

**Comment by yefim** [comment] 2016-04-26 01:15
There's a PR out to fix it: https://github.com/mochajs/mocha/pull/2112

**Comment by danielstjules** [comment] 2016-04-27 08:08
Yup, this is a duplicate of https://github.com/mochajs/mocha/issues/2083 Sorry, it should be merged in the near future!

**Closed by danielstjules** 2016-04-27 08:08 UTC
