### ISSUE TITLE
Output in Chrome console includes "stdout:"-prefixed lines

### ISSUE THREAD

**Issue by mattflix** [mochajs/mocha#2095] opened 2016-02-06 05:16 UTC
Mocha 2.4.5
Chrome 48.0.2564.103

Pretty much with any reporter I use, Mocha outputs the following poorly-formatted text to the browser console.

Note the weird "stdout:"-prefixed lines.

```
  Foo
     #bar
 stdout: [2K
       1) should work
       ✓ should still work
   1 passing (770ms)
   1 failing
   1) Foo #bar should work:
     Error: oops
      at Context.shouldWork (test/test.js!transpiled:11:35)

 stdout: [0G
 stdout: [2K
 stdout: [0G
```

This seem to be the result of code in most reporters using a combination of calls to console.log() and process.stdout.write().  In the browser, process.stdout is ultimately implemented as calls to the console with "stdout:" prefixed in front on each line (not really sure why, just something BrowserStdout does) which is often just a cursor movement escape code (which, in many cases, like above, really contributes nothing to the final formatting).

So, this just doesn't work well, eh?  Can something be done to make reporter output look better in the browser?  Mocha is advertised as working "in the browser"   ...but it doesn't really.

**Comment by ebbe-brandstrup** [comment] 2016-05-22 12:08
I'm getting the same. It is _really_ spamming the output.

**Comment by skeggse** [comment] 2016-07-13 20:24
This will be partially resolved by #2373, but there will still be a bunch of lines (albeit blank lines) in the output. This is due to the choice of `browser-stdout` for `process.stdout` in the browser. The module is problematic for mocha's uses for two reasons:

- it buffers output, and some of the code just uses `console.log`, so the output isn't interleaved as intended
- it outputs each chunk as a new line, so there are many more newlines than there should be

**Comment by boneskull** [comment] 2016-07-25 17:20
@skeggse I don't know why `browser-stdout` is required.  Is there an alternative?

**Comment by boneskull** [comment] 2016-07-25 17:20
I'm going to call this a "bug".

**Comment by boneskull** [comment] 2016-07-25 17:23
> So, this just doesn't work well, eh? Can something be done to make reporter output look better in the browser? Mocha is advertised as working "in the browser" ...but it doesn't really.

The "intended" browser reporter is the HTML reporter, and it's no work of art, but it's decent. 😏

**Comment by skeggse** [comment] 2016-08-12 19:58
@boneskull I didn't find a good alternative. A real alternative would overwrite the global `console` methods, and add a global `process` shim.

**Comment by mattflix** [comment] 2016-08-12 20:01
Isn't the alternative to log everything via the same conduit?  Right now, the hodge-podge of calls to console.log() and BrowserStdout (delayed on timers) is what is causing the mess in the browser console.

**Comment by skeggse** [comment] 2016-08-12 20:03
Correct, everything could go out through `process.stdout`. Alternatively, we could add a buffer mechanism to mocha to buffer partial lines.

**Comment by plroebuck** [comment] 2018-10-20 07:57
PR #2373 had a bug which left the `stdout: ` prefix intact.
PR #3477 corrects that problem.

My tests confirm that the prefix is gone afterwards. But I find **no** evidence of terminal control codes in `spec` reporter output. Obviously, some reporters (`nyan`, `landing`, etc.) are lost causes for the browser console.

Plan to close this (again, for good) when #3477 is merged.
If you still experience the terminal control code spew problem, open a new issue.

**Comment by outsideris** [comment] 2018-10-20 20:45
close by #3477

**Closed by outsideris** 2018-10-20 20:45 UTC
Labels: confirmed-bug, needs-feedback
