### ISSUE TITLE
make test timeouts closer to reality

### ISSUE THREAD

**Issue by boneskull** [mochajs/mocha#2597] opened 2016-11-24 09:23 UTC
Many tests in our suite regularly output "slowness" warnings:

![image](https://cloud.githubusercontent.com/assets/924465/20592829/7eda1df6-b1e4-11e6-8555-a32dee0de34e.png)

Let's increase the `--timeout` and/or `--slow` setting so the information it produces is actually helpful.

**Comment by ScottFreeCode** [comment] 2017-08-25 21:47
Seems like this and #2837 are duplicate of each other?

**Comment by juergba** [comment] 2020-02-10 12:36
closing, see #3539.

**Closed by juergba** 2020-02-10 12:36 UTC
Labels: chore, help wanted, qa
