### ISSUE TITLE
Can not import Mocha as a native ES6 module in a browser

### ISSUE THREAD

**Issue by vitalets** [mochajs/mocha#3139] opened 2017-12-09 11:29 UTC
### Prerequisites
* [ x] Checked that your issue isn't already filed by cross referencing [issues with the `common mistake` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Acommon-mistake%20)
* [x ] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
* [ x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
* [ x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with:
`node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend avoiding the use of globally installed Mocha.

### Description
Can not import Mocha as a native ES6 module in a browser (Chrome 62). I tried several variant with `import` statement but with no success:
```js
import 'https://unpkg.com/mocha@4.0.1/mocha.js';
// or 
import mocha from 'https://unpkg.com/mocha@4.0.1/mocha.js';
// or 
import mocha from 'https://unpkg.com/mocha@4.0.1/index.js';
```

### Steps to Reproduce
See jsFiddle: https://jsfiddle.net/Lph8mrbe/2/

**Expected behavior:**
Mocha will be loaded into global context without errors.

**Actual behavior:**
Error: 
```
mocha.js:1 Uncaught ReferenceError: require is not defined at mocha.js:1
```

**Reproduces how often:**
Always

### Versions
4.0.1

**Comment by ScottFreeCode** [comment] 2017-12-10 23:39
Sounds like it's caused by the same thing as #3091?

**Comment by boneskull** [comment] 2017-12-12 07:50
duplicate of #3091

**Closed by boneskull** 2017-12-12 07:50 UTC

**Comment by boneskull** [comment] 2017-12-12 20:56
@vitalets please pull down PR #3145 to test a fix

**Comment by vitalets** [comment] 2017-12-13 14:52
> @vitalets please pull down PR #3145 to test a fix

@boneskull I've checked -  importing Mocha a ES module works for `mocha.js` in this PR.
