### ISSUE TITLE
Mocha shows error in inner `before` function as error for outer `it`

### ISSUE THREAD

**Issue by okachynskyy** [mochajs/mocha#3291] opened 2018-03-23 14:27 UTC
### Prerequisites

- [x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend avoiding the use of globally installed Mocha.

### Description

Mocha shows error in inner `before` function as error for outer `it`, but this outer `it` passed successfully.

### Steps to Reproduce
```
describe('Top-level describe', () => {

  it('Top-level it', () => { });

  describe('Nested describe', () => {
    before(() => {
      throw new Error();
    });

    it('Nested it', () => { });
  });
});
```

**Expected behavior:** Info about error in inner `before` statement for `Nested describe`

**Actual behavior:** Mocha shows this error: 
```
  Top-level describe
    ✓ Top-level it
    Nested describe
      1) "before all" hook for "Top-level it"
```

**Reproduces how often:** always

### Versions

- The output of `mocha --version`  - not installed 
- `node node_modules/.bin/mocha --version`: 5.0.5
- The output of `node --version`: v8.10.0
- The version and architecture of your operating system: Ubuntu 16.04 LTS 64 bit
- Your shell (bash, zsh, PowerShell, cmd, etc.): bash

**Comment by boneskull** [comment] 2018-03-23 17:19
This is *not* a regression introduced with v5.0.5.

**Comment by plroebuck** [comment] 2018-04-20 19:03
Looks like it is displayed in the correct location in output (`Nested describe`), but with incorrect  test title given internally [`test.parent.fullTitle()`, I think].

**Comment by jdmarshall** [comment] 2018-05-10 00:02
Duplicate of #2134 but your test case is simpler.

**Comment by juergba** [comment] 2018-11-07 18:56
First of all `before` hooks can be declared incl. a title: `Suite.prototype.beforeAll = function(title, fn)` 
Passing a clear description should clear any confusion. In case of an undefined title, we could fix a default value, f.e. the parent's title.

Which title should be used? The one of the parent `describe`, or the one of the next `test` which hasn't been reached yet? The first option is probably easier to obtain, in plain (not nested) tests it would be "for root".

In the context `ctx` of hook what is the difference between `test` and `currentTest`? In above example the `currentTest` is responsible for the incorrect test title, it still points to the outer test. I guess `currentTest` should be undefined since there is no test yet (later as next step)?

**Comment by juergba** [comment] 2018-11-08 10:35
The content of `hook.ctx.currentTest` doesn't seem reliable to me.
1. `before` / `beforeEach`: it should be undefined, but points to the latest completed test (parent suite).
2. `afterEach`: it seems ok to me.
3. `after`: is undefined, but should point to ...? To the latest completed test within the current suite or to the current suite itself?

For now I want to fix the first item. --> runner.js, 289ff
```
Runner.prototype.hook = function(name, fn) {
...
  function next(i) {
      var hook = hooks[i];
      if (!hook) {
        return fn();
      }
      self.currentRunnable = hook;
      if (name !== 'beforeAll' && name !== 'beforeEach') {    //new
          hook.ctx.currentTest = self.test;
      }    //new

**Comment by juergba** [comment] 2018-11-08 14:17
When no `currentTest` is available, I use the hook's parent title. --> runner.js, 271ff
```
Runner.prototype.failHook = function(hook, err) {
  if (hook.ctx && hook.ctx.currentTest) {
    hook.originalTitle = hook.originalTitle || hook.title;
    hook.title =
      hook.originalTitle + ' for "' + hook.ctx.currentTest.title + '"';
 } else {                                         //new
    var parent = hook.parent.title || 'root';     //new
    hook.title += ' for "' + parent + '"';        //new
 }
```
```
 Top-level describe
    √ Top-level it
    Nested describe
      1) "before all" hook for "Nested describe"
```
The `if` code is quite unnice, but I didn't touch it.
I have done quite a few tests what are the next steps for this issue?

**Comment by juergba** [comment] 2018-11-09 18:31
The following hooks are set incorrectly in `hook.ctx.currentTest`
`before` hook: is undefined or points to the outer test already past successfully.
`after` hook: is undefined.

[runner.js 301ff](https://github.com/mochajs/mocha/blob/master/lib/runner.js#L301)
```
if (name === "beforeAll") {                  //new
      hook.ctx.currentTest = hook.parent.tests[0];
} else if (name === "afterAll") {          //new
      hook.ctx.currentTest = hook.parent.tests[hook.parent.tests.length - 1];
} else {
      hook.ctx.currentTest = self.test;   //old
}
```
With `nested suites` I just search the current suite for the next test to come and don't run down all nested `describe`s. If no `test` can be found in the current `suite`, `currentTest` remains undefined.

[runner.js 301ff](https://github.com/mochajs/mocha/blob/master/lib/runner.js#L271)
```
if (hook.ctx && hook.ctx.currentTest) { 
    hook.originalTitle = hook.originalTitle || hook.title;
    hook.title =
    hook.originalTitle + ' for "' + hook.ctx.currentTest.title + '"';
} else {     //new
   let parent = hook.parent.title || 'root';    //new
   hook.title += ' for "' + parent + '"';     //new
}

```
```
Top-level describe
  √ Top-level it
  Nested describe
     1) "before all" hook for "Nested it"
```

**Comment by plroebuck** [comment] 2018-11-09 23:46
PR #3333 seems to be addressing the same issue. While it "fixed" the problem, it wasn't merged ASAP because it seemed to be patching after the fact. I worked on it for a bit, expanding the test case to verify other assumptions in the code, but got lost in the forest at some point.  @juergba's solution above looks more in line with fixing the root problem.

**Comment by plroebuck** [comment] 2018-11-11 08:50
@juergba do you have a PR?

**Comment by juergba** [comment] 2018-11-11 12:37
@plroebuck  No.
It would be my first one. So please, tell me what you are expecting me to do. Thank you.

**Comment by plroebuck** [comment] 2018-11-11 16:59
@juergba:

```bash
$ cd ~/Projects    # or wherever you develop from
$ MOCHA_REPO="https://github.com/mochajs/mocha.git"
$ git clone ${MOCHA_REPO}
$ cd mocha
$ npm install
$ BASE_UPON_BRANCH="master"
$ NEW_BRANCH="issues/3291"    # easy if you name it after the issue#
$ git checkout -b ${NEW_BRANCH} ${BASE_UPON_BRANCH}
```

Make your changes to whatever files. Then find relevant specification file(s) and update tests to prove your changes work.

```bash
$ git status
$ git add <files you changed related to this fix>
$ git-cz        # assuming "commitizen" installed globally
$ git push    # to _your_ GitHub repository
```
Assuming the tests run correctly on Travis, etc., create a pull request from your repository for this branch.

Did I scare you?

**Comment by juergba** [comment] 2018-11-11 17:08
@plroebuck Thank you! 
No, not scared, but ... I'm just watching tutorials about git/github.

I leave you the choice:
- you give me some days and your will will happen.
- it's a very old bug. Do it yourself fast and easy. No problem with, I will watch and learn.

**Comment by plroebuck** [comment] 2018-11-11 18:44
Do you have tests to confirm your changes?

When I looked into Heather's PR, believe she said that only `before` hook was incorrect. But you imply it's both.

**Comment by juergba** [comment] 2018-11-11 19:31
```
before(function () {
    //throw new Error();
    console.log('before root', this.currentTest ? this.currentTest.title : undefined);
});

describe('suite A', () => {
    it('test A', ()=>{});
    describe('suite B', function () {
        before(function () {
            //throw new Error();
            console.log('before B', this.currentTest ? this.currentTest.title : undefined);
        });
        beforeEach(function () {
            console.log('beforeEach B', this.currentTest ? this.currentTest.title : undefined);
        });
        afterEach(function () {
            console.log('afterEach B', this.currentTest ? this.currentTest.title : undefined);
        });
        after(function () {
            console.log('after B', this.currentTest ? this.currentTest.title : undefined);
        });
        it('test1 B', function () { });
        it('test2 B', function () { });
    })
})
```
With that one you can see that `currentTest` of `after` is undefined, at least not pointing to an incorrect test. So the Errortitle is not obviously wrong, just incomplete, the second part "for ..." is missing.

**Comment by juergba** [comment] 2018-11-12 16:34
@plroebuck  I created my github repository and opened a new branch with my changes and some test cases. [repo](https://github.com/juergba/mocha.git)
Next step will be the specification file(s).

**Comment by juergba** [comment] 2018-11-13 06:30
@plroebuck 
When running hook-err.spec.js of the master branch, original status without any of my changes, all tests are failing with: (Node 10.5.0)
```
Error: Timeout of 200ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (D:\mocha3291\mocha\test\integration\hook-err.spec.js)
      at Hook.Runnable._timeoutError (lib\runnable.js:460:10)
      at Timeout.<anonymous> (lib\runnable.js:271:24)
```
I can't find out why, can you help?

**Comment by juergba** [comment] 2018-11-13 10:42
@plroebuck  ok.

There is another difference in a test which I don't understand: test/cascade.fixtures.js 
This test passes successfully, but the output is different.
My forked master (5.2.0):
```
one
before one
    two
  before two
      three
    before three
  before each one
    before each two
    before each three
      TEST three
    after each three
    after each two
  after each one
        √ should three                            <<<<< different
    after three
  after two
after one
```
my local mocha installation (also 5.2.0)
```
one
before one
    two
  before two
      three
    before three
  before each one
    before each two
    before each three
      TEST three
        √ should three
    after each three
    after each two
  after each one
    after three
  after two
after one
```

**Comment by plroebuck** [comment] 2018-11-13 18:11
Go ahead and create a PR named "WIP: Fix Hook Test Names". These questions relate to your PR, not the original issue. Feel the original output is correct, but based on your fix shown above, see no reason why it would have changed the output at all.

**Closed** 2019-01-28 18:55 UTC
Labels: confirmed-bug, help wanted
