### ISSUE TITLE
[BUG] it.only run two test case

### ISSUE THREAD

**Issue by Matrixbirds** [mochajs/mocha#2909] opened 2017-07-03 07:05 UTC
```js
    it.only('send example', function *() {
      console.log(1);
    });
    it ('send example', function *() {
      console.log(2);
    });
```

then i got output as below
```output
1
2
```

**Comment by ScottFreeCode** [comment] 2017-07-03 21:44
Make sure you are using the latest version of Mocha and do not have different global and local versions installed. Mocha 2.x had a bug (or a badly implemented feature\*) that could cause this, but that was fixed in 3.x and this example seems to be fine.

Also, if you are using Mocha through some additional framework or with some add-on enhancement that handles generator functions, you may wish to try replacing it with using Co to wrap your generators before passing them to Mocha and see if that resolves the issue, as it's possible that the problem is not with Mocha itself.

\* (In 2.x, `only` was a way to apply `grep`, which filters by suite+test title and would therefore pick up identically named suites or tests. 3.x no longer treats `only` as a filtering function, rather directly tracking which suites and tests were marked `only`.)

**Comment by Matrixbirds** [comment] 2017-07-04 03:14
yup, i used 2.x. i will be use the latest version. thx

**Closed** 2017-07-04 03:14 UTC
Labels: needs-feedback, unconfirmed
