### ISSUE TITLE
Bail flag causes before() hooks to be run even after a failure

### ISSUE THREAD

**Issue by dpatti** [mochajs/mocha#1812] opened 2015-07-25 18:54 UTC
Example file:

```javascript
describe('one', function(){
  it('fails', function(){
    throw Error("failed");
  });
});

var slowHook = function(next) {
  console.log("hook");
  setTimeout(next, 1000);
};

describe('two', function(){
  before(slowHook);
  it('never runs', function(){ });
});

describe('three', function(){
  before(slowHook);
  it('never runs', function(){ });
});

describe('four', function(){
  before(slowHook);
  it('never runs', function(){ });
});
```

So what I'm seeing is that when you run this with `--bail` and the first test fails, it keeps going and runs all the other hooks before actually quitting. The output looks like this:

```
$ mocha --version
2.2.5
$ mocha timeout.js -b


  one
    1) fails

  two
hook

  three
hook

  four
hook


  0 passing (3s)
  1 failing

  1) one fails:
     Error: failed
      at Error (<anonymous>)
      at Context.<anonymous> (timeout.js:3:11)
```

In our actual code base we have hundreds of test suites each with sometimes lengthy hooks that set up and tear down fixtures in the db. When you run the whole suite with `-b`, you might see one red dot, and then it appears to hang for over a minute while it is running all the other hooks. Finally it reports with the failure. I can't think of why this would be desirable, so my best guess is that it is a bug.

**Comment by okv** [comment] 2015-08-20 13:18
+1 (really looks like bug)

**Comment by okv** [comment] 2015-08-20 13:20
Can it be fixed in some way?

**Comment by dasilvacontin** [comment] 2015-08-20 18:07
Bug confirmed, thanks for reporting.

**Comment by aaroncrows** [comment] 2015-09-02 04:07
I've found a fix for this that passes the tests and I can submit a PR. I'm not exactly sure how to simulate the multiple it and before blocks for the purposes of adding a test for the fix though.

**Comment by dasilvacontin** [comment] 2015-09-02 06:18
@aaroncrows This can be helpful: https://github.com/mochajs/mocha/blob/master/test/integration/helpers.js

Usage example: https://github.com/mochajs/mocha/blob/master/test/integration/multiple.done.js

Let us know if you need further help/pointers. :)

**Closed** 2015-09-02 21:22 UTC
Labels: Bug, PR PLEASE
