### ISSUE TITLE
Tests throw an error in IE8

### ISSUE THREAD

**Issue by Xotic750** [mochajs/mocha#1606] opened 2015-03-18 00:30 UTC
Have been running tests on numerous browsers and all has been running fine. Have now come to run the tests on IE8. The tests begin to run and then stop.

The error I see in the console is
```'undefined' is not null or object```
and it points to this code in the debug, at the ` } catch (err) {`
```javascript
Runner.prototype.runTest = function(fn){
  var test = this.test
    , self = this;

  if (this.asyncOnly) test.asyncOnly = true;

  try {
    test.on('error', function(err){
      self.fail(test, err);
    });
    test.run(fn);
  } catch (err) {
    fn(err);
  }
};
```
This is the block of code that is running at the time, I believe but I've run out of IE testing time..
```javascript
        var  maxLength = Math.pow(2, 32) - 1,
              testSubject1 = [2, 3, undefined, true, 'hej', null, false, 0, , 9];
              testSubject2 = [];
              testSubject3 = [ , , ];

        it('should have a correct length between 0 and ' + maxLength, function () {
            var  max = [];

            expect(function () {
                max[maxLast] = 'ok';
            }).to.not.throwException();

            expect(max.length).to.be(maxLength);

            max = [];
            expect(function () {
                max.length = maxLength;
            }).to.not.throwException();

            expect(max.length).to.be(maxLength);

            testValue = 10;
            expect(testSubject1.length).to.be(testValue);

            testValue = 0;
            expect(testSubject2.length).to.be(testValue);

            testValue = 2;
            expect(testSubject3.length).to.be(testValue);
        });
```
The blocks before the one above output results in the browser. The block after the above, in case needed is
```javascript
        it('should throw RangeError if length is set to < 0', function () {
            expect(function () {
                var max = [];

                max.length = -1;
            }).to.throwException(function (e) {
                expect(e).to.be.a(RangeError);
            });
        });
```
I am using the a copy of the current `master`.
Any pointers to what the problem could be? Is it a `mocha` problem?

Update: I have just tried the latest release (2.2.1) and it does not have the problem.

**Comment by dasilvacontin** [comment] 2015-03-22 16:50
If `master` doesn't have the problem, just
![move along]
(http://i.imgur.com/iXGV18l.gif)

**Comment by Xotic750** [comment] 2015-03-22 17:19
The problem was with `master`, the latest release `2.2.1` worked fine. Whatever.

**Comment by dasilvacontin** [comment] 2015-03-22 17:37
Oh, I misunderstood, sorry.

**Comment by dasilvacontin** [comment] 2015-03-22 17:52
558191d964e860eaddd6432e8fe5a86bad7781be might be the cause of the regression, can you test using that commit, and then it's parent? I don't have a Windows machine to do it myself.

**Comment by Xotic750** [comment] 2015-03-22 19:50
Unfortunately I don't have `windows` or `IE` either. I was using `browserstack` and I have run out of testing time as I only have a free account. I used the last few minutes of testing time to get the information that I have provided. Sorry. :(

**Comment by dasilvacontin** [comment] 2015-03-22 20:06
No worries, thanks for the report and the information! I could try using `browserstack` to reproduce the error, now that I know about it.

**Comment by danielstjules** [comment] 2015-03-23 06:26
@Xotic750 Thanks for pointing this out! Fixed in https://github.com/mochajs/mocha/pull/1617

**Closed** 2015-03-23 06:25 UTC

**Comment by Xotic750** [comment] 2015-03-23 21:30
You're welcome.
