### ISSUE TITLE
Mocha strange behavior with adding/remove only statement while using watch flag

### ISSUE THREAD

**Issue by rickarubio** [mochajs/mocha#3108] opened 2017-11-15 19:04 UTC
Mocha version: v3.5.3

I have the following in my package.json:
```
    "test:watch": "NODE_ENV=test mocha --watch --watch-extensions js,jsx --reporter nyan",
```

When I run this, everything seems to be running well and fine at first.

However, the problem manifests itself when I start playing around with adding ".only" to my describe blocks.

I'll do something like this on a describe block with 1 it block that is already passing:

```
describe.only('#blah', () => ....blah....
```

and all is well. The spec reporter will report 1 spec passing. So far, looking good.

Now, I go ahead and remove the only statement:

```
describe('#blah', () => ....blah....
```

The spec reporter reports 0 passing (in green).

At this point, none of the changes I make to any spec files will be picked up anymore.

I either have to avoid use of only, or be very careful about when I add/remove the only statement when using the watch flag.

Anyone else experiencing this?

**Comment by ScottFreeCode** [comment] 2017-11-15 21:08
This was a known issue in Mocha 3 (duplicate of #2429), which should be fixed in version 4 with #2544.

**Comment by rickarubio** [comment] 2017-11-15 21:14
@ScottFreeCode awesome, thanks!

**Comment by ScottFreeCode** [comment] 2017-11-15 21:58
You're welcome! Let us know if you need any help transitioning to version 4!

**Closed by ScottFreeCode** 2017-11-15 21:58 UTC
