### ISSUE TITLE
🐛 Bug: Can't create more than 1 instance of Mocha programatically

### ISSUE THREAD

**Issue by tigermarques** [mochajs/mocha#2740] opened 2017-03-15 17:53 UTC
When I create 2 instances of mocha programatically, and run them, I can only get the first one to give me the actual results.
```
import Mocha from 'mocha';
import path from 'path';

const files = ['mixins/_BiDi', 'utils/utils'];

for (let i = 0; i < files.length; i++) {
  const mocha = new Mocha({});
  mocha.addFile(path.resolve(__dirname, files[i]));
  mocha.run(function() {});
}
```

When I run this code, only the tests for the first file are run, and I get `0 passing (0ms)` for the second one.
I've tried setting the tests so that one mocha instance only runs after the previous one has finished, but the result is the same.

For this case in particular, adding both files to the same Mocha instance is not an option.

**Comment by JoshuaKGoldberg** [comment] 2024-01-15 05:40
Duplicate of #2706.

**Closed by JoshuaKGoldberg** 2024-01-15 05:40 UTC
Labels: unconfirmed-bug
