### ISSUE TITLE
after() not called on error

### ISSUE THREAD

**Issue by Almad** [mochajs/mocha#534] opened 2012-08-07 10:57 UTC
describe 'Test', ->
      after -> console.error 'cleanup is not called'
    
      describe 'When I do something', ->
        before -> throw new Error 'BAM' # and there is a problem
        it -> assert.ok true

**Comment by geoguide** [comment] 2015-02-02 20:18
I am having an issues where the after does not run if the before hook fails. This is annoying because I do a register and authenticate before and a delete after and the register runs and then authenticate fails and i ahve tons of test data.

**Comment by dasilvacontin** [comment] 2015-02-02 20:22
@geoguide, version of mocha and sample test suite where it fails?

**Comment by geoguide** [comment] 2015-02-02 20:56
@dasilvacontin 2.1.0

**Comment by dasilvacontin** [comment] 2015-02-02 21:04
With mocha 2.1.0 I can't get to reproduce the issue the bug with the following code:
```
describe('after a failed before', function() {

    before(function() {
        console.log('before hook');
        throw new Error
    })

    after(function() {
        console.log('the after hook should be called anyways')
    })

    it('shouldn\'t execute this test', function() {
        console.log('wat')
    })

})
```

**Comment by geoguide** [comment] 2015-02-02 21:26
Maybe i need to throw the error instead of returning error messages on expects. I thought that was equivalent to throwing an error though.

**Comment by geoguide** [comment] 2015-02-02 21:49
That's not fixing it. It's very likely I'm formatting the test wrong, because this is my first shot at using mocha. 

It is basically as you see it, i just tried changing the returns to throw errors and it got more messed up so went back to returning messages. I'll try looking at the docs some more to figure out where I'm going wrong, but for now i just have to make sure those methods in before are working.

**Comment by dasilvacontin** [comment] 2015-02-02 22:42
@geoguide, the after hook is executing in my code.

Basically you have to throw errors if necessary, either manually, or via a library, like `should`, `chai`, etc. If you need help you can ping me at Gitter.

**Comment by dasilvacontin** [comment] 2015-02-02 23:17
Okay, I confirm this is still failing when you are throwing **async** inside the before.

**Comment by searls** [comment] 2015-02-04 00:21
Given how long this issue has been around, I suspect this is a relatively recent regression?

**Comment by dasilvacontin** [comment] 2015-02-04 00:36
Maybe, our tests for these scenarios suck.

**Comment by dasilvacontin** [comment] 2015-02-04 03:13
Hmm. Not sure if it's related to the bug I found.

**Comment by dasilvacontin** [comment] 2015-02-04 08:21
I'm working on this on PR #1531.

**Comment by dasilvacontin** [comment] 2015-02-06 01:31
It seems like I'll have to change the uncaught error listener behaviour, so that I can test a mocha instance  using mocha; the main mocha is getting the uncaught errors that are intended to get caught by the mocha instance I'm testing.

This might also fix a compatibility error we had with Hapi, or something similar  that I read over the repo's issues.

**Comment by thardy** [comment] 2015-02-20 19:47
I recently started using mocha, and I was surprised to see this bug as well.  I have some tests that hit a MongoDb database and I wanted to use after to clean up any of the records my tests inserted.  I was surprised to find out that "after" did not execute when my tests fail.

I look forward to this being fixed.

**Comment by rom1504** [comment] 2015-03-30 01:39
I'm getting that problem too, also looking forward for a fix!

**Comment by jifeon** [comment] 2015-09-04 20:28
guys! any news here?

**Comment by ajaykodali** [comment] 2015-10-30 21:25
@jifeon should be fixed in the latest release

**Comment by dasilvacontin** [comment] 2015-11-30 15:12
Closed via https://github.com/mochajs/mocha/pull/1802. Thanks @ajaykodali!

**Closed by dasilvacontin** 2015-11-30 15:12 UTC
Labels: High priority

**Comment by igorbunova** [comment] 2021-12-15 16:50
The workaround I've found for after:
`before("before all", ...)
try {
  it("test1", ...)
  it("test2", ...)
} finally {
   after("after all", ...)
}
`
I didn't check whether it will keep the test stack trace if after raises an error, however it can be wrapped with try/catch as well for sure.

**Comment by lbeschastny** [comment] 2021-12-15 17:53
@igorbunova `try ... catch` shouldn't do anything here since `it(...)` only registers a test handler for mocha to execute later.

So, `after` itself is always called before any test cases are executed, but it's handler may or may not be executed after that.

**Comment by lbeschastny** [comment] 2021-12-15 17:59
Anyway, the bag was fixed a long ago
