### ISSUE TITLE
2.4.5 - afterEach run multiple extra times and wrong number of tests reported if a test errors

### ISSUE THREAD

**Issue by rally25rs** [mochajs/mocha#2216] opened 2016-04-19 13:59 UTC
I think I've stumbled into a weird edge case here.

I have global-level `beforeEach` and `afterEach` handlers, as well as some nested in a `describe`, basically like this:

```
beforeEach(function () {
  console.log('GLOBAL BEFORE');
});

afterEach(function () {
  console.log('GLOBAL AFTER');
});

describe('', function() {
  beforeEach(function () {
    console.log('BEFORE');
  });

  afterEach(function () {
    console.log('AFTER');
  });

  it('test 1', function () {
    console.log('test 1');
  });

  it('test 2', function () {
    console.log('test 2');
  });
});
```

It seems that if all my tests pass, I get the output 

```
LOG: 'GLOBAL BEFORE'
LOG: 'BEFORE'
LOG: 'test 1'
LOG: 'AFTER'
LOG: 'GLOBAL AFTER'
LOG: 'GLOBAL BEFORE'
LOG: 'BEFORE'
LOG: 'test 2'
LOG: 'AFTER'
LOG: 'GLOBAL AFTER'
LOG: 'GLOBAL BEFORE'
LOG: 'BEFORE'
LOG: 'test 3'
LOG: 'AFTER'
LOG: 'GLOBAL AFTER'
PhantomJS 1.9.8 (Mac OS X 0.0.0): Executed 91 of 91 SUCCESS (0.981 secs / 0.702 secs)
```

Note the test count is 91 (correct) and it measures the execution time at 0.702s.

However, if one of my tests errors, I get:

```
LOG: 'GLOBAL BEFORE'
LOG: 'BEFORE'
LOG: 'test 1'
LOG: 'AFTER'
LOG: 'GLOBAL AFTER'
LOG: 'GLOBAL BEFORE'
LOG: 'BEFORE'
LOG: 'test2'
LOG: 'AFTER'
LOG: 'GLOBAL AFTER'
LOG: 'GLOBAL BEFORE'
LOG: 'BEFORE'
LOG: 'test3'
PhantomJS 1.9.8 (Mac OS X 0.0.0) test 3 FAILED
	TypeError: 'undefined' is not a function (evaluating 'this.foo()') (/Users/me/Projects/foo/test/tests.js:1212)
LOG: 'AFTER'
LOG: 'AFTER'
LOG: 'GLOBAL AFTER'
LOG: 'GLOBAL AFTER'
LOG: 'GLOBAL AFTER'
PhantomJS 1.9.8 (Mac OS X 0.0.0): Executed 94 of 91 (3 FAILED) (0.969 secs / NaN secs)
```

Note now that after the failing "test 3" the nested `afterEach` is called twice, and the global `afterEach` is called 3 times!

Also it reports 94/91 tests now (cool, it ran 103% of my tests! :) ) and reports the execution time as `NaN`

-----

I'll try to distill my actual test code into a sharable example to reproduce this behavior, but I suspect there is some weird edge case I've run into that will disappear as soon as I change anything...

**Comment by rally25rs** [comment] 2016-04-19 15:32
I reproduced some of the issues here: https://github.com/rally25rs/mocha-issue2216

but can't seem to reproduce whatever was making the afterEach get called multiple times...

**Comment by rally25rs** [comment] 2016-04-19 17:04
Not sure if this helps at all either, but with the HTML reporter / running in a browser, I see the same test triplicated (the 2 failures and last success are all the same test. there are actually only 3 tests not 5).

There is an error on the console, and it seems if you debug there, `this.test.body` is undefined.

![screen shot 2016-04-19 at 1 00 25 pm](https://cloud.githubusercontent.com/assets/38535/14648227/3978bc1a-062f-11e6-8334-aa56ba0254b2.png)

**Comment by rally25rs** [comment] 2016-04-20 17:06
Part of this is related to #2112

**Comment by danielstjules** [comment] 2016-04-27 08:34
Yup, this is a duplicate of https://github.com/mochajs/mocha/issues/2083 and should be fixed in the next release, sorry!

**Closed by danielstjules** 2016-04-27 08:34 UTC
