### ISSUE TITLE
Segmentation faults, stderr and exit code

### ISSUE THREAD

**Issue by michaelsbradleyjr** [mochajs/mocha#358] opened 2012-03-31 21:08 UTC
I'm using mocha to test a C++ addon for node.js, and sometimes the C++ side of things is causing segmentation faults.

If usage of the addon is wrapped in a child proces, e.g. with `child_process.exec`, the segfault results in `"Segmentation fault"` messages being sent to the child's `stderr` and the child's exit code is something other than `0` (e.g. `139` in my linux env).

In the context of mocha, the messages to `stderr` are getting swallowed and the segfault results in the mocha process
exiting with status code `0`.

Any thoughts on whether mocha could be adapted to pass on the messages to `stderr` and close with a non-zero exit code in the event of a segfault?

**Comment by danielstjules** [comment] 2015-03-15 03:02
Closing this issue as it's been a few years since it was posted. If you could highlight the C++ addon in question, and maybe post an example spec or reproduce case, feel free to re-open it and someone will take a look. :)

**Closed by danielstjules** 2015-03-15 03:02 UTC
