### ISSUE TITLE
Failing Tests display twice in HTML

### ISSUE THREAD

**Issue by sgnl** [mochajs/mocha#2166] opened 2016-03-25 19:20 UTC
Here is a link to the [jsfiddle](https://jsfiddle.net/sgnl/wfyavarf/2/).

Passing tests correctly pass and display only once.

**Comment by danielstjules** [comment] 2016-03-25 19:41
Thanks for letting us know! This is a duplicate of https://github.com/mochajs/mocha/issues/2083 and has will be fixed in https://github.com/mochajs/mocha/pull/2112

**Closed by danielstjules** 2016-03-25 19:41 UTC

**Comment by sgnl** [comment] 2016-03-25 20:03
TY. sorry for not finding the dupe issue. cheers!
