### ISSUE TITLE
--bail and --retries events: multiple "end" occurs

### ISSUE THREAD

**Issue by 1999** [mochajs/mocha#3414] opened 2018-06-11 10:45 UTC
### Prerequisites

- [x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend avoiding the use of globally installed Mocha.

### Description

I found out that when both `--retries` and `--bail` option are used "end" event is emitted 2+ times. While this works fine for reporters I'm not sure if this behaviour is okay. However, this is even trickier when there's no `--exit` option specified. What is the test supposed to do after the bailed "end"?

### Steps to Reproduce

CLI: `mocha -R test/util/events-reporter.js --bail --retries 1 test/bail-and-retries/index.spec.js`

```javascript
// test/util/events-reporter.js
const Base = require('mocha').reporters.Base;

module.exports = class Reporter extends Base {
    constructor(runner) {
        super(runner);

        [
            'waiting',
            'start',
            'end',
            'suite',
            'suite end',
            'test',
            'test end',
            'pass',
            'fail',
            'pending',
            'hook',
            'hook end',
        ].forEach((evtName) => {
            runner.on(evtName, this.onRunnerEventFired.bind(this, evtName));
        });
    }

    onRunnerEventFired(evtName) {
        console.log(evtName);
    }
};

// test/bail-and-retries/index.spec.js
describe('suite', () => {
    it('case', () => {
        throw new Error('fail');
    });
});
```

**Expected behavior:** needs discussion. Probably depends on `--exit`: if it's specified the program should stop executing after the bailed "end" is emitted. If it's not: 🤷‍♂️ 

**Actual behavior:** bailed "end" is emitted, then all other events occur including second "end"

**Reproduces how often:** 100%

### Versions

- The output of `mocha --version` and `node node_modules/.bin/mocha --version`: 5.2.0
- The output of `node --version`: 8.11.2
- The version and architecture of your operating system: OSX
- Your shell (bash, zsh, PowerShell, cmd, etc.): bash

**Comment by outsideris** [comment] 2018-07-21 13:40
In my test, with only `--bail`, `end` event occured twice. 

```
$ mocha -R test/util/events-reporter.js --bail test/bail-and-retries/index.spec.js
start
suite
suite
test
test
fail
end
test end
suite end
suite end
end
```

I think we need to defind `--bail` behavior clearly like #3398 .

**Comment by juergba** [comment] 2018-11-20 16:51
The flag `--retries 1` is not the reason why the `end` event is emitted twice. It is the `--bail` flag which is working incorrect. The root problem is shown in issue [#3457](https://github.com/mochajs/mocha/issues/3457). 

With the fixes applied the output looks like this:
```
mocha -R test/util/events-reporter.js --bail --retries 1 test/bail-and-retries/index.spec.js
start
suite
suite
test
test
fail
test end
suite end
suite end
end
```

**Comment by juergba** [comment] 2018-12-21 09:21
The double `end` event was a bug and has been fixed with PR #3617.  The bug was caused by the `bail` flag exclusively, without any link to `--retries`.
With `--bail` Mocha exits in a clean manner, all `afterEach` and `after` hooks are called for a potential cleanup, then all remaining tests/subsuites in current suite and all subsequent suites are skipped.
```
suite
start
suite
test
test
fail
test end
suite end
suite end
end
```
@craigtaub I'm unsure why the first two events switched their order. I just found one registered `start` event in "stats-collector.js". It's emitted in "runner.js" with Runner.immediately(). Is this switch ok?

**Comment by craigtaub** [comment] 2018-12-21 23:03
@juergba stats-collector is just a listener. Looks like its the Runner.immediately() which causes this switch. `start` is emitted on nextTick whereas the first `suite` is not. Im not sure if this is a bug.

**Comment by juergba** [comment] 2018-12-22 07:43
@craigtaub Yes, but Runner.immediately() hasn't been changed, whereas the statistics have been refactored. And before this refactoring the event order was different than now.
@plroebuck can you help, please?

**Comment by juergba** [comment] 2018-12-28 18:16
@outsideris Could you have a look at this switch of the `start` and `suite` events, please.
I think the order is incorrect now. I didn't checkout the commits, but the change could have been caused by 00ca06b. Thanks.

**Comment by outsideris** [comment] 2018-12-28 18:50
@juergba You are right. https://github.com/mochajs/mocha/commit/00ca06b0e957ec4f067268c98053782ac5dcb69f caused to change the order. I will dig it more.

**Comment by plroebuck** [comment] 2018-12-28 22:30
Someone please add a new PR with a trivial test case/fixture that outputs events fired with an expected order. Think it's time we merge it to prevent these continued issues with event firing order.

Until then, this needs to be backed out.

**Comment by boneskull** [comment] 2019-01-09 23:41
This, whether a fix or a backout, will need to be addressed before the first release.

@plroebuck 	We now have tests per @juergba 	and #3642.

**Comment by boneskull** [comment] 2019-01-31 00:59
@outsideris Are you still working on this one?

**Comment by outsideris** [comment] 2019-02-04 11:31
@boneskull  Now, I'm not.

**Closed** 2019-02-10 18:53 UTC
Labels: confirmed-bug
