### ISSUE TITLE
Group suites over multiple files

### ISSUE THREAD

**Issue by marcojahn** [mochajs/mocha#1792] opened 2015-07-07 08:37 UTC
When splitting my tests accross multiple files I got them grouped for each file.

    // file1.js
    describe('test 1 - file 1', function () {
        // more testcode here
    });

    // file2.js
    describe('test 1 - file 2', function () {
        // more testcode here
    });

The output is as expected

    test 1 - file 1
        (tests listed here)
    test 1 - file 2
        (tests listed here)

But I wonder if it is possible to group these tests by defining an additional "shared" describe

    // file1.js
    describe('grouped', function () {
        describe('test 1 - file 1', function () {
            // more testcode here
        });
    });

    // file2.js
    describe('grouped', function () {
        describe('test 1 - file 2', function () {
            // more testcode here
        });
    });

The expected output would be

    grouped
        test 1 - file 1
            (tests listed here)
        test 1 - file 2
            (tests listed here)

**Comment by marcojahn** [comment] 2015-07-07 08:45
This is how I currently achieve the desired output, but I am not sure if it just a workaround or how it should be done.

    export default function () {
        describe('test 1 - file 1', function () {
            // more testcode here
        });
    }
    
    import Test1 from './test1.js';
    
    describe('grouped', function () {
        Test1();
    });

**Comment by boneskull** [comment] 2015-07-10 19:16
dupe of #1413

**Closed** 2015-07-10 19:16 UTC
Labels: Duplicate

**Comment by paulbhartzog** [comment] 2019-10-23 19:55
Here's the same solution, but with different syntax:

one.js
```
function test1 () {
  describe('test 1 - file 1', function () {
    it('should be true', function () {
      expect(true).to.be.true
    })
  })
}
module.exports = {
  test1:test1
}
```
(do that ^ for each file of tests)

and this to use them in a group:
```
const one = require('./one.js')
const two = require('./two.js')
describe('grouped', function () {
  one.test1()
  two.test1()
})
```

Hope that helps

**Comment by danon** [comment] 2023-10-24 07:24
> This is how I currently achieve the desired output, but I am not sure if it just a workaround or how it should be done.
> 
> ```
> export default function () {
>     describe('test 1 - file 1', function () {
>         // more testcode here
>     });
> }
> 
> import Test1 from './test1.js';
> 
> describe('grouped', function () {
>     Test1();
> });
> ```

That's not ideal, since adding new test suits, requires editing the "joiner module", and can cause for example conflicts when merging multiple codes.
