### ISSUE TITLE
grep behaviour is badly documented

### ISSUE THREAD

**Issue by ghost** [mochajs/mocha#1565] opened 2015-02-22 02:29 UTC
I think that the following line of lib\mocha.js:
![image](https://cloud.githubusercontent.com/assets/359568/6317108/54dc4232-ba7d-11e4-9184-fe752c417623.png)
should change to 
![image](https://cloud.githubusercontent.com/assets/359568/6317124/8ec070cc-ba7d-11e4-88cc-994daf5d3aac.png)

**Comment by dasilvacontin** [comment] 2015-02-22 05:30
You should justify/provide reasons. Anyways, your code wouldn't work.
```
var str = 'test+sort';
var re = new RegExp(str);
re.test(str); //false
```

**Comment by dasilvacontin** [comment] 2015-02-22 05:55
'The value of grep option not exactly match the suite name'. If with option you mean function argument, then indeed, it doesn't. Because it's not the intended behaviour of the function.

If with option you mean the `--grep` option, it doesn't either. With `mocha --grep apple` I should be able to run all tests containing `apple` on its title. If you want an exact match, provide a regex to the `--grep` option.

**Comment by fzx** [comment] 2015-02-22 08:29
@dasilvacontin,thank you for the reply.
```javascript
If with option you mean the --grep option, it doesn't either. With mocha --grep apple I should be able to run all tests containing apple on its title. If you want an exact match, provide a regex to the --grep option.
...
Please provide an example of  --grep option that can do an exact match.

**Comment by dasilvacontin** [comment] 2015-02-22 11:53
It should be `mocha --grep ^apple$`. However, it doesn't work.

I've investigated the issue. `Runner` tests the regex against `test.fullTitle()`. `fullTitle()` returns the name of the test preceded by the descriptions in the describes. That way we can easily match all the tests nested in the describe. However, to allow an exact-match regex, we should also test against the test title only. I propose adding an OR:

`var match = self._grep.test(test.fullTitle()) || self._grep.test(test.title);`

Any thoughts @boneskull @travisjeffery?

**Comment by dasilvacontin** [comment] 2015-02-22 11:54
Same thing for matching against suite title.

**Comment by a8m** [comment] 2015-02-22 13:02
I'm fan of the currently `grep` behavior, it's looks sense and fits great with tdd/bdd workflow
this change could cause an inconsistent behavior, so I'm -1 on this change, you should make you regex more robust.

**Comment by dasilvacontin** [comment] 2015-02-22 14:10
@a8m, are you commenting on @fzx's change, or my suggestion?

**Comment by jbnicolai** [comment] 2015-02-22 14:11
@dasilvacontin I'm on the fence in regards to your suggestion. I see the use case, and feel like it should be supported, but am also hesitant as it makes the behaviour less intuitive.

**Comment by fzx** [comment] 2015-02-22 14:14
Why 'It should be mocha --grep ^apple$. However, it doesn't work'? I think the cause is in the lib/mocha.js line number of 226(see my pic at first post). The ^ and $ char are escaped by function escapeRe.

**Comment by a8m** [comment] 2015-02-22 14:16
on your suggestion @dasilvacontin.

**Comment by dasilvacontin** [comment] 2015-02-22 14:21
@fzx yes, they are escaped. But in any case, the regex is being checked against parent describes + suite/test title.

**Comment by dasilvacontin** [comment] 2015-02-22 14:22
@jbnicolai I would personally use `.only` to achieve this behaviour, tbh.

**Comment by fzx** [comment] 2015-02-22 14:23
I dislike the .only method, because you will sometimes forget to remove it.

**Comment by fzx** [comment] 2015-02-22 14:25
@dasilvacontin, why escaped the --grep option value?

**Comment by a8m** [comment] 2015-02-22 14:30
You should use the `.only` option @fzx (just don't forget about it haha).

**Comment by a8m** [comment] 2015-02-22 14:31
mixing matching titles would cause an unexpected behaviour @dasilvacontin

**Comment by dasilvacontin** [comment] 2015-02-22 14:31
@fzx I don't know. Mocha is not checking if value for `--grep` is a string or a regex. Not sure if it's a bug, or regex was never meant to be used with `--grep` and I misunderstood the use of the word `pattern` in mocha's documentation.

**Comment by dasilvacontin** [comment] 2015-02-22 14:35
@a8m, what would you currently expect if you tried using an exact-match regex via `--grep`?

And when not using a match-begin/end regex, behaviour would stay the same, wouldn't it? (not meaning I'm in favor of the change, just curious since you mention unexpected behaviour)

**Comment by a8m** [comment] 2015-02-22 14:54
You can use `--grep` with exact-match style today, 
like so: `mocha dir/ --grep='^Your.*(?=Reg).+Exp$'`.
I just saying that test-matching in two different title is not a good idea imo

**Comment by jbnicolai** [comment] 2015-02-22 15:02
>  test-matching in two different title is not a good idea imo

I agree

**Comment by a8m** [comment] 2015-02-22 15:02
@dasilvacontin for example, running this tests with: `--grep=^Array.+toString`, run both. I expecting to run only the first one.
```js
describe('Array', function() {
  describe('.toString()', function() {
    it('....', function() {
      // ...
    });
  });
});

describe('My super smart function', function() {
  it('Array with .toString() logic', function() {
    // ...
  });
});
```

**Comment by dasilvacontin** [comment] 2015-02-22 15:23
> test-matching in two different title is not a good idea imo

I agree too, it's horrible.

**Comment by dasilvacontin** [comment] 2015-02-22 15:35
@fzx, actually, since mocha is creating a regex with the given value of `--grep` at `/bin/_mocha`, the command line input is not being escaped.

@a8m, do you think that's clear to users? Because without the underlying-understanding of how grep matches work, I wonder where/how people figure out it's going to work that way, if it's not by trying. To be honest, I found out today. And that makes me worry.

**Comment by a8m** [comment] 2015-02-22 15:46
@dasilvacontin I'm a user(a happy one, haha). 
I think it's easy to get it after you play it a bit, but we can make the user's life more easier by expending the docs.
I can assign it to myself.

**Comment by dasilvacontin** [comment] 2015-02-22 16:04
Yep, improving the documentation is what I was about to propose. I took a look at it and it only mentions super easy cases that don't even use regex. Sure, go ahead. :)

**Comment by iongion** [comment] 2015-06-22 14:16
a8m how did you do it, this does not work ```mocha tests/ --grep="^root$"```, but this does ```mocha tests/ --grep="root"```

**Comment by ralf57** [comment] 2015-10-27 11:26
Any news about this?

**Comment by dasilvacontin** [comment] 2015-11-30 15:59
@ralf57 behaviour is intended, just badly documented. Regex is applied on full title.

**Comment by dasilvacontin** [comment] 2016-03-29 23:32
> I dislike the .only method, because you will sometimes forget to remove it.

Also, if like @ghost you ran into this because you forget to remove `.only`, you could use https://github.com/dasilvacontin/dot-only-hunter.

**Comment by boneskull** [comment] 2017-10-18 04:19
@ScottFreeCode Do you think you can update this with your recent additions for grep?

**Comment by ScottFreeCode** [comment] 2017-10-18 05:32
I don't think any of us have done any recent additions for grep, that I recall, and I know I haven't -- in fact as far as I remember the closest I've come to touching grep was submitting some old PRs to fix the HTML reporter's *usage* of it (but not the underlying behavior).

**Comment by dschuyler** [comment] 2017-11-09 20:33
If I understand this thread correctly: I'd prefer to see an additional function added (aside from grep() and fgrep()) to match the whole string. That third function would essentially do an fgrep with the ^ $ to match the whole string.

**Comment by tommedema** [comment] 2017-12-20 11:32
Is this still working as intended? I have a very simple use case. When I run `node_modules/mocha/bin/mocha` I have two tests running fine.

One of these tests is setup like so:

```
describe('url-static-clone', async function () {
  ...

  describe('static', async () => {
    it('should return expected html for simple static sites', async () => {
      ...
  })
})
```

If I then run: `node_modules/mocha/bin/mocha --grep="static"` it runs 0 tests.

**Comment by juergba** [comment] 2021-08-21 06:06
Documentation has been updated meanwhile.

**Closed by juergba** 2021-08-21 06:06 UTC
Labels: help wanted, documentation

**Comment by audioscavenger** [comment] 2023-05-28 23:25
fgrep implementation in mocha is still broken as of today. The solution I found involves renaming ALL describe() with a 1st extra character like "_"
No other way.
