### ISSUE TITLE
HTML reporters fails

### ISSUE THREAD

**Issue by xg-wang** [mochajs/mocha#2873] opened 2017-06-11 17:24 UTC
I tried to use html reporters but it failed. The doc reporter works fine.
```
mocha -s 1 -R html > report.html
```

The error trace is
```
  var div = document.createElement('div');
            ^

ReferenceError: document is not defined
    at fragment (/Users/xgwang/.nvm/versions/node/v8.0.0/lib/node_modules/mocha/lib/reporters/html.js:285:13)
    at new HTML (/Users/xgwang/.nvm/versions/node/v8.0.0/lib/node_modules/mocha/lib/reporters/html.js:57:14)
    at Mocha.run (/Users/xgwang/.nvm/versions/node/v8.0.0/lib/node_modules/mocha/lib/mocha.js:501:18)
    at Object.<anonymous> (/Users/xgwang/.nvm/versions/node/v8.0.0/lib/node_modules/mocha/bin/_mocha:469:18)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
```

I'm using Mocha 3.4.2 with node v8

**Comment by ScottFreeCode** [comment] 2017-06-14 02:38
Closing this as a duplicate of #1906; see the comment at https://github.com/mochajs/mocha/issues/1906#issuecomment-308303013 in particular, and feel free to continue discussion there!

**Closed by ScottFreeCode** 2017-06-14 02:38 UTC
