### ISSUE TITLE
mocha --watch throws an error if running with ES6

### ISSUE THREAD

**Issue by weepy** [mochajs/mocha#4831] opened 2022-02-14 06:16 UTC
I run `mocha --watch` on a node project with ES6 import enabled. I get the following error:

`Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/xxxx/test/test.js`

**Comment by juergba** [comment] 2022-02-14 07:22
duplicate of #4374

**Closed by juergba** 2022-02-14 07:22 UTC
Labels: unconfirmed-bug
