### ISSUE TITLE
Global memory leak check should ignore explicit properties rather then comparing lengths

### ISSUE THREAD

**Issue by vojtajina** [mochajs/mocha#748] opened 2013-02-13 19:41 UTC
````
mocha.setup({globals: ['xxx']});
````

Assume the `xxx` global variable was not defined during the test.

Now, you need to have at least two memory leaks to get the error, because of the condition in https://github.com/visionmedia/mocha/blob/master/lib/runner.js#L161

See https://github.com/testacular/testacular/issues/351

**Comment by danielstjules** [comment] 2015-03-09 04:07
I'm not able to reproduce with the latest version of mocha. So I'm thinking it's been fixed. :)

```html
<html>
<head>
  <meta charset="utf-8">
  <title>Mocha Tests</title>
  <link rel="stylesheet" href="mocha.css" />
</head>
<body>
  <div id="mocha"></div>
  <script src="mocha.js"></script>
  <script>mocha.setup('bdd')</script>
  <script>
    it('leak a var', function() {
      example = true;
    });
    mocha.checkLeaks();
    mocha.globals(['xxx']);
    mocha.run();
  </script>
</body>
</html>
```

yields

![screen shot 2015-03-08 at 9 04 25 pm](https://cloud.githubusercontent.com/assets/817212/6549780/b9b21740-c5d6-11e4-8d70-007dd710d3e3.png)

I'm going to close the issue and assume it's been resolved since `Runner.prototype.checkGlobals` has had a few modifications over the past couple years. However, please feel free to reopen if you're able to reproduce the issue!

**Closed by danielstjules** 2015-03-09 04:07 UTC
