### ISSUE TITLE
unhelpful error when describe lacks second argument

### ISSUE THREAD

**Issue by dasilvacontin** [mochajs/mocha#1744] opened 2015-06-13 16:25 UTC
```js
➜  temp  cat test/test.js
it('rulz')
describe('very cofee')
it('sucks')

➜  temp  mocha
/usr/local/lib/node_modules/mocha/lib/interfaces/bdd.js:49
      fn.call(suite);
        ^
TypeError: Cannot read property 'call' of undefined
    at context.describe.context.context (/usr/local/lib/node_modules/mocha/lib/interfaces/bdd.js:49:9)
    at Object.<anonymous> (/Users/dasilvacontin/temp/test/test.js:2:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at /usr/local/lib/node_modules/mocha/lib/mocha.js:192:27
    at Array.forEach (native)
    at Mocha.loadFiles (/usr/local/lib/node_modules/mocha/lib/mocha.js:189:14)
    at Mocha.run (/usr/local/lib/node_modules/mocha/lib/mocha.js:422:31)
    at Object.<anonymous> (/usr/local/lib/node_modules/mocha/bin/_mocha:398:16)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

**Comment by dasilvacontin** [comment] 2015-06-13 16:27
Throwing a `TypeError` or ignoring suites without a second argument (kinda like if they were pending) are ways to go.

I like the idea of having `pending` suites.

**Comment by ndhoule** [comment] 2015-06-20 02:03
I also find the asymmetry surprising:

```js
describe('something', function() {
  xit('skip it);
});

xdescribe('something', function() {}); // works fine
xdescribe('whatever'); // throws an error
```

**Comment by hellboy81** [comment] 2015-11-12 06:56
+ `infinity`

**Comment by JoeCostanzo** [comment] 2016-04-05 14:30
Still an issue.
To replicate it:

- Type `describe('')` into any of your spec files, as the beginning of a new suite you intend to write.
- Instead of filling out your describe, go away from your machine and forget you typed the incomplete block.
- Try to run your normal test command, find the above error trace, and proceed to waste an hour searching around for what it means.

**Comment by UlyssesAlves** [comment] 2016-08-11 20:53
I just wasted a good amount of time trying to find out what was wrong with my tests. I had written a backbone describe so that I wouldn't forget to test a given functionality, but I didn't pass a callback to the describe function, because I wasn't intending to implement the test right now. I was going to implement other tests first, and then return and complete this describe with an actual callback which would have the actual tests in "it" functions. It would have been much easir for me to diagnose the problem if mocha had said me "Invalid describe definition without callback argument." or something like that.

**Comment by Munter** [comment] 2016-08-13 23:09
@UlyssesAlves I can't recreate this behavior. What version of mocha are you running?

**Comment by UlyssesAlves** [comment] 2016-08-15 11:52
@Munter I'm using Mocha version 2.5.3. Here is a snippet of a scenario which will reproduce the issue as described above:

```
describe("This is a test suite with a callback function parameter.", function() {
    it('Some test', function() {
        assert.equal(1, 1);
    });
});

describe("This test suite has no callback parameter and will produce an error which is hard to debug.");
```

**Comment by Munter** [comment] 2016-08-15 20:56
In mocha 3 this is the output of the above test:

```
$ ./bin/mocha test/describe.js 


  This is a test suite with a callback function parameter.
    ✓ Some test


  1 passing (7ms)
```

Seems to be fixed

**Comment by UlyssesAlves** [comment] 2016-08-15 22:10
That's great! I'm going to update my project to the latest version of mocha then. I think @dasilvacontin (or some project member) should close the issue by now. Unless, of course, if this is still an issue for him or for someone else.

**Comment by dasilvacontin** [comment] 2016-08-18 08:03
@Munter @UlyssesAlves After reading that snippet, I was expecting to see a pending suite in the output. What about you?

**Comment by Munter** [comment] 2016-08-18 08:12
@dasilvacontin It does strike me as a bit odd that suites with no tests simply disappear completely in the output

**Comment by UlyssesAlves** [comment] 2016-08-18 09:34
@dasilvacontin sure. I think it would be better to see a pending suítes report so that we don't forget that our tests are not complete yet and that we have empty *describe* directives which need to be filled with actual test cases.

**Closed** 2016-09-19 06:36 UTC
Labels: bug, pr-please
