### ISSUE TITLE
this.skip() is also skipping teardown()/afterEach()

### ISSUE THREAD

**Issue by laughinghan** [mochajs/mocha#2148] opened 2016-03-08 21:20 UTC
``` js
    setup(function() {
      mock.innerHTML = 'Temporary stuff';
    });
    teardown(function() {
      mock.innerHTML = ''; // THIS ISN'T BEING RUN
    });
    test('test', function() {
      if ('some precondition is unmet') {
        this.skip();
      }
    });
```

With Mocha v2.4.5: http://jsbin.com/bijuru/edit?html,output
With latest `master` branch: http://jsbin.com/dajugel/edit?html,output

Observed: `Temporary stuff` is leftover from test setup

Expected: `Temporary stuff` should've been cleared by test teardown

**Comment by danielstjules** [comment] 2016-03-21 03:35
Confirmed as an issue. Likely extends to the bdd and other UIs as well.

``` javascript
suite('suite', function() {
  suiteSetup(function() {
    console.log('SUITE SETUP');
  });

  setup(function() {
    console.log('SETUP');
  });

  test('spec2', function() {
    console.log('SKIPPED SPEC');
    this.skip();
  });

  teardown(function() {
    console.log('TEADOWN');
  });

  suiteTeardown(function() {
    console.log('SUITE TEARDOWN');
  });
});

// =>

SUITE SETUP
SETUP
SKIPPED SPEC
SUITE TEARDOWN
```

**Comment by danielstjules** [comment] 2016-03-21 03:36
Note that the behavior is correct when using `test.skip` to skip the function. In that instance, the setup/beforeEach is never ran, so the teardown/afterEach is unnecessary.

It's only when dynamically skipping the spec that this occurs. In that case, the test is pending, however the setup/beforeEach has already ran.

**Comment by boneskull** [comment] 2016-06-11 21:30
@megagon @danielstjules 8a37e016e5629b46709891740c74d5f0b69929e0 was merged.  Is this still an issue?

**Comment by laughinghan** [comment] 2016-06-11 21:33
@boneskull: yes it is, I'm able to repro using the testcase from the original issue report that uses latest `master`, you can see "Temporary stuff" isn't cleaned up: http://jsbin.com/dajugel/edit?html,output

**Comment by ScottFreeCode** [comment] 2016-06-12 01:20
I copied this down locally and tried it with a rebuilt browser mocha.js file and confirmed the issue is still present. In the process I also noticed how this is different from #2286/#2287: that was `afterAll` being skipped if `beforeEach` calls skip, this is `afterEach` being skipped if the test or the `beforeEach` calls skip.

**Comment by laughinghan** [comment] 2016-06-12 03:05
@ScottFreeCode: oh, thanks! Did you ever try #2168?

**Comment by ScottFreeCode** [comment] 2016-06-12 05:16
If I take the change from #2168 and rebuild mocha.js, it does seem to fix this issue. It could use some updates to the tests though.

**Comment by boneskull** [comment] 2016-11-03 05:38
dupe of #2286 for all intents and purposes

**Closed by boneskull** 2016-11-03 05:38 UTC
Labels: duplicate

**Comment by boneskull** [comment] 2016-11-03 06:30
See PR #2571

**Comment by laughinghan** [comment] 2016-11-03 18:48
Hey now, mine came first so strictly speaking #2286 is a dupe of this one 😜
