### ISSUE TITLE
Capture per-test debug and only output on failure

### ISSUE THREAD

**Issue by aspiers** [mochajs/mocha#4735] opened 2021-08-29 10:10 UTC
It would be extremely useful to have a feature I've seen in other test frameworks, where an API exists for logging debug within a test, but the debug only appears in the output on failure.  This ensures that output of passing tests avoids visual clutter, whilst providing useful extra debug only when a test fails.  It's much better than leaving commented-out debug in your test code, because you never have to uncomment the debug to use it. 

As far as I can see, this feature doesn't exist in Mocha, in which case please consider this a feature request.  However if it does and I've just missed it, please consider this a documentation bug report, because I searched https://mochajs.org/ for `debug` and `log` and found nothing related.

**Comment by JoshuaKGoldberg** [comment] 2023-12-27 23:39
Duplicate of #1457. As in, per #5027, we're not looking to add big new features or change things significantly, so anything like this would likely come from plugins. Cheers!

**Closed by JoshuaKGoldberg** 2023-12-27 23:39 UTC
Labels: type: feature
