### ISSUE TITLE
A few doubts

### ISSUE THREAD

**Issue by jaydeep17** [mochajs/mocha#1541] opened 2015-02-08 01:19 UTC
I have been using mocha for a while and there's this particular behavior of mocha that's been constantly bugging me.

So today I decided to face it.

I have a nodejs server built using something like express.
I have a test suite with 100% results, but just to understand how mocha works I have tweaked the code to not respond to a particular call. Thus it is failing a test.

#### What is failing ?
`client2 receives client1s msg` under `Routes/Message sending route`
(Note : output given below)

#### Why is it failing ?
Because `done()` never gets called

#### Other info
I use `--bail` to abort the execution when a test fails. Also note that in most of the tests I use the `done()` method, as they are async calls.

Okay, so let's get started

Doubt 0
----
`done()` is never called, yet why does it say `done()` called multiple times ?

Doubt 1
----
In the output, you can notice that it constantly mentions `/home/jaydeep/Documents/nodejs/falcon/test/auth.js`, that's a little surprising to me as the failing test is in `home/jaydeep/Documents/nodejs/falcon/test/routes.js`. And all the tests in `auth.js` have already passed.

Doubt 2
----
As I use `--bail`, it should abort the execution as soon as it finds a failing test, yet `Delivery ACK route` gets executed.

#### First Output
```javascript
Authentication
00:44:00.916Z  WARN Falcon: username or password empty! (module=server, method=authenticate)
    ✓ forbids unauthorized connection 
    ✓ allows authorized connection 
    ✓ rejects publish to registerMe 
    Register mode
      ✓ allows connection to register mode 
      allowed pub/sub
        ✓ subscribe to registerMe/+ 
        ✓ rejects subscription to any other topic 
        register mode publish attempts
          ✓ some other topic 
          ✓ reject subscriptions to registerMe 

  Routes
    Message sending route // <------------------------- Here's the problem
      1) client2 receives client1s msg
    Delivery ACK route
      2) "after all" hook: destroy clients

  13 passing (1s)
  2 failing

  1) Routes Message sending route client2 receives client1s msg:
     Uncaught Error: done() called multiple times
      at Hook.Runnable (/home/jaydeep/Documents/nodejs/falcon/node_modules/mocha/lib/runnable.js:49:17)
      at new Hook (/home/jaydeep/Documents/nodejs/falcon/node_modules/mocha/lib/hook.js:22:12)
      at Suite.beforeEach (/home/jaydeep/Documents/nodejs/falcon/node_modules/mocha/lib/suite.js:224:14)
      at context.beforeEach (/home/jaydeep/Documents/nodejs/falcon/node_modules/mocha/lib/interfaces/bdd.js:53:17)
      at Suite.<anonymous> (/home/jaydeep/Documents/nodejs/falcon/test/auth.js:127:17)
      at context.describe.context.context (/home/jaydeep/Documents/nodejs/falcon/node_modules/mocha/lib/interfaces/bdd.js:74:10)
      at Suite.<anonymous> (/home/jaydeep/Documents/nodejs/falcon/test/auth.js:123:13)
      at context.describe.context.context (/home/jaydeep/Documents/nodejs/falcon/node_modules/mocha/lib/interfaces/bdd.js:74:10)
      at Suite.<anonymous> (/home/jaydeep/Documents/nodejs/falcon/test/auth.js:78:9)
      at context.describe.context.context (/home/jaydeep/Documents/nodejs/falcon/node_modules/mocha/lib/interfaces/bdd.js:74:10)
      at Suite.<anonymous> (/home/jaydeep/Documents/nodejs/falcon/test/auth.js:64:5)
      at context.describe.context.context (/home/jaydeep/Documents/nodejs/falcon/node_modules/mocha/lib/interfaces/bdd.js:74:10)
      at Object.<anonymous> (/home/jaydeep/Documents/nodejs/falcon/test/auth.js:8:1)
      at Module._compile (module.js:456:26)
      at Object.Module._extensions..js (module.js:474:10)
      at Module.load (module.js:356:32)
      at Function.Module._load (module.js:312:12)
      at Module.require (module.js:364:17)
      at require (module.js:380:17)
      at /home/jaydeep/Documents/nodejs/falcon/node_modules/mocha/lib/mocha.js:185:27
      at Array.forEach (native)
      at Mocha.loadFiles (/home/jaydeep/Documents/nodejs/falcon/node_modules/mocha/lib/mocha.js:182:14)
      at Mocha.run (/home/jaydeep/Documents/nodejs/falcon/node_modules/mocha/lib/mocha.js:394:31)
      at Object.<anonymous> (/home/jaydeep/Documents/nodejs/falcon/node_modules/mocha/bin/_mocha:394:16)
      at Module._compile (module.js:456:26)
      at Object.Module._extensions..js (module.js:474:10)
      at Module.load (module.js:356:32)
      at Function.Module._load (module.js:312:12)
      at Function.Module.runMain (module.js:497:10)
      at startup (node.js:119:16)
      at node.js:929:3

  2) Routes Message sending route "after all" hook: destroy clients:
     Uncaught Error: done() called multiple times
      at Hook.Runnable (/home/jaydeep/Documents/nodejs/falcon/node_modules/mocha/lib/runnable.js:49:17)
      at new Hook (/home/jaydeep/Documents/nodejs/falcon/node_modules/mocha/lib/hook.js:22:12)
      at Suite.beforeEach (/home/jaydeep/Documents/nodejs/falcon/node_modules/mocha/lib/suite.js:224:14)
      at context.beforeEach (/home/jaydeep/Documents/nodejs/falcon/node_modules/mocha/lib/interfaces/bdd.js:53:17)
      at Suite.<anonymous> (/home/jaydeep/Documents/nodejs/falcon/test/auth.js:127:17)
      at context.describe.context.context (/home/jaydeep/Documents/nodejs/falcon/node_modules/mocha/lib/interfaces/bdd.js:74:10)
      at Suite.<anonymous> (/home/jaydeep/Documents/nodejs/falcon/test/auth.js:123:13)
      at context.describe.context.context (/home/jaydeep/Documents/nodejs/falcon/node_modules/mocha/lib/interfaces/bdd.js:74:10)
      at Suite.<anonymous> (/home/jaydeep/Documents/nodejs/falcon/test/auth.js:78:9)
      at context.describe.context.context (/home/jaydeep/Documents/nodejs/falcon/node_modules/mocha/lib/interfaces/bdd.js:74:10)
      at Suite.<anonymous> (/home/jaydeep/Documents/nodejs/falcon/test/auth.js:64:5)
      at context.describe.context.context (/home/jaydeep/Documents/nodejs/falcon/node_modules/mocha/lib/interfaces/bdd.js:74:10)
      at Object.<anonymous> (/home/jaydeep/Documents/nodejs/falcon/test/auth.js:8:1)
      at Module._compile (module.js:456:26)
      at Object.Module._extensions..js (module.js:474:10)
      at Module.load (module.js:356:32)
      at Function.Module._load (module.js:312:12)
      at Module.require (module.js:364:17)
      at require (module.js:380:17)
      at /home/jaydeep/Documents/nodejs/falcon/node_modules/mocha/lib/mocha.js:185:27
      at Array.forEach (native)
      at Mocha.loadFiles (/home/jaydeep/Documents/nodejs/falcon/node_modules/mocha/lib/mocha.js:182:14)
      at Mocha.run (/home/jaydeep/Documents/nodejs/falcon/node_modules/mocha/lib/mocha.js:394:31)
      at Object.<anonymous> (/home/jaydeep/Documents/nodejs/falcon/node_modules/mocha/bin/_mocha:394:16)
      at Module._compile (module.js:456:26)
      at Object.Module._extensions..js (module.js:474:10)
      at Module.load (module.js:356:32)
      at Function.Module._load (module.js:312:12)
      at Function.Module.runMain (module.js:497:10)
      at startup (node.js:119:16)
      at node.js:929:3
```

Doubt 3
----
Other strange thing is when I run the same tests again I get different output, have a look at the below output.

#### Second Output
```javascript
  Authentication
00:49:31.848Z  WARN Falcon: username or password empty! (module=server, method=authenticate)
    ✓ forbids unauthorized connection 
    ✓ allows authorized connection 
    ✓ rejects publish to registerMe 
    Register mode
      ✓ allows connection to register mode 
      allowed pub/sub
        ✓ subscribe to registerMe/+ 
        ✓ rejects subscription to any other topic 
        register mode publish attempts
          ✓ some other topic 
          ✓ reject subscriptions to registerMe 

  Routes
    Message sending route // <------------------------- Here's the problem
      1) client2 receives client1 msg
      2) client2 receives client1 msg
    Delivery ACK route
    Read ACK route
      3) allows authorized connection
    Registered Contacts routes
    Forwards typing
    Profile changes
    Online notification

  Falcondb Connection test
    4) reject subscriptions to registerMe
    5) some other topic
    6) rejects publish to registerMe
    7) "after all" hook: closing server

  13 passing (1s)
  7 failing

  1) Routes Message sending route client2 receives client1 msg:
     Uncaught Error: done() called multiple times
      at Hook.Runnable (/home/jaydeep/Documents/nodejs/falcon/node_modules/mocha/lib/runnable.js:49:17)
      at new Hook (/home/jaydeep/Documents/nodejs/falcon/node_modules/mocha/lib/hook.js:22:12)
      at Suite.beforeEach (/home/jaydeep/Documents/nodejs/falcon/node_modules/mocha/lib/suite.js:224:14)
      at context.beforeEach (/home/jaydeep/Documents/nodejs/falcon/node_modules/mocha/lib/interfaces/bdd.js:53:17)
      at Suite.<anonymous> (/home/jaydeep/Documents/nodejs/falcon/test/auth.js:127:17)
      at context.describe.context.context (/home/jaydeep/Documents/nodejs/falcon/node_modules/mocha/lib/interfaces/bdd.js:74:10)
      at Suite.<anonymous> (/home/jaydeep/Documents/nodejs/falcon/test/auth.js:123:13)
      at context.describe.context.context (/home/jaydeep/Documents/nodejs/falcon/node_modules/mocha/lib/interfaces/bdd.js:74:10)
      at Suite.<anonymous> (/home/jaydeep/Documents/nodejs/falcon/test/auth.js:78:9)
      at context.describe.context.context (/home/jaydeep/Documents/nodejs/falcon/node_modules/mocha/lib/interfaces/bdd.js:74:10)
      at Suite.<anonymous> (/home/jaydeep/Documents/nodejs/falcon/test/auth.js:64:5)
      at context.describe.context.context (/home/jaydeep/Documents/nodejs/falcon/node_modules/mocha/lib/interfaces/bdd.js:74:10)
      at Object.<anonymous> (/home/jaydeep/Documents/nodejs/falcon/test/auth.js:8:1)
      at Module._compile (module.js:456:26)
      at Object.Module._extensions..js (module.js:474:10)
      at Module.load (module.js:356:32)
      at Function.Module._load (module.js:312:12)
      at Module.require (module.js:364:17)
      at require (module.js:380:17)
      at /home/jaydeep/Documents/nodejs/falcon/node_modules/mocha/lib/mocha.js:185:27
      at Array.forEach (native)
      at Mocha.loadFiles (/home/jaydeep/Documents/nodejs/falcon/node_modules/mocha/lib/mocha.js:182:14)
      at Mocha.run (/home/jaydeep/Documents/nodejs/falcon/node_modules/mocha/lib/mocha.js:394:31)
      at Object.<anonymous> (/home/jaydeep/Documents/nodejs/falcon/node_modules/mocha/bin/_mocha:394:16)
      at Module._compile (module.js:456:26)
      at Object.Module._extensions..js (module.js:474:10)
      at Module.load (module.js:356:32)
      at Function.Module._load (module.js:312:12)
      at Function.Module.runMain (module.js:497:10)
      at startup (node.js:119:16)
      at node.js:929:3

  2) Routes Message sending route client2 receives client1 msg:
     Uncaught Error: done() called multiple times
      at Hook.Runnable (/home/jaydeep/Documents/nodejs/falcon/node_modules/mocha/lib/runnable.js:49:17)
      at new Hook (/home/jaydeep/Documents/nodejs/falcon/node_modules/mocha/lib/hook.js:22:12)
      at Suite.beforeEach (/home/jaydeep/Documents/nodejs/falcon/node_modules/mocha/lib/suite.js:224:14)
      at context.beforeEach (/home/jaydeep/Documents/nodejs/falcon/node_modules/mocha/lib/interfaces/bdd.js:53:17)
      at Suite.<anonymous> (/home/jaydeep/Documents/nodejs/falcon/test/auth.js:127:17)
      at context.describe.context.context (/home/jaydeep/Documents/nodejs/falcon/node_modules/mocha/lib/interfaces/bdd.js:74:10)
      at Suite.<anonymous> (/home/jaydeep/Documents/nodejs/falcon/test/auth.js:123:13)
      at context.describe.context.context (/home/jaydeep/Documents/nodejs/falcon/node_modules/mocha/lib/interfaces/bdd.js:74:10)
      at Suite.<anonymous> (/home/jaydeep/Documents/nodejs/falcon/test/auth.js:78:9)
      at context.describe.context.context (/home/jaydeep/Documents/nodejs/falcon/node_modules/mocha/lib/interfaces/bdd.js:74:10)
      at Suite.<anonymous> (/home/jaydeep/Documents/nodejs/falcon/test/auth.js:64:5)
      at context.describe.context.context (/home/jaydeep/Documents/nodejs/falcon/node_modules/mocha/lib/interfaces/bdd.js:74:10)
      at Object.<anonymous> (/home/jaydeep/Documents/nodejs/falcon/test/auth.js:8:1)
      at Module._compile (module.js:456:26)
      at Object.Module._extensions..js (module.js:474:10)
      at Module.load (module.js:356:32)
      at Function.Module._load (module.js:312:12)
      at Module.require (module.js:364:17)
      at require (module.js:380:17)
      at /home/jaydeep/Documents/nodejs/falcon/node_modules/mocha/lib/mocha.js:185:27
      at Array.forEach (native)
      at Mocha.loadFiles (/home/jaydeep/Documents/nodejs/falcon/node_modules/mocha/lib/mocha.js:182:14)
      at Mocha.run (/home/jaydeep/Documents/nodejs/falcon/node_modules/mocha/lib/mocha.js:394:31)
      at Object.<anonymous> (/home/jaydeep/Documents/nodejs/falcon/node_modules/mocha/bin/_mocha:394:16)
      at Module._compile (module.js:456:26)
      at Object.Module._extensions..js (module.js:474:10)
      at Module.load (module.js:356:32)
      at Function.Module._load (module.js:312:12)
      at Function.Module.runMain (module.js:497:10)
      at startup (node.js:119:16)
      at node.js:929:3

  3) Authentication allows authorized connection:
     Error: done() called multiple times
      at Test.Runnable (/home/jaydeep/Documents/nodejs/falcon/node_modules/mocha/lib/runnable.js:49:17)
      at new Test (/home/jaydeep/Documents/nodejs/falcon/node_modules/mocha/lib/test.js:22:12)
      at context.it.context.specify (/home/jaydeep/Documents/nodejs/falcon/node_modules/mocha/lib/interfaces/bdd.js:112:18)
      at Suite.<anonymous> (/home/jaydeep/Documents/nodejs/falcon/test/auth.js:41:5)
      at context.describe.context.context (/home/jaydeep/Documents/nodejs/falcon/node_modules/mocha/lib/interfaces/bdd.js:74:10)
      at Object.<anonymous> (/home/jaydeep/Documents/nodejs/falcon/test/auth.js:8:1)
      at Module._compile (module.js:456:26)
      at Object.Module._extensions..js (module.js:474:10)
      at Module.load (module.js:356:32)
      at Function.Module._load (module.js:312:12)
      at Module.require (module.js:364:17)
      at require (module.js:380:17)
      at /home/jaydeep/Documents/nodejs/falcon/node_modules/mocha/lib/mocha.js:185:27
      at Array.forEach (native)
      at Mocha.loadFiles (/home/jaydeep/Documents/nodejs/falcon/node_modules/mocha/lib/mocha.js:182:14)
      at Mocha.run (/home/jaydeep/Documents/nodejs/falcon/node_modules/mocha/lib/mocha.js:394:31)
      at Object.<anonymous> (/home/jaydeep/Documents/nodejs/falcon/node_modules/mocha/bin/_mocha:394:16)
      at Module._compile (module.js:456:26)
      at Object.Module._extensions..js (module.js:474:10)
      at Module.load (module.js:356:32)
      at Function.Module._load (module.js:312:12)
      at Function.Module.runMain (module.js:497:10)
      at startup (node.js:119:16)
      at node.js:929:3

  4) Authentication Register mode allowed pub/sub register mode publish attempts reject subscriptions to registerMe:
     Error: done() called multiple times
      at Test.Runnable (/home/jaydeep/Documents/nodejs/falcon/node_modules/mocha/lib/runnable.js:49:17)
      at new Test (/home/jaydeep/Documents/nodejs/falcon/node_modules/mocha/lib/test.js:22:12)
      at context.it.context.specify (/home/jaydeep/Documents/nodejs/falcon/node_modules/mocha/lib/interfaces/bdd.js:112:18)
      at Suite.<anonymous> (/home/jaydeep/Documents/nodejs/falcon/test/auth.js:148:17)
      at context.describe.context.context (/home/jaydeep/Documents/nodejs/falcon/node_modules/mocha/lib/interfaces/bdd.js:74:10)
      at Suite.<anonymous> (/home/jaydeep/Documents/nodejs/falcon/test/auth.js:123:13)
      at context.describe.context.context (/home/jaydeep/Documents/nodejs/falcon/node_modules/mocha/lib/interfaces/bdd.js:74:10)
      at Suite.<anonymous> (/home/jaydeep/Documents/nodejs/falcon/test/auth.js:78:9)
      at context.describe.context.context (/home/jaydeep/Documents/nodejs/falcon/node_modules/mocha/lib/interfaces/bdd.js:74:10)
      at Suite.<anonymous> (/home/jaydeep/Documents/nodejs/falcon/test/auth.js:64:5)
      at context.describe.context.context (/home/jaydeep/Documents/nodejs/falcon/node_modules/mocha/lib/interfaces/bdd.js:74:10)
      at Object.<anonymous> (/home/jaydeep/Documents/nodejs/falcon/test/auth.js:8:1)
      at Module._compile (module.js:456:26)
      at Object.Module._extensions..js (module.js:474:10)
      at Module.load (module.js:356:32)
      at Function.Module._load (module.js:312:12)
      at Module.require (module.js:364:17)
      at require (module.js:380:17)
      at /home/jaydeep/Documents/nodejs/falcon/node_modules/mocha/lib/mocha.js:185:27
      at Array.forEach (native)
      at Mocha.loadFiles (/home/jaydeep/Documents/nodejs/falcon/node_modules/mocha/lib/mocha.js:182:14)
      at Mocha.run (/home/jaydeep/Documents/nodejs/falcon/node_modules/mocha/lib/mocha.js:394:31)
      at Object.<anonymous> (/home/jaydeep/Documents/nodejs/falcon/node_modules/mocha/bin/_mocha:394:16)
      at Module._compile (module.js:456:26)
      at Object.Module._extensions..js (module.js:474:10)
      at Module.load (module.js:356:32)
      at Function.Module._load (module.js:312:12)
      at Function.Module.runMain (module.js:497:10)
      at startup (node.js:119:16)
      at node.js:929:3

  5) Authentication Register mode allowed pub/sub register mode publish attempts some other topic:
     Error: done() called multiple times
      at Test.Runnable (/home/jaydeep/Documents/nodejs/falcon/node_modules/mocha/lib/runnable.js:49:17)
      at new Test (/home/jaydeep/Documents/nodejs/falcon/node_modules/mocha/lib/test.js:22:12)
      at context.it.context.specify (/home/jaydeep/Documents/nodejs/falcon/node_modules/mocha/lib/interfaces/bdd.js:112:18)
      at Suite.<anonymous> (/home/jaydeep/Documents/nodejs/falcon/test/auth.js:141:17)
      at context.describe.context.context (/home/jaydeep/Documents/nodejs/falcon/node_modules/mocha/lib/interfaces/bdd.js:74:10)
      at Suite.<anonymous> (/home/jaydeep/Documents/nodejs/falcon/test/auth.js:123:13)
      at context.describe.context.context (/home/jaydeep/Documents/nodejs/falcon/node_modules/mocha/lib/interfaces/bdd.js:74:10)
      at Suite.<anonymous> (/home/jaydeep/Documents/nodejs/falcon/test/auth.js:78:9)
      at context.describe.context.context (/home/jaydeep/Documents/nodejs/falcon/node_modules/mocha/lib/interfaces/bdd.js:74:10)
      at Suite.<anonymous> (/home/jaydeep/Documents/nodejs/falcon/test/auth.js:64:5)
      at context.describe.context.context (/home/jaydeep/Documents/nodejs/falcon/node_modules/mocha/lib/interfaces/bdd.js:74:10)
      at Object.<anonymous> (/home/jaydeep/Documents/nodejs/falcon/test/auth.js:8:1)
      at Module._compile (module.js:456:26)
      at Object.Module._extensions..js (module.js:474:10)
      at Module.load (module.js:356:32)
      at Function.Module._load (module.js:312:12)
      at Module.require (module.js:364:17)
      at require (module.js:380:17)
      at /home/jaydeep/Documents/nodejs/falcon/node_modules/mocha/lib/mocha.js:185:27
      at Array.forEach (native)
      at Mocha.loadFiles (/home/jaydeep/Documents/nodejs/falcon/node_modules/mocha/lib/mocha.js:182:14)
      at Mocha.run (/home/jaydeep/Documents/nodejs/falcon/node_modules/mocha/lib/mocha.js:394:31)
      at Object.<anonymous> (/home/jaydeep/Documents/nodejs/falcon/node_modules/mocha/bin/_mocha:394:16)
      at Module._compile (module.js:456:26)
      at Object.Module._extensions..js (module.js:474:10)
      at Module.load (module.js:356:32)
      at Function.Module._load (module.js:312:12)
      at Function.Module.runMain (module.js:497:10)
      at startup (node.js:119:16)
      at node.js:929:3

  6) Authentication rejects publish to registerMe:
     Error: done() called multiple times
      at Test.Runnable (/home/jaydeep/Documents/nodejs/falcon/node_modules/mocha/lib/runnable.js:49:17)
      at new Test (/home/jaydeep/Documents/nodejs/falcon/node_modules/mocha/lib/test.js:22:12)
      at context.it.context.specify (/home/jaydeep/Documents/nodejs/falcon/node_modules/mocha/lib/interfaces/bdd.js:112:18)
      at Suite.<anonymous> (/home/jaydeep/Documents/nodejs/falcon/test/auth.js:52:5)
      at context.describe.context.context (/home/jaydeep/Documents/nodejs/falcon/node_modules/mocha/lib/interfaces/bdd.js:74:10)
      at Object.<anonymous> (/home/jaydeep/Documents/nodejs/falcon/test/auth.js:8:1)
      at Module._compile (module.js:456:26)
      at Object.Module._extensions..js (module.js:474:10)
      at Module.load (module.js:356:32)
      at Function.Module._load (module.js:312:12)
      at Module.require (module.js:364:17)
      at require (module.js:380:17)
      at /home/jaydeep/Documents/nodejs/falcon/node_modules/mocha/lib/mocha.js:185:27
      at Array.forEach (native)
      at Mocha.loadFiles (/home/jaydeep/Documents/nodejs/falcon/node_modules/mocha/lib/mocha.js:182:14)
      at Mocha.run (/home/jaydeep/Documents/nodejs/falcon/node_modules/mocha/lib/mocha.js:394:31)
      at Object.<anonymous> (/home/jaydeep/Documents/nodejs/falcon/node_modules/mocha/bin/_mocha:394:16)
      at Module._compile (module.js:456:26)
      at Object.Module._extensions..js (module.js:474:10)
      at Module.load (module.js:356:32)
      at Function.Module._load (module.js:312:12)
      at Function.Module.runMain (module.js:497:10)
      at startup (node.js:119:16)
      at node.js:929:3

  7) Routes "after all" hook: closing server:
     Uncaught TypeError: Object #<Client> has no method 'emit'
      at /home/jaydeep/Documents/nodejs/falcon/node_modules/mosca/lib/persistence/abstract.js:79:16
      at RedisPersistence.lookupRetained (/home/jaydeep/Documents/nodejs/falcon/node_modules/mosca/lib/persistence/redis.js:193:20)
      at Server.server.forwardRetained (/home/jaydeep/Documents/nodejs/falcon/node_modules/mosca/lib/persistence/abstract.js:77:10)
      at /home/jaydeep/Documents/nodejs/falcon/node_modules/mors/node_modules/mosca/lib/client.js:446:21
      at Array.forEach (native)
      at /home/jaydeep/Documents/nodejs/falcon/node_modules/mors/node_modules/mosca/lib/client.js:444:26
      at /home/jaydeep/Documents/nodejs/falcon/node_modules/mors/node_modules/mosca/node_modules/async/lib/async.js:254:17
      at done (/home/jaydeep/Documents/nodejs/falcon/node_modules/mors/node_modules/mosca/node_modules/async/lib/async.js:135:19)
      at /home/jaydeep/Documents/nodejs/falcon/node_modules/mors/node_modules/mosca/node_modules/async/lib/async.js:32:16
      at /home/jaydeep/Documents/nodejs/falcon/node_modules/mors/node_modules/mosca/node_modules/async/lib/async.js:251:21
      at Object._onImmediate (/home/jaydeep/Documents/nodejs/falcon/node_modules/mors/node_modules/mosca/lib/client.js:412:7)
      at processImmediate [as _immediateCallback] (timers.js:354:15)
```

**Comment by travisjeffery** [comment] 2015-02-08 02:28
dunno without seeing your tests, can you either show those or reproduce the issue with an example?

**Comment by dasilvacontin** [comment] 2015-02-08 02:30
Unless you should a simple reproducible example, it will be difficult to help. :/

**Comment by jaydeep17** [comment] 2015-02-08 19:44
While I was trying to reproduce it in a sample code. I ran into something else.

[Here](https://github.com/jaydeep17/mochajs_doubts)'s the entire code.

I have created a simple express app, with just one endpionts (the root), which sends back `hello world\n`.

There are two test files, `auth.js` and `routes.js` under `test` directory. I have tried to mimic the structure of tests I have in my original app. Looking at the tests it seems that they should pass without any problems.

BTW, the test is to verify that the server responds something.

But they don't pass.

#### Reason ?
I have no clue.

#### Other observation
Try commenting out, test `subscribe to registerMe/+` in `Layer 2`  of `auth.js`.
You'll find that the place where the test was failing changes.

**Comment by boneskull** [comment] 2015-02-16 09:40
@jaydeep17 I don't think anyone is going to want to wade through all that code.  If you want to see something happen, we'll need a concise reproducible case.

**Comment by danielstjules** [comment] 2015-03-14 22:09
@jaydeep17 Closing for now since it's been over a month since your last reply. If you're able to come up with a smaller test case (a single file, only a few specs), we'd be happy to help! :)

**Closed by danielstjules** 2015-03-14 22:09 UTC
Labels: Needs-Feedback
