### ISSUE TITLE
Interdependent instances of "new Mocha()" Object

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [mochajs/mocha#3141] opened 2017-12-09 22:14 UTC
### Description
Only one `new Mocha()` instance can be created that will behave normally. The second mocha instance will not run any tests.
```javascript
const Mocha = require('mocha')
const mocha1 = new Mocha()
const mocha2 = new Mocha() // will behave badly
```

### Steps to Reproduce
Run *try_mocha_run_twice.js* in the same directory as *test_simple.js* in a console and view the output for the inconsistencies between the two different results of the function *mocha_test*. 

try_mocha_run_twice.js
```javascript
const Mocha = require('mocha')

function mocha_test() {
  return new Promise(resolve => {

    const mocha = new Mocha()
    mocha.addFile('test_simple.js')

    console.log('start --------------------------------')

    mocha.run(() => {
      console.log('end --------------------------------')
      resolve()
    })

  })
}


async function run_mult_tests(count=2) {
  for (; count > 0; --count)
    await mocha_test()
}

run_mult_tests(2)
```

test_simple.js
```javascript
describe('pass fail', function() {
  it('should pass', function() {})
  it('should fail', function() {throw new Error('fail')})
})
```

#### Expected behavior:
```shell
$ node try_mocha_run_twice.js
start --------------------------------

  pass fail
    ✓ should pass
    1) should fail

  1 passing (9ms)
  1 failing

  1) pass fail
       should fail:
     Error: fail
      at Context.<anonymous> (try_test_mocha_run_twice.js:3:39)


end --------------------------------
start --------------------------------


  pass fail
    ✓ should pass
    1) should fail

  1 passing (9ms)
  1 failing

  1) pass fail
       should fail:
     Error: fail
      at Context.<anonymous> (try_test_mocha_run_twice.js:3:39)


end --------------------------------
```

#### Actual behavior:
```shell
$ node try_mocha_run_twice.js
start --------------------------------

  pass fail
    ✓ should pass
    1) should fail

  1 passing (9ms)
  1 failing

  1) pass fail
       should fail:
     Error: fail
      at Context.<anonymous> (try_test_mocha_run_twice.js:3:39)

end --------------------------------
start --------------------------------

  0 passing (0ms)

end --------------------------------
```

**Reproduces how often:** 100%

### Versions
OS X El Capitan 10.11.6
mocha 4.0.1
node v8.5.0
shell: osx term

### Prerequisites

* [x] Checked that your issue isn't already filed by cross referencing [issues with the `common mistake` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Acommon-mistake%20)
* [x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
* [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
* [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with:
`node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend avoiding the use of globally installed Mocha.

**Comment by boneskull** [comment] 2017-12-13 01:26
duplicate of #2783

**Closed by boneskull** 2017-12-13 01:26 UTC
