### ISSUE TITLE
describe.only matches more that one describe test suite

### ISSUE THREAD

**Issue by DinisCruz** [mochajs/mocha#1481] opened 2014-12-23 11:31 UTC
If I have these two test suites (just showing the first one)

```coffee
describe 'Boolean',->

  it 'is_True',->
    expect(true.is_True    ).to.be.an('Function')
    expect(false.is_True   ).to.be.an('Function')
    expect(true.is_True()  ).to.be.true
    expect(false.is_True() ).to.be.false
    expect((1==1).is_True()).to.be.true
    expect((1==2).is_True()).to.be.false
    expect((1!=1).is_True()).to.be.false
``` 

and

```coffee
describe 'Assert | Boolean',->
  it 'assert_Is_True', ->
    true.assert_Is_True.assert_Is_Function()
    true.assert_Is_True().assert_Is_True()
    (-> false.assert_Is_True()).assert_Throws()
```

If I add **.only** to the first one : 
```coffee
describe.only 'Boolean',->
```

both will now be executed:

![image](https://cloud.githubusercontent.com/assets/656739/5537286/e7824a9e-8a96-11e4-9b96-b1643bd4ae93.png)

![image](https://cloud.githubusercontent.com/assets/656739/5537292/06cfd97a-8a97-11e4-9b18-7521030aab68.png)

and I would expect only the first one to execute

I assuming that mocha behind the scenes is not keeping a pointer to the actual tests to execute, it is just keeping the name/string, which is then searched on all tests/describes loaded (is that correct?)

**Comment by tylerhjones** [comment] 2015-01-07 17:47
https://github.com/mochajs/mocha/pull/1492

**Comment by tylerhjones** [comment] 2015-01-07 17:48
Try that.

**Comment by twolfson** [comment] 2015-01-07 18:05
@tylerhjones That solution will fit most cases but not if there are 2 cases with the same `describe` block and I use a `.only` on one of them.

```js
// We should only run this block
describe.only('A server', function () {
  describe('receiving an HTTP request', function () {
    it('replies successfully', function () {
    });
  });
});

describe('A server', function () { /* Similar setup but different test */ });
```

We need to solve it from file and position within the file. That is a valid unique identifer for each block.

**Comment by danielstjules** [comment] 2015-03-14 05:55
So far we've had 3 candidate fixes for this issue: https://github.com/mochajs/mocha/pull/1492 https://github.com/mochajs/mocha/pull/1595 and https://github.com/mochajs/mocha/pull/1591

If no one else has jumped on this already, I'll be reviewing all 3 tomorrow morning to hopefully get this closed up :)

**Comment by demisx** [comment] 2015-04-27 18:07
+1

**Comment by dasilvacontin** [comment] 2015-11-30 15:27
PR #1807 is in the works, for the record.

**Comment by Vanuan** [comment] 2016-02-10 10:46
Are you trying to solve multiple issues with one pull request?

The issue is quite simple to describe:

If some test name is a part of another name, ".only" should match one test name.

**Comment by Vanuan** [comment] 2016-02-10 10:57
`it` works correctly, BTW:

    it.only('name')
    it('another name')
    # only 'name' is executed

**Comment by RavenHursT** [comment] 2016-03-18 18:44
@Vanuan lol.. I totally agree.. this has been marked as a bug since Dec 2014.

This bit me in the butt today as well.  The `.only` behavior in Mocha is extremely confusing.

**Comment by deltreey** [comment] 2016-03-23 21:17
wow, I thought I might help by putting in a fix, but the latest pull request changes 17 files and hundreds of lines of code...how complicated is this `.only` check?

**Comment by Vanuan** [comment] 2016-03-23 21:21
It's not complicated. It's that maintainers are trying to fix more and more issues in one pull request.

**Comment by danielstjules** [comment] 2016-03-23 21:24
> changes 17 files and hundreds of lines of code...how complicated is this .only check?

Those are mostly integration tests. The lib change itself is 6 files and 83 loc.

**Comment by Vanuan** [comment] 2016-03-23 21:27
First pull request, #1492 covered all use cases except duplicate test names. For me duplicate test names is a bug, not a feature. Mocha should've stack-traced if smb registered duplicate tests.

**Comment by boneskull** [comment] 2016-07-03 06:18
PR for this is merged into v3.0.0 branch via 8a75434

**Closed by boneskull** 2016-07-03 06:18 UTC
Labels: bug, pr-please

**Comment by krmannix** [comment] 2017-05-15 16:57
Is it possible to use the old behavior (i.e., `.only` including all blocks, regardless of file, at the same level & same identifier) with a flag or something? I structured tests based on the old behavior, and it was nice to run all tests for a specific identifier with a single `.only`

**Comment by ScottFreeCode** [comment] 2017-05-17 02:17
[`--grep`](https://mochajs.org/#g---grep-pattern) (or `.grep` in the programmatic API) is (and always was) equivalent to the old `.only` behavior. Or maybe it was equivalent to [`--fgrep`/`.fgrep`](https://mochajs.org/#usage); I forget which. Use whichever fits your use case. ;^)
