### ISSUE TITLE
Can't --require custom UI and use it

### ISSUE THREAD

**Issue by joaomoreno** [mochajs/mocha#1794] opened 2015-07-10 14:27 UTC
In the [Third party UIs](https://github.com/mochajs/mocha/wiki/Third-party-UIs) wiki page, it is said that one can `--require` a module which enriches the `mocha.interfaces` object bag with a custom UI and directly use it with the `--ui` option.

This doesn't seem to work.

Looking at the latest [`bin/_mocha`](https://github.com/mochajs/mocha/blob/952dca73d1c24132b0fb8e30e3300b5346f0f1c1/bin/_mocha), I can see why: [the UI lookup](https://github.com/mochajs/mocha/blob/952dca73d1c24132b0fb8e30e3300b5346f0f1c1/bin/_mocha#L214) happens before [all the requires are required](https://github.com/mochajs/mocha/blob/952dca73d1c24132b0fb8e30e3300b5346f0f1c1/bin/_mocha#L311).

Is this a regression?

**Comment by boneskull** [comment] 2015-07-10 19:18
@joaomoreno don't know if it's a regression or not, but this seems like a bug.

**Comment by boneskull** [comment] 2015-07-10 19:19
@joaomoreno what 3p UI are you using?

**Comment by joaomoreno** [comment] 2015-07-10 20:33
@boneskull I'm not using *one* 3p UI. I followed the aforementioned guide, in which you defined a UI in a JS module, `--require` it and refer to it using the `--ui` option. Just follow the guide using the latest version and you'll see what I mean.

**Comment by joaomoreno** [comment] 2015-07-13 12:16
@boneskull Please check joaomoreno/mocha@102e1402fcb61f772940c085517352198885f163. This adds an integration test which tests for the exact same example that is explained in the Wiki. Run it with:

```mocha test/integration/regression.js```

**Comment by danielstjules** [comment] 2015-07-15 10:18
@joaomoreno It's been a bit since I wrote the page, and I'll give it an update tomorrow. But try running `npm install mocha`. Prior to doing so, I got:

``` javascript
$ mocha --require ./simple-ui.js --ui simple-ui test.js
/usr/local/lib/node_modules/mocha/lib/mocha.js:174
  if (!this._ui) throw new Error('invalid interface "' + name + '"');
                       ^
Error: invalid interface "simple-ui"
    at Mocha.ui (/usr/local/lib/node_modules/mocha/lib/mocha.js:174:24)
    at Object.<anonymous> (/usr/local/lib/node_modules/mocha/bin/_mocha:210:7)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:428:10)
    at Module.load (module.js:335:32)
    at Function.Module._load (module.js:290:12)
    at Function.Module.runMain (module.js:451:10)
    at startup (node.js:123:18)
    at node.js:868:3
```

But after:

``` javascript
$ cd Desktop/mocha-test/
dstjules:~/Desktop/mocha-test

$ cat test.js
test('pass', function() {
  // pass
});

test('fail', function() {
  throw new Error('oops!');
});

dstjules:~/Desktop/mocha-test
$ cat simple-ui.js
var Mocha = require('mocha');
    Suite = require('mocha/lib/suite'),
    Test  = require('mocha/lib/test');

/**
 * A simple UI that only exposes a single function: test
 */
module.exports = Mocha.interfaces['simple-ui'] = function(suite) {
  suite.on('pre-require', function(context, file, mocha) {
    var common = require('mocha/lib/interfaces/common')([suite], context);

    context.run = mocha.options.delay && common.runWithSuite(suite);

    /**
     * Describes a specification or test-case with the given `title`
     * and callback `fn` acting as a thunk.
     */
    context.test = function(title, fn) {
      var test = new Test(title, fn);
      test.file = file;
      suite.addTest(test);

      return test;
    };
  });
};

dstjules:~/Desktop/mocha-test
$ mocha --version
2.2.5

dstjules:~/Desktop/mocha-test
$ mocha --require ./simple-ui.js --ui simple-ui test.js


  ✓ pass
  1) fail

  1 passing (12ms)
  1 failing

  1)  fail:
     Error: oops!
      at Context.<anonymous> (test.js:6:9)
```

**Comment by joaomoreno** [comment] 2015-07-15 15:34
Your answer led me to the real issue: it fails when `simple-ui.js` lives in a child directory. Try the following:

```
mkdir foo
mv simple-ui.js foo
mocha --require ./foo/simple-ui.js --ui simple-ui test.js
```

**Comment by danielstjules** [comment] 2015-07-15 15:57
> it fails when simple-ui.js lives in a child directory

Looks like it fails when the ui lives anywhere outside of the cwd, instead? Should be easier to hunt down what to change :)

**Comment by joaomoreno** [comment] 2015-07-15 21:06
Yep sounds like it!

**Comment by joaomoreno** [comment] 2015-07-16 12:50
OK, so the sample works not because you provide `--require` to mocha, but because of this [require call](https://github.com/mochajs/mocha/blob/952dca73d1c24132b0fb8e30e3300b5346f0f1c1/lib/mocha.js#L193). It will also work if you simply run 

```
mocha --ui simple-ui test.js
```

This makes sense, given the fact that requiring the modules defined via `--require` will happen after the `ui` resolution.

Knowing this, a potential workaround is to provide the full path to the UI module:

```
mocha --ui /full/path/to/simple-ui.js test.js
```

This actually works, but doesn't help me in my use case: I need to add the `--ui` parameter in a `mocha.opts` file, which knows nothing about its own full path, much less `simple-ui.js`'s.

**Comment by tauren** [comment] 2015-10-09 20:10
Is anyone working on a fix for this yet? If not, I'll try to find some time to work on it.

**Comment by nazarhussain** [comment] 2015-12-10 12:08
I came up with a finding which at least works for me. 

For any Custom UI it is not necessary or even required to add it to `--require`, just adding it to `--ui` will load it automatically. 

Other point is `--ui` does not accept the name of ui which is defined in `Mocha.interfaces['tags']`, it's the name of the npm package/module in which that ui resides. 

So if we have a ui `my-ui` in a package called `my-style-ui`

```javascript
module.exports = Mocha.interfaces['my-ui'] = function(suite) {
```
For running it we need to specify `--ui my-style-ui` not `my-ui`

**Comment by jgkim** [comment] 2015-12-13 14:24
@nazarhussain That's true for UI plugins published on NPM, but if you implemented an UI plugin in your project, you shoud use both `--require` and `--ui`. Of course, this is a rare case, but I encountered this problem when I developed a plugin.

**Comment by nazarhussain** [comment] 2015-12-14 05:12
Since we had identified the issue... so we should add a note to readme and close this issue.

**Closed** 2015-12-25 22:10 UTC
Labels: Bug, PR PLEASE

**Comment by danielstjules** [comment] 2015-12-25 22:13
@joaomoreno Fixed via https://github.com/mochajs/mocha/commit/a61b1f3287b436522545e5458d071d7e791c15d0 Included your test case, and updated it to work with local mocha. https://github.com/mochajs/mocha/commits/master

**Comment by memelet** [comment] 2015-12-30 04:53
So will remain that a ui required via npm will need to use -ui npm-module-name and not the ui name?
