### ISSUE TITLE
--fgrep doesnt work with --watch

### ISSUE THREAD

**Issue by VictorioBerra** [mochajs/mocha#2027] opened 2015-12-27 18:07 UTC
### Expected

when using `--fgrep "my search string" --watch` one would think a file change would run tests with the provided fgrep string.
### Actual

all tests re-run when a file is changed as if `--fgrep` was never used.

**Comment by Fahrradflucht** [comment] 2017-05-23 15:34
Confirmed! The `fgrep` flag is only recognised for the first test run. re-runs just run all tests. This is a major issue on large codebases.

**Comment by boneskull** [comment] 2017-10-18 04:27
grep and watch don't play nice together.

**Comment by Janpot** [comment] 2019-02-21 11:21
`--watch` + `--grep` used to work well for me. It just broke completely in `mocha@6` for me. It just runs `0` tests.

**Comment by Janpot** [comment] 2019-02-21 11:57
To reproduce:
given the following test file:
```js
/* eslint-env mocha */
describe('testsuite', () => {
  it('test1', () => {});
  it('test2', () => {});
});
```
Running under v5:
```sh
$ npx mocha@5 --watch --grep test1
npx: installed 24 in 2.949s



  testsuite
    ✓ test1


  1 passing (5ms)
```
Running under v6:
```sh
$ npx mocha@6 --watch --grep test1
npx: installed 230 in 6.878s



  0 passing (1ms)
```

**Comment by plroebuck** [comment] 2019-02-21 17:21
@Janpot, already fixed in #3755.

**Comment by boneskull** [comment] 2019-02-21 18:43
rather, it'll be fixed when it's released.

duplicate of #3748

**Comment by boneskull** [comment] 2019-02-21 19:31
oh, whoops.

**Closed** 2019-07-17 11:27 UTC
Labels: confirmed-bug, help wanted
