### ISSUE TITLE
Tests not running with Mocha 9.0.2 and Yarn Berry (2.4.2)

### ISSUE THREAD

**Issue by Drethic** [mochajs/mocha#4693] opened 2021-07-19 19:58 UTC
### Prerequisites

- [x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend that you _not_ install Mocha globally.

### Description

When our project upgrade to Mocha 9.0.2 from 8.3.1 running mocha would return 0 tests.  Before the update we had over 400 tests.  We ended up updating to 8.4.0 in the short term and our tests continued to function.  I put together a demo repo that is just yarn 2.4.2, mocha 9.0.2, and chai 4.3.4 to showcase no tests appear.  As a test I also removed chai and did the assert only test with the same result.

### Steps to Reproduce

Link to [demo](https://github.com/Drethic/mocha-yarn-bug) repo.
1. Clone demo repo
2. Run `yarn install` to install mocha, chai, and their dependencies
3. Run `yarn test` and the console will return `0 passing (1ms)`

That repo should have 2 passing tests.  Also, this shows with and without chai as part of the tests to rule that out.

If you downgrade to yarn 1.22.10 the tests work.  If you downgrade mocah to 8.4.0 the tests work.  I assume the issue is with Mocah because older versions work as expected.

**Expected behavior:** [What you expect to happen]
2 Passing tests

**Actual behavior:** [What actually happens]

No tests found:
`0 passing (1ms)`

**Reproduces how often:** [What percentage of the time does it reproduce?]
100% reproduction

### Versions

- The output of `mocha --version` and `node node_modules/.bin/mocha --version`: 9.0.2
- The output of `node --version`: v14.15.5
- Your operating system
  - name and version: macOS Big Sur (11.4)
  - architecture (32 or 64-bit): 64-bit
- Your shell (e.g., bash, zsh, PowerShell, cmd): zsh
- Your browser and version (if running browser tests): N/A
- Any third-party Mocha-related modules (and their versions): N/A
- Any code transpiler (e.g., TypeScript, CoffeeScript, Babel) being used (and its version): N/A

**Comment by juergba** [comment] 2021-07-20 06:14
@Drethic I don't use _yarn_, and tried to have a short look on _yarn 2_. There is no `node_modules` folder anymore to play around with. I don't have time to go through this migration guide , but I hope you have done that correctly.

From my side this issue is on standby, I'm sorry:
- Mocha v9 works with _npm_
- can you check your migration from _yarn1_ to _yarn 2_, please?
- in Mocha v9.0.0 we removed the deprecated public `utils.lookupFiles()` which returns test file paths. Could this be the reason?

**Comment by juergba** [comment] 2021-07-20 11:10
Btw: _yarn_ runs very small integration tests with Mocha, eg. [this one](https://github.com/yarnpkg/berry/runs/3112346887).
They show:
```
➤ YN0000: Done with warnings in 2s 996ms
const assert = require('assert'); it('should pass', function() { assert.equal(true, true); });


  0 passing (1ms)

const assert = require('assert'); it('should fail', function() { assert.equal(true, false); });


  0 passing (2ms)
```

**Comment by Drethic** [comment] 2021-07-20 12:26
@juergba For yarn 2 all of the packages are now stored in .yarn/cache as a zip file.  .pnp.js is what handles the reading of the packages at run time.

We have been running yarn 2 for close to a year with no issues, it wasn't until mocha updated from 8 to 9 that our tests stopped working.  I did verify that version 9 works yarn 1 but we are not able to use that version since we have never used it for the project and it would require an overhaul on our part.  As for the `utils.lookupFiles()` I wouldn't know where to begin testing that.  If you can point me to it's usage in v8 and how you handle test file paths I can try to debug it myself if I have the time.

I did look at the action you linked.  I see they are using a shell script to test the latest build with mocha by echoing a line for a couple tests.  I think it's being missed by the yarn team because 0 passing may not flag like a fail would.

**Comment by juergba** [comment] 2021-07-20 13:11
@Drethic Thank you. I understand your problem, but ... Mocha v9 is a major release with breaking changes listed in our changelog. It's to easy to simply blame Mocha.

Looking at the code of _yarn_, it looks like typescript despite the `js` extension. They need type definitions which possibly are not up-to-date, [@types/mocha](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/mocha/index.d.ts) is for Mocha v8.2. `utils.lookupFiles()` has been removed in v9.0.0 and moved to _lib/cli/lookup-files.js_. This may explain the bug, but I don't see how Mocha's types should affect _yarn_.

**Comment by Drethic** [comment] 2021-07-20 13:29
@juergba I put in a number of console logs and it's hitting the first if block and does return files.  Here is the output:

```js
Starting lookupFiles
lookupFiles - filepath does not exist
lookupFiles - hasMagic
{ pattern: '**/*.spec.js', filepath: '**/*.spec.js' }
{
  files: [ 'test-mocha-and-chai.spec.js', 'test-mocha-assert.spec.js' ]
}
{
  files: [ 'test-mocha-and-chai.spec.js', 'test-mocha-assert.spec.js' ]
}
```

Here is a snippet of what I modified so you can see where the items are responding:
```js
module.exports = function lookupFiles(
  filepath,
  extensions = [],
  recursive = false
) {
  console.log('Starting lookupFiles');
  const files = [];
  let stat;

  if (!fs.existsSync(filepath)) {
    let pattern;
    console.log('lookupFiles - filepath does not exist');
    if (glob.hasMagic(filepath)) {
      console.log('lookupFiles - hasMagic');
      // Handle glob as is without extensions
      pattern = filepath;
      console.log({ pattern, filepath });
    } else {
      console.log('lookupFiles - not hasMagic');
      // glob pattern e.g. 'filepath+(.js|.ts)'
      const strExtensions = extensions
        .map(ext => (ext.startsWith('.') ? ext : `.${ext}`))
        .join('|');
      pattern = `${filepath}+(${strExtensions})`;
      debug('looking for files using glob pattern: %s', pattern);
    }
    files.push(...glob.sync(pattern, {nodir: true}));
    console.log({ files });
    if (!files.length) {
      console.lg('About to throw error');
      throw createNoFilesMatchPatternError(
        `Cannot find any files matching pattern "${filepath}"`,
        filepath
      );
    }
    console.log({ files });
    return files;
  }
```

**Comment by juergba** [comment] 2021-07-20 15:00
@Drethic thank you. We can exclude _lib/cli/lookup-files.js_ as source then.

I did some yarn/cache zip file manipulation to have a closer look at our test file loading.
@giltayar can you join in, please? _esm-utils.js_ loads empty default objects.

```
function dealWithExports(module) {
  if (module.default) {             <== this is an empty object
    return module.default;
  } else { 
    return {...module, default: undefined};
  }
}
```

**Comment by juergba** [comment] 2021-07-21 20:07
It's not `module.default` being empty. This seems to be correct, since there are no exports in this test file.
But `require.cache` says: not loaded 
```
Module {
  id: 'D:\\temp\\mocha-yarn-bug-master\\test\\test-mocha-and-chai.spec.js',
  path: 'D:\\temp\\mocha-yarn-bug-master\\test',
  exports: {},
  parent: undefined,
  filename: 'D:\\temp\\mocha-yarn-bug-master\\test\\test-mocha-and-chai.spec.js',
  loaded: false,
  children: [],
  paths: [
    'D:\\temp\\mocha-yarn-bug-master\\test\\node_modules',
    'D:\\temp\\mocha-yarn-bug-master\\node_modules',
    'D:\\temp\\node_modules',
    'D:\\node_modules'
  ]
}
```

**Comment by juergba** [comment] 2021-07-22 18:08
@Drethic I applied the following changes to your demo project:
- add `nodeLinker: node-modules` to _yarnrc.yml_
- add `"@yarnpkg/plugin-node-modules": "*"` to _package.json_

then run: `yarn install`: => creates the good old `node_modules` folder.

```
$ yarn -v
2.4.2

$ yarn test
  Testing Mocha 9.0.2 with Yarn 2.4.2
    √ Should have 1 test that passes

  Array
    #indexOf()
      √ should return -1 when the value is not present

  2 passing (4ms)
```

I think this isn't a Mocha thing, but Yarn PnP. I guess they use their own loader hooks?

**Comment by Drethic** [comment] 2021-07-22 18:15
The reason we went with yarn 2 a year ago was to remove node_modules and the nested dependencies that comes with it.  There is now a centralized cache that lowers the overall footprint of the code and makes checking modules much easier.

With that said, yarn 2 has been working find with v8 of mocha for that whole time with only a couple minor updates to yarn (went from 2.2.3 to 2.4.2 in that time).  It wasn't until mocha did the major update to v9 that mocha stopped working.  I'm hesitant to say forcing the usage of node_modules is the correct way to fix it or that it's a core problem with yarn and/or pnp when it was working.  Is there any other changes from v8 - v9 that could have disrupted how mocha loads/handles dependency modules?

I'm willing to help test out possible fixes on the mocha side as well as open an issue yarn berry to see if it is.  But as I said above usually the thing that changes tends to be the cause of new errors.

If you can provide a quick run down of how mocha reads the files and how that flows through the various parts of the lib I can try debugging and see if I can find a root cause.

**Comment by juergba** [comment] 2021-07-22 18:32
First of all Mocha uses pure Node features to load test files, we don't run our own loader hooks or whatever (as Yarn PnP probably does).

Since v9.0.0 Mocha uses Node's dynamic `import()` which is able to load both CommonJs and EMS test files into CJS modules (Mocha is a CJS package). This is valid for Node >= v12.22.

Yarn offers [support via plugins](https://yarnpkg.com/features/pnp#support-via-plugins) for some packages, but none for Mocha.

Yes, opening an issue in yarn berry would help, thank you.

**Comment by Drethic** [comment] 2021-07-22 18:51
I've made a report with yarn about the issue.  I'll also poke at lib/esm-utils.js as I have time to see if I can see where in .pnp.js it may be throwing it off.  I assume with the node_modules patch you mentioned lib/esm-utils.js has a different output for the modules.  Would you be willing to share that so I have a point of reference while hacking pnp.

**Comment by juergba** [comment] 2021-07-22 19:01
Thank you. Could you add to your issue, please:
- it's **dynamic** import
- yarn's own CI mocha test are not running correctly

Do you mean this output (without PnP)?
```
<ref *1> Module {
  id: 'D:\\temp\\mocha-yarn-bug-master\\test-mocha-and-chai.spec.js',
  path: 'D:\\temp\\mocha-yarn-bug-master',
  exports: {},
  parent: undefined,
  filename: 'D:\\temp\\mocha-yarn-bug-master\\test-mocha-and-chai.spec.js',
  loaded: true,
  children: [
    Module {
      id: 'D:\\temp\\mocha-yarn-bug-master\\node_modules\\chai\\index.js',
      path: 'D:\\temp\\mocha-yarn-bug-master\\node_modules\\chai',
      exports: [Object],
      parent: [Circular *1],
      filename: 'D:\\temp\\mocha-yarn-bug-master\\node_modules\\chai\\index.js',
      loaded: true,
      children: [Array],
      paths: [Array]
    }
  ],
  paths: [
    'D:\\temp\\mocha-yarn-bug-master\\node_modules',
    'D:\\temp\\node_modules',
    'D:\\node_modules'
  ]
}
```

**Comment by merceyz** [comment] 2021-07-22 19:16
This issue boils down to the fact that Yarn PnP doesn't support ESM yet https://github.com/yarnpkg/berry/issues/638

> add "@yarnpkg/plugin-node-modules": "*" to package.json
https://github.com/mochajs/mocha/issues/4693#issuecomment-885126723

That's an unnecessary step, it wont be used by the CLI

**Comment by juergba** [comment] 2021-07-23 08:18
@Drethic How are you going to proceed in this case?
@merceyz How long will it take to implement your PR in Yarn PnP?

Otherwise I could offer an environment variable (eg. MOCHA_UNSTABLE_ESM) which opens a back door to the past.
Patching _lib/esm-utils.js_:
```
const hasStableEsmImplementation = (() => {
  if (Boolean(process.env.MOCHA_UNSTABLE_ESM) === true) return false;
```
@Drethic if yes, could you test this code with your project, please?

@giltayar feedback would be nice.

**Comment by Drethic** [comment] 2021-07-23 12:05
@juergba We had planned to stick with 8.4.0 in the short term until yarn could patch.  But I'd be happy to test out that code.  Should I just patch my zip?

**Comment by arcanis** [comment] 2021-07-23 12:43
> @merceyz How long will it take to implement your PR in Yarn PnP?

We're planning to land ESM support in Yarn 3.1, in a month or two. Note however that this require us to use [ESM loaders](https://nodejs.org/api/esm.html#esm_loaders), which are currently flagged experimental (and don't support well things like loader composition, iirc), so ESM still has some noticeable drawbacks at the moment.

However, there's still something I don't understand - you seem to have a [fallback](https://github.com/mochajs/mocha/blob/master/lib/esm-utils.js#L51-L53) that goes through `require`, so why doesn't it kick in? 🤔

**Comment by juergba** [comment] 2021-07-23 14:23
@arcanis the dynamic import does not fail. Take following example without Mocha:

```js
// test-dep.js
exports.go = function() {console.log('inside dependency')};
```
```js
// test.js
import('file:///D:/mocha-fork/test-dep.js').
  then( module => {
    console.log(require.cache['D:\\mocha-fork\\test-dep.js']); 
    module.go() }
);
```

If I remember well, `yarn run test` runs successfully. The `required.cache` looked strange though ..?

**Comment by juergba** [comment] 2021-07-23 14:33
@Drethic 

> Should I just patch my zip?

Yes, just as you did with your first `console.log()` test. I don't promise anything, as Mocha's ESM implementation is not my child.

**Comment by giltayar** [comment] 2021-07-24 04:45
@arcanis @juergba just saw this. The fallback to CJS kicks in only on the following error codes: 

```
ERR_MODULE_NOT_FOUND
ERR_UNKNOWN_FILE_EXTENSION
ERR_UNSUPPORTED_DIR_IMPORT
```

If for some reason the dynamic import throws something else, then the fallback won't be called. Let me try the demo repo and see where the problem is.

**Comment by giltayar** [comment] 2021-07-24 05:15
@arcanis OK, checked the repo. Some not surprising and surprising conclusions:

1. Not surprising: when running the "old" load code in `esm-utils.js`, which first does `require` and fallbacks to `import` if necesary, the tests work.
2. Surprising: when running the new for v9 `import`-first code, the `import` succeeds, but nothing is loaded (I added `console.log`-s to the test and they were not shown. So my conjecture above was wrong: no exception happens.

(I patched `esm-utils.js` with `console.log`-s to verify the above)

So...

From what I know of Yarn Berry, it patches the hell out of Node.js so that all things related to loading modules goes through it. My guess is that there is something wrong in the patching in the specific path that Node.js runs through when doing a dynamic import of a CJS file.

To prove this, I wrote a small _CJS_ file:

```js
// x.j
(async () => {
const x = await import('./test-mocha-assert.spec.js');

console.log(x)
})()
```

And ran it using `yarn node x.js`.

The `import` "worked", but the module was not loaded.

So your problem is not really Mocha, but rather dynamic import used in CJS files. This is true even if it's a dynamic import of a CJS file.

As all of the above is CJS, and no ESM is involved, this is not a Mocha problem, but rather a Yarn Berry with the path Node.js takes in CJS to `import` a CJS file.

**Comment by arcanis** [comment] 2021-07-24 09:16
Oh that's very interesting - definitely something we'll want to look at. I don't know if we'll be able to do something (the classic Node esm codepath is doing itself a lot of magic when crossing from esm to cjs and the other way around), but it'd be nice to at least know exactly what happens. Thanks for the details your provided!

**Comment by merceyz** [comment] 2021-07-24 09:51
That issue is fixed in https://github.com/yarnpkg/berry/pull/2161, I'll extract it out to a separate PR so it works in cases where Node can access the files on its own (files not in zip archives)

**Comment by giltayar** [comment] 2021-07-25 03:51
@arcanis note that we can still provide a MOCHA_DISABLE_IMPORT environment flag that disables `import`-ing and enables you to use Mocha >8, as suggested by @juergba

**Closed** 2021-07-28 06:40 UTC
Labels: integration

**Comment by charlessuh** [comment] 2021-08-07 03:36
Question: should "0 passing" have a process exit status that indicates an error instead of success? Bugs like this could have the potential to give false positives, such as in CI/CD environments where successful tests can lead to automatic deploys.
